### ISSUE TITLE
Infinite indentation of multi-line comments

### ISSUE THREAD

**Issue by 0lightbee0** [vuejs/vetur#1329] opened 2019-06-11 03:08 UTC
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- OS: Linux x64 4.19.45-1-MANJARO
- Vetur version: 0.21.1
- VS Code version: 1.34.0
- Electron: 4.1.4
- Chrome: 69.0.3497.128
- Node.js: 10.11.0
- V8: 6.9.427.30-electron.0

## Problem

When i formatting the script block in the vue file, The following problems arise.

![深度录屏_选择区域_20190611110320](https://user-images.githubusercontent.com/19899022/59241033-9f4a1380-8c38-11e9-804a-9ccec9e528ca.gif)

**Comment by octref** [comment] 2019-06-19 06:32
Duplicate of #1016.

**Closed by octref** 2019-06-19 06:32 UTC
