### ISSUE TITLE
Is not a module error

### ISSUE THREAD

**Issue by rajinder-yadav** [vuejs/vetur#1816] opened 2020-03-30 10:56 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.24.0
- VS Code version: 1.43.0-insider

## Problem
In a TypeScript CLI generated project (no Babel) the following __import__ in "App.vue" reports a "not a module" error!

```ts
// File: App.vue
<script lang="ts">
import HelloWorld from "./components/HelloWorld/HelloWorld.vue";
```

__Error: "HelloWorld.vue is not a module"__

Project builds and runs fine, but Vetur fails to determine the file is a module. 

The file "__HelloWorld.vue__" file contains. 

```html
<template>
  <div>
    <h1>Hello World!</h1>
  </div>
</template>

<script lang="ts" src="./HelloWorld.ts" />
<style scoped lang="stylus" src="./HelloWorld.stylus" />
```

![vetur](https://user-images.githubusercontent.com/439226/77904273-48a6d800-7252-11ea-9c40-f8413e5d2d3b.png)

**Comment by KytoSai** [comment] 2020-03-31 04:44
I have same issue when start a new project nuxtjs with typescript !

Demo: https://prnt.sc/rpvv4p

**Comment by agnauck** [comment] 2020-04-24 20:50
same here. Does anyone have a workaround for this issue?

**Comment by MrTomek** [comment] 2020-04-25 22:12
Problem in nestjs when creating a new project.
Probably doesn't detect <script>

**Comment by MrTomek** [comment] 2020-04-25 22:32
Temporary solution.
Add a ruler before error this comment
```javascript
// @ts-ignore
```

**Comment by jvdwijngaard** [comment] 2020-04-28 11:42
Is there any info available about any plans or progress towards a solution to this problem?

It happens for vue files with or without script tags.

Known workarounds:

**Vue files without script tag**
- Adding script tag with dummy export
`<script>export default{}</script>`

- Adding `// @ts-ignore`

**Vue files with script tag with src attribute set to external script file (ts/js)**
- Instead of using src attribute, import external script and export as default
```
<script lang="ts">
import component from './component';
export default component;
</script>
```

**Comment by MrTomek** [comment] 2020-05-10 12:24
https://github.com/vuejs/vetur/issues/762

The problem disappears when you run the project in a direct folder vue / nuxt etc..
For example: Tree Folder
```
public
   - index.html
src            < --- (main folder eg nuxt, vue-cli )
   - assets
   - components
   - dist
   - ...
...
```
Open Vscode in main folder eg nuxt, vue-cli

**Comment by JE-lee** [comment] 2020-05-26 14:04
Maybe it's just because the component doesn't have a default export 
[Similar question](https://github.com/nuxt/create-nuxt-app)

**Comment by octref** [comment] 2020-07-30 01:08
Duplicate of #1187, which will be fixed soon.

**Closed by octref** 2020-07-30 01:08 UTC
Labels: duplicate

**Comment by Eagon7** [comment] 2023-01-29 12:38
use volar
