### ISSUE TITLE
Vetur 0.26.x is no longer applying changes for eslint / prettier

### ISSUE THREAD

**Issue by geoidesic** [vuejs/vetur#2126] opened 2020-08-07 07:35 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.26.1
- VS Code version: 1.47.3

## Problem
Yesterday Vetur was working fine, it would fix my VueJS SFC files on save. I've made no changes to VsCode settings. Today Vetur no longer fixes my code. I've had to roll back to v0.25.0 to get it to work again.

## Reproducible Case
The steps are simple in my case: open any SFC VueJS file, write  some non-eslint-compliant code and hit save. It should correct the code to eslint standard. 

Here is my `settings.json`:

```
{
  // "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.codeActionsOnSave": {
    "source.fixAll": true
  },
  "jest.pathToJest": "yarn test:unit",
  "jest.showCoverageOnLoad": true,
  "php-cs-fixer.executablePath": "${extensionPath}/php-cs-fixer.phar",
  "php-cs-fixer.lastDownload": 1596197060819,
  "php-cs-fixer.autoFixBySemicolon": true,
  "php-cs-fixer.onsave": true,
  "stylusSupremacy.insertBraces": false,
  "stylusSupremacy.insertSemicolons": false,
  "vetur.format.defaultFormatter.html": "prettyhtml",
  "vetur.format.defaultFormatter.js": "prettier-eslint",
  "vetur.format.scriptInitialIndent": true,
  "vetur.format.styleInitialIndent": true,
  "window.zoomLevel": 0,
  "diffEditor.ignoreTrimWhitespace": true,
  "[vue]": {
    "editor.defaultFormatter": "octref.vetur"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.tabSize": 2,
  "editor.detectIndentation": false,
  "editor.fontFamily": "Fira Code",
  //"Monaco, Fira Code, Menlo, 'Courier New', monospace",
  "editor.fontLigatures": true
}
```
Seems to relate to https://github.com/vuejs/vetur/issues/2116, (which the author closed in impatience).

**Comment by geoidesic** [comment] 2020-08-07 07:39
Seems to relate to https://github.com/vuejs/vetur/issues/2116, (which the author closed in impatience).

**Comment by octref** [comment] 2020-08-07 08:21
Duplicate of #2125.

**Closed by octref** 2020-08-07 08:21 UTC
Labels: duplicate
