### ISSUE TITLE
Report missing component imports as warnings/errors

### ISSUE THREAD

**Issue by michaelschufi** [vuejs/vetur#2707] opened 2021-02-17 18:16 UTC
- [x] I have searched through existing issues

## Feature Request

In the following code, the missing import for the Logo component should report a warning/error.

```vue
<template>
  <div>
    <Logo />
    {{ foo }}
  </div>
</template>

<script>
import * as _ from 'lodash'

export default {
  props: ['foo', 'bar']
}
</script>
```

**Why?**
This will make catching missing imports easier, e.g. with Nuxt without its auto-import feature.

**Note**
Additionally, we should be able to import the missing component with a "Quick Fix..." action - but this might be a different issue and a temporary workaround is the auto-completion import suggestion.

**Comment by yoyo930021** [comment] 2021-02-22 04:29
Duplicate of #1997

**Closed** 2021-02-22 04:29 UTC
Labels: duplicate
