### ISSUE TITLE
Closed label Wrap in template blocks break the highlighting

### ISSUE THREAD

**Issue by SuperKieran** [vuejs/vetur#1318] opened 2019-06-05 07:45 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: v0.21.0
- VS Code version: 1.34.0

## Problem

Problem Screenshot:
![](https://raw.githubusercontent.com/SuperKieran/misc/master/bug.png)
![](https://raw.githubusercontent.com/SuperKieran/misc/master/right.png)

## Reproducible Case

https://github.com/SuperKieran/misc/blob/master/render-bug.vue

**Comment by octref** [comment] 2019-06-19 05:39
Duplicate of #1211.

**Closed by octref** 2019-06-19 05:39 UTC
Labels: duplicate
