### ISSUE TITLE
intellisense bugs in *.vue SFC with lang=tsx

### ISSUE THREAD

**Issue by Plasmatium** [vuejs/vetur#569] opened 2017-12-04 16:52 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.11.3
- VS Code version: 1.18.1

## Problem
I tried to use `*.vue` with `<script lang="tsx"> for SFC, and located a bug(may be) in ts-loader, and issued a [PR](https://github.com/TypeStrong/ts-loader/pull/687) to fix it. [Demo](https://github.com/Plasmatium/vue-plc-ts) for test is running well.

But there has been some of intellisense and highlight issues:
```javascript
  // if use lang=tsx, the "string" type notation is not highlight, 
  //and this.msg can't be derived to a string type

  // if use lang=ts, hightlight and type derivation works well, 
  // but this.msg alone is still derived as any and cause an error,
  // and jsx syntax is not allowed in lang=ts
  computed: {
    testMsg: function ():string {
      return (this as any).msg + ' powered by typescript & tsx'
    }
  },
```

And in render function, `data` and `computed` and maybe others all can't be found on `this`.

Another problem is that, I wrote a jsx.d.ts:
```javascript
// ./src/types/jsx.d.ts
import Vue, { VNode } from 'vue'

declare global {
  namespace JSX {
    interface Element extends VNode {}
    interface ElementClass extends Vue {}
    interface ElementAttributesProperty {
      $props: {}
    }

    interface IntrinsicElements {
      [elemName: string]: any
    }
  }
}

```
But that seems like only take an effect on `*.tsx` files, not on `*.vue`'s <script lant="tsx"> region, I had to write above code again in `*.vue`. This may not be a bug on vetur, but I can't figure out a way to resolve it.

## Reproducible Case
[Test this demo repo.](https://github.com/Plasmatium/vue-plc-ts)

**Comment by HerringtonDarkholme** [comment] 2017-12-05 03:25
> And in render function, data and computed and maybe others all can't be found on this.

This is caused by cyclic dependency. Please refer to  https://vuejs.org/v2/guide/typescript.html#Annotating-Return-Types

> if use lang=tsx, the "string" type notation is not highlight

<img width="621" alt="screen shot 2017-12-05 at 11 18 32 am" src="https://user-images.githubusercontent.com/2883231/33588483-0cce9a82-d9ae-11e7-9069-9ab45edfa24e.png">

> But that seems like only take an effect on *.tsx files, not on *.vue's <script lant="tsx"> region

I think you need to reload vscode. This is probably a duplicate of https://github.com/vuejs/vetur/issues/355 .

**Closed** 2017-12-05 05:44 UTC
Labels: question

**Comment by Plasmatium** [comment] 2017-12-05 14:20
Thanks for your reply, @HerringtonDarkholme 
> if use lang=tsx, the "string" type notation is not highlight. 
I mean the notation `: string`, not the string content its self. It is brown in my editor under lang=ts, and white under lang=tsx. Finally I found it is the theme problem with different TM scope between lang=tsx and lang=ts
