### ISSUE TITLE
Broken folding in VS Code.

### ISSUE THREAD

**Issue by wsjscss** [vuejs/vetur#2247] opened 2020-09-04 13:26 UTC
## Info

- Platform: macOS
- Vetur version: 0.27.1
- VS Code version: 1.48.2

## Problem
When enable extension the folding icon disappear and can't be clicked.
Here is short video: https://share.getcloudapp.com/2Nuy969G
Also if enable Vetur and change file type to HTML, then folding arrows appear again.

**Comment by yoyo930021** [comment] 2020-09-04 13:27
Duplicate of #2234

**Closed by yoyo930021** 2020-09-04 13:27 UTC
Labels: duplicate
