### ISSUE TITLE
Syntax highlighting error when missing semicolon

### ISSUE THREAD

**Issue by Moerj** [vuejs/vetur#319] opened 2017-07-08 10:08 UTC
![qq20170708-180538 2x](https://user-images.githubusercontent.com/13795438/27984423-4fa65406-6408-11e7-80fc-5e75fffe797a.jpg)
![qq20170708-180611 2x](https://user-images.githubusercontent.com/13795438/27984426-55780f5a-6408-11e7-943c-0ca887328b6c.jpg)

import key Syntax highlighting error when missing semicolon.

Vetur version: 0.8.6
VScode version: 1.13.1

**Comment by octref** [comment] 2017-07-08 10:11
I won't try to type all the code in from screenshot.
Please provide info and reproducible case:

![image](https://user-images.githubusercontent.com/4033249/27984453-ec92ba68-63de-11e7-9224-468b221d2157.png)

**Comment by Moerj** [comment] 2017-07-08 10:31
already edited

**Comment by octref** [comment] 2017-07-08 11:57
https://github.com/Microsoft/vscode/issues/30287

**Comment by octref** [comment] 2017-08-05 09:58
This seems to be fixed and pulled in VSCode repo. Should be automatically fixed with next VSCode release this week.

**Closed by octref** 2017-08-05 09:58 UTC
Labels: grammar, upstream
