### ISSUE TITLE
When the template code exceeds 387 lines, format code and  go to end of template

### ISSUE THREAD

**Issue by alvis-lee** [vuejs/vetur#1070] opened 2019-01-22 12:43 UTC
## Info

- Platform:  Win 7
- Vetur version:0.14.5
- VS Code version:1.30.2(system setup)

## Problem

When the `<template></template>` code exceeds 387 lines, 
I formatted the code  (Alt+Shift+F) , the mouse cursor will be go to `</template>`

Before formatting（Alt+Shift+F）：
![image](https://user-images.githubusercontent.com/3367338/51536226-dab09500-1e85-11e9-8613-0925dc32fab3.png)

After formatting（Alt+Shift+F）：
![image](https://user-images.githubusercontent.com/3367338/51536264-fae05400-1e85-11e9-8008-0fcc54d907a6.png)

![abc](https://user-images.githubusercontent.com/3367338/51577477-f43cf580-1ef4-11e9-9b04-a883a2adf545.gif)

**Comment by octref** [comment] 2019-03-14 22:44
Duplicate of #841.

**Closed by octref** 2019-03-14 22:44 UTC
