### ISSUE TITLE
Support the <script setup> syntax in SFCs

### ISSUE THREAD

**Issue by dsine-de** [vuejs/vetur#3108] opened 2021-08-12 08:47 UTC
## Feature Request

See https://v3.vuejs.org/api/sfc-script-setup.html

Currently there are no errors with the new `<script setup>` syntax, but variables defined in the script are displayed (e.g. component imports, computed etc.) as dimmed when they are never read in the script itself, because you don't have to `return` them with this syntax and there is a tooltip `<variable> is declared but its value is never read. Vetur(6133)`.

**Comment by zs-g** [comment] 2021-08-13 02:10
I also encountered the same problem

**Comment by Gumper-x** [comment] 2021-08-13 11:50
I have the same problem

**Comment by Azema4ka** [comment] 2021-08-14 17:11
I also encountered the same problem

**Comment by lupas** [comment] 2021-08-15 13:49
see also https://github.com/vuejs/vetur/issues/2296

**Comment by SKFrozenCloud** [comment] 2021-08-21 16:57
I also get ```Module '"mycomponent.vue"' has no default export.```

**Comment by yoyo930021** [comment] 2021-10-04 12:44
Duplicate of #2296

**Closed by yoyo930021** 2021-10-04 12:44 UTC
