### ISSUE TITLE
Assigning elements from a stylus hash adds a set of parentheses on each save

### ISSUE THREAD

**Issue by nachocab** [vuejs/vetur#638] opened 2018-01-14 14:23 UTC
```
<style lang="stylus" scoped>
$abc = {
  one: 1,
  two: 2
}
$abc[three] = $abc.one + 2 // 👎  becomes: $abc[three] = ($abc.one + 2)
$abc.four = $abc[two] + 2 // 👎 becomes: $abc.four = ($abc[two] + 2)
$abc[five] = 2 + 3 // 👍 nothing gets added
$abc.six = 6 // 👍 nothing gets added 
</style>
```

Each time you save, a new set of parentheses gets added. Eventually you might end up with something like `$abc[three] = ((((((((((((($abc.one + 2)))))))))))))`

**Comment by nachocab** [comment] 2018-01-14 16:09
Also, the same happens when adding multiple box shadows (separated by commas):

```
box-shadow: inset 0 -9px 0 ((($color.blue))), inset 0 9px 0 ((($color.blue)))
```

**Comment by HerringtonDarkholme** [comment] 2018-01-15 06:31
cc @ThisIsManta 

I cannot reproduce @nachocab 's report, but I do find other glitch.

Before:
<img width="279" alt="screen shot 2018-01-15 at 2 30 43 pm" src="https://user-images.githubusercontent.com/2883231/34929767-b6b56f54-fa00-11e7-98cf-fd6d908b7080.png">

After: 
<img width="295" alt="screen shot 2018-01-15 at 2 30 49 pm" src="https://user-images.githubusercontent.com/2883231/34929768-b6de5e1e-fa00-11e7-832a-f4131abd0aef.png">

**Comment by ThisIsManta** [comment] 2018-01-18 17:34
This should be fixed by https://github.com/vuejs/vetur/pull/659

**Closed** 2018-01-18 18:33 UTC
Labels: bug, formatter
