### ISSUE TITLE
Outdated imports over samba shares

### ISSUE THREAD

**Issue by qgates** [vuejs/vetur#1758] opened 2020-03-06 23:57 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.23.0
- VS Code version: 1.42.1

## Problem

I have a Z: drive mapped to a samba share, and vscode loads the project from Z:\project

Function & data parameter types, return types and access specifiers imported from other modules seem not to update in Vetur when modified (and saved). Reloading vscode causes them to be re-read and fixes the issue. Example:

Module 'test.ts'
```typescript
export class TestDb {
  public init(type: string) { ... }
}
```

Module 'xyz.vue'
```vue
...
<script lang="ts">
  import Vue from 'vue'
  import { TestDb } from './test'

export default Vue.extend({
  mounted() {
    let x = new TestDb;
    x.init('foo');
  }
});
```

In module xyz.vue I get a wavy line under `x.init()` with error `Property 'init' is protected and only accessible within class 'TestDb' and its subclasses`, because module 'test.ts' had declared method `init()` as `protected` when the project was loaded, even though it was then changed to `public` and saved.

If I restart vscode, everything works correctly because vetur has now re-read test.ts and detected the correct access specifier.

This problem only exists when loading the project from a samba share, and not when the project is loaded from a local drive.

**Comment by qgates** [comment] 2020-03-18 14:28
Any further thoughts on this? At the moment any imports from `.ts` files don't reflect in `.vue` files if the `.ts` file changes. The only workaround seems to be restarting vscode on a regular basis.

**Comment by octref** [comment] 2020-06-07 04:30
Duplicate of #1490

**Closed by octref** 2020-06-07 04:30 UTC
