### ISSUE TITLE
templateInterpolationService does not work with PUG template

### ISSUE THREAD

**Issue by boid-com** [vuejs/vetur#2743] opened 2021-03-02 07:22 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.32.0
- VS Code version: 1.53.2

## Problem
Intellisense works great with a standard HTML template in the Vue single file component.

When I use pug as the template language, I get zero intellisense feedback, It seems that Vetur does not try to parse the PUG at all.
```
<template lang="pug">
    div {{datavar}}
```

Pug is properly installed in package.json 
```
    "pug": "^3.0.2",
    "pug-plain-loader": "^1.1.0"
```
And loaded into webpack
```
        cfg.module.rules.push({
          test: /\.pug$/,
          loader: 'pug-plain-loader'
        })
```

Project is using quasar

## Reproducible Case
1) Setup blank vue project template using vue-cli or quasar
2) yarn add -D pug pug-plain-loader
3) modify a component to use PUG language instead of html

**Comment by boid-com** [comment] 2021-03-02 07:25
Please vote for #1500

**Comment by yoyo930021** [comment] 2021-03-02 14:33
Duplicate of #1500

**Closed** 2021-03-02 14:33 UTC
Labels: duplicate
