### ISSUE TITLE
<script setup> Introduce sub-components to prompt an error

### ISSUE THREAD

**Issue by zs-g** [vuejs/vetur#3114] opened 2021-08-17 05:52 UTC
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [ ] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version: v0.34.1
- VS Code version: v1.59.0
- Vue  version:  ^3.2.2

![1629179476(1)](https://user-images.githubusercontent.com/46895375/129670843-b1f138e5-1992-4b6a-bbbb-f7fde55c48ce.jpg)

![1629179641(1)](https://user-images.githubusercontent.com/46895375/129671073-6c32fb8f-958f-4ef1-83e0-916bc5b71de3.jpg)

**Comment by arpowers** [comment] 2021-08-17 22:13
@yoyo930021 @zs-g 

having the same issue with Vue 3.2 and `script setup`.... 

Either you can use without `lang="ts"` which causes TS linting errors or, if you add the 'ts`, then variables are flagged as unused.

**Comment by wqqwqq666** [comment] 2021-08-20 08:14
same issue, when will it be repaired ?

**Comment by SKFrozenCloud** [comment] 2021-09-25 18:02
'Volar' seems to be an option

**Comment by runarb** [comment] 2021-09-27 09:41
Same issue for "top-level bindings" such as variables and functions being used directly in the template:

![image](https://user-images.githubusercontent.com/440339/134884627-ee77e565-1edf-4380-8d20-ba288faf7ba2.png)

**Comment by yoyo930021** [comment] 2021-10-04 12:45
Duplicate of #2296

**Closed by yoyo930021** 2021-10-04 12:45 UTC
