### ISSUE TITLE
vetur.format.defaultFormatter.js options

### ISSUE THREAD

**Issue by basaran** [vuejs/vetur#2480] opened 2020-11-16 22:29 UTC
Hello,

I failed to find documentation regarding the vetur.format.defaultFormatter.js when used with prettier-eslint.

```javascript
    "vetur.format.defaultFormatter.scss": "prettier",
    "vetur.format.defaultFormatter.css": "prettier",
    "vetur.format.defaultFormatter.js": "prettier-eslint",
    "vetur.format.defaultFormatter.html": "prettier",
    "vetur.format.enable": true,
    "vetur.validation.template": false,
```

I can get the code to format if the JS option is set to `prettier` but nothing seems to be happening with `prettier-eslint`.

I have these installed both globally and locally:

```
./node_modules/.bin/eslint
./node_modules/.bin/prettier
./node_modules/.bin/prettier-eslint
```

```
/home/michael/.yarn/bin/eslint
/home/michael/.yarn/bin/prettier
/home/michael/.yarn/bin/prettier-eslint
```

and I also made sure the path is correct:
```
PATH=/home/michael/.yarn/bin:....
```

and I also have .eslintrc and .prettierrc in the project folder. VS Code `eslint extension` can reach to it just fine if I enable it, and `prettier extension` the same way if I enable it. I also have no issues using the `prettier-eslint extension` if I enable it.

If I use vetur with 'prettier' (while the vs code extension is disabled), that also works fine.  I also verified if I run the prettier-eslint through CLI, it returns the formatted file as expected.

```
prettier-eslint /home/michael/websites/port/src/App.vue
```

After several days, I'm stuck as to why this "prettier-eslint" inside vetur won't be working. Thank you for your time and the great vetur.

**Comment by yoyo930021** [comment] 2020-11-17 02:20
Duplicate of #2477 
Open `vetur.useWorkspaceDependencies: true`?

**Comment by basaran** [comment] 2020-11-17 18:03
Hello,

using `vetur.useWorkspaceDependencies: true` helped, but not all the way. It seems, it is still not reading the `.eslintrc` settings.

I verified from the language server log, that the prettier-eslint is being loaded fine.

```
[INFO ] Find node_modules paths in /home/michael/websites/port - 338ms
[INFO ] Loaded typescript@3.9.7 from /home/michael/websites/port/node_modules/typescript.
[INFO ] Loaded prettier@2.1.2 from /home/michael/websites/port/node_modules/prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded prettier-eslint@11.0.0 from /home/michael/websites/port/node_modules/prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded @prettier/plugin-pug@1.10.1 from /home/michael/websites/port/node_modules/@prettier/plugin-pug.
Vetur initialized
```

I removed `template` and `style` sections from the vue sfc, and after saving the vue file, the the log shows:

[DEBUG] Using prettier-eslint. Options
{"trailingComma":"es5","tabWidth":2,"semi":true,"printWidth":100,"singleQuote":false,"htmlWhitespaceSensitivity":"ignore","useTabs":false,"parser":"babel","pluginSearchDirs":["/home/michael/websites/port"]}

This shows it is in fact reading the `.prettierrc.js` because I have, the `tabWidth` set to 2 as an override, but I see no mention of the eslint configuration at `.eslintrc`.

This is the `.eslintrc` I am using, which formats fine with the `eslint extension` while enabled.

```json
{
    "root": true,
    "env": {
        "node": true
    },

    "extends": [ "eslint:recommended", "plugin:vue/recommended" ],
    "parserOptions": {
        "parser": "babel-eslint"
    },
    "plugins": [ "html", "vue" ],

    "rules": {
        "space-in-parens": [ "error", "always" ],
        "array-bracket-spacing": [ "error", "always" ],
        "no-unexpected-multiline": [ "off" ],
        "no-unused-vars": [ "off" ],
        "object-curly-spacing": [ "error", "always" ],
        "operator-linebreak": [ "error", "before" ],
        "indent": [ "error", 8, {
            "SwitchCase": 1
        } ],
        "vue/max-attributes-per-line": [ "error", {
            "singleline": 2,
            "multiline": {
                "max": 1,
                "allowFirstLine": false
            }
        } ],
        "vue/component-name-in-template-casing": [ "error", "PascalCase" ]
    }
}
```

I also tried an rc file without `eslint plugins`

```json
{
    "root": true,
    "env": {
        "node": true
    },

    "extends": [ "eslint:recommended" ],
    "parserOptions": {
        "parser": "babel-eslint"
    },


    "rules": {
        "space-in-parens": [ "error", "always" ],
        "array-bracket-spacing": [ "error", "always" ],
        "no-unexpected-multiline": [ "off" ],
        "no-unused-vars": [ "off" ],
        "object-curly-spacing": [ "error", "always" ],
        "operator-linebreak": [ "error", "before" ],
        "indent": [ "error", 8, {
            "SwitchCase": 1
        } ]
    }
}
```

All the testing was done with `eslint` and `prettier` extensions disabled, to make sure nothing is getting in the way.

**Closed** 2020-11-25 12:54 UTC
Labels: question
