### ISSUE TITLE
vetur does not see the use of variables in the composition API 

### ISSUE THREAD

**Issue by Mnigos** [vuejs/vetur#3115] opened 2021-08-17 16:56 UTC
- [✔️] I have searched through existing issues
- [✔️] I have read through [docs](https://vuejs.github.io/vetur)
- [✔️] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [✔️] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Win
- Vetur version: 0.34.1
- VS Code version: latest

## Problem

`Footer.vue`
```vue
<template>
  <nav class="text-xl mt-6">
    <router-link class="icon-btn mx-2" to="/" :title="t('button.home')">
      <carbon-campsite />
    </router-link>

    <button class="icon-btn mx-2 !outline-none" :title="t('button.toggle_dark')" @click="toggleDark">
      <carbon-moon v-if="isDark" />
      <carbon-sun v-else />
    </button>

    <a class="icon-btn mx-2" :title="t('button.toggle_langs')" @click="toggleLocales">
      <carbon-language />
    </a>
  </nav>
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'
import { isDark, toggleDark } from '~/logic'

const { t, availableLocales, locale } = useI18n()

const toggleLocales = () => {
  // change to some real logic
  const locales = availableLocales
  locale.value = locales[(locales.indexOf(locale.value) + 1) % locales.length]
}
</script>

```

Errors:
`All imports in import declaration are unused.`
`'t' is declared but its value is never read.`
`'toggleLocales' is declared but its value is never read.`

As you can see I'm using this variables inside template but vetur don't recognize that.

**Comment by chuckntaylor** [comment] 2021-08-18 14:11
You likely need to update your `.eslintrc` rules.
There is a relatively new `vue/script-setup-uses-vars` rule that helps with this.
[https://eslint.vuejs.org/rules/script-setup-uses-vars.html](https://eslint.vuejs.org/rules/script-setup-uses-vars.html).

Basically add the rule `'vue/script-setup-uses-vars': 1` to your eslint config, and make sure you have at least eslint-plugin-vue v7.13.0 or higher.

**Comment by yoyo930021** [comment] 2021-10-04 12:45
Duplicate of #2296

**Closed by yoyo930021** 2021-10-04 12:45 UTC
