### ISSUE TITLE
error occurred when using v-for with a range

### ISSUE THREAD

**Issue by icecola2018** [vuejs/vetur#738] opened 2018-03-21 16:14 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.11.7
- VS Code version: 1.21.1

## Problem

error occurred when using v-for with a range
![image](https://user-images.githubusercontent.com/36227102/37721798-65373598-2d65-11e8-94cf-da4f5dc78b2d.png)

message:
```
[vue/require-v-for-key]
Elements in iteration expect to have 'v-bind:key' directives.
```

## Reproducible Case
In a `.vue` file:
```vue
<template>
<div>
    <p v-for="i in 25">
        hello
    </p>
</div>
</template>
```

**Comment by LinusBorg** [comment] 2018-03-21 16:31
Well, it's not an error - you re using eslint-plugin-vue which tells you to put a `key` on the `<p>`

https://vuejs.org/v2/guide/list.html#key

**Comment by octref** [comment] 2018-03-21 17:54
@LinusBorg Thanks for jumping in to help. I'm wondering if we could do better. If eslint-plugin-vue could offer urls Vetur could render them on error hover too. I'm thinking linking to https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/valid-v-bind.md or for some errors, the official doc / style guide. What do you think?

**Comment by LinusBorg** [comment] 2018-03-21 18:56
That would be great. Maybe open an issue with the guys of the eslint plugin?

**Comment by octref** [comment] 2018-03-22 00:10
Closing this as duplicate of #261.
Meanwhile I opened https://github.com/vuejs/eslint-plugin-vue/issues/439.

**Closed by octref** 2018-03-22 00:10 UTC
