### ISSUE TITLE
can not save

### ISSUE THREAD

**Issue by grace618** [vuejs/vetur#3650] opened 2023-02-20 09:12 UTC
0.37.1 Cannot save while formatting

**Comment by disvst** [comment] 2023-02-20 11:21
@grace618 I have also some trouble saving. Formatting is very slow, even in a simple component. is it your issue?

**Comment by dmke** [comment] 2023-02-20 12:01
Same here. After hitting <kbd>Ctrl</kbd>+<kbd>s</kbd> in a `*.vue` file, nothing happens for a few seconds.

Then a notification appears:

> Saving 'file.vue': Getting code actions from ''Vetur', 'ESLint''

Cancelling this notification will save the file, but skip ESLint.

There's also a "Load project: '`path`'" notification on the status bar, which does not finish loading.

![image](https://user-images.githubusercontent.com/327411/220100249-7115eafc-27cc-4cb2-bed5-38548239f513.png)

I haven't hat this behaviour until I reloaded VSCode a few moments ago.

**Comment by VojtechLanka** [comment] 2023-02-20 12:16
Seem to be problem with the latest version. Instaling `v0.36.1` fixed the issue.

**Comment by dmke** [comment] 2023-02-20 12:22
Can confirm, rolling back to v0.36.1 works.

v0.37.0 is not available; v0.37.1 and v0.37.2 don't work.

**Comment by jakeflorentine** [comment] 2023-02-20 22:10
I am also seeing this same issue

**Comment by jakeflorentine** [comment] 2023-02-20 22:11
> 

v0.37.2

**Comment by meguoe** [comment] 2023-02-21 01:46
Are there conflicts caused by other plug-ins? After upgrading to v0.37.2, everything is normal

**Comment by bailuochen** [comment] 2023-02-21 03:04
v0.37.2 

load project: xxxxxxxxx

Format is abnormal, and No code prompt

**Comment by aaaa-coder** [comment] 2023-02-21 03:25
0.37.2bug：
1、无法保存文件
2、代码提示异常
3、缩放格式异常

**Comment by bailuochen** [comment] 2023-02-21 03:35
> 0.37.2bug： 1、无法保存文件 2、代码提示异常 3、缩放格式异常

先降低版本 使用v0.36.1吧

**Comment by yoyo930021** [comment] 2023-02-21 07:18
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by wishong** [comment] 2023-02-21 08:21
use 0.36.1

**Comment by Sjkuu** [comment] 2023-02-21 12:29
cause by the newest version! It's been bothering me all day

**Comment by yoyo930021** [comment] 2023-02-22 02:35
> > Please provide a repro case. https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
> 
> Repro case is described above. Load newest Vetur in a workspace which used a previous Vetur version.

In my any project, I don't have any problem.
Please open my link to generate your any repro case.
I would like to solve the problem. but I can't repro it. I can't do anything about it

**Comment by dmke** [comment] 2023-02-22 08:34
I cannot yet reproduce this issue with the linked veturpack repo (installing eslint, eslint-plugin-vue and removing prettier alone did not suffice).

**Comment by yoyo930021** [comment] 2023-02-23 05:32
Duplicate of #3657 and fix in v0.37.3

**Closed by yoyo930021** 2023-02-23 05:32 UTC
Labels: duplicate

**Comment by dmke** [comment] 2023-02-23 11:27
Can confirm, 0.37.3 works for me again. Thank you very much!
