### ISSUE TITLE
Parse error with template literal in component key

### ISSUE THREAD

**Issue by Made-of-Clay** [vuejs/vetur#1234] opened 2019-04-24 19:56 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Ubuntu 18.04.2 LTS
- Vetur version: 0.19.0
- VS Code version: 1.33.1

## Problem

Vetur just started erroring when using template literal in markup. It worked earlier today, but I have recently closed VS Code and reopened it to find this error. The variables being looped exist in the `data` definition, so that's not the issue. [Here are some screenshots](https://imgur.com/a/MPGOIgv). Other components appear to have errors too.

## Reproducible Case

The problem doesn't seem to occur outside my environment unfortunately. I'm hoping someone will recognize the issue from the screenshot(s).

**Comment by octref** [comment] 2019-04-24 23:34
Can you paste the code content?

Also, try this command `Vetur: Show corresponding virtual file and sourcemap` and put its content here too.

**Comment by Astray-git** [comment] 2019-04-25 03:03
I have a similar error here
```vue
<template>
  <div :id="`${type}`"></div>
</template>
<script>
export default {
  data() { return { type: 'test' } }
}
</script>
```
error: `Cannot find name 'temthis'.Vetur(2304)`

sourcemap
```
====================
Virtual content of Icon.vue.template
Hover, semantic diagnostics, jump to definition and find references are run on this file.
====================

import __Component from "./Icon.vue";
import { __vlsRenderHelper, __vlsComponentHelper, __vlsIterationHelper, __vlsListenerHelper } from "vue-editor-bridge";
__vlsRenderHelper(__Component, function () {
    "\n  ";
    __vlsComponentHelper("div", { props: { "id": temthis.typee> }, on: {}, directives: [] }, []);
    "\n           \n\n                  \n                                                             \n                                                            \n                                    \n\n                 \n            \n                \n                  \n \n\n          \n                                       \n                                                                           \n\n                          \n\n                  \n                              \n                                        \n                            \n       \n                                   \n                                   \n       \n     \n                          \n   \n                  \n                                                    \n                          \n                         \n                                 \n                   \n       \n                        \n     \n               \n   \n \n         \n\n                   \n           \n             \n              \n                         \n                     \n                   \n\n                  \n                           \n   \n \n        \n";
});


====================
SourceMap
from: Icon.vue
to  : Icon.vue.template
[VueFileStart, VueFileEnd, VueFileText] => [TSVirtualFileStart, TSVirtualFileEnd, TSVirtualFileText]
====================

[23, 32, `${type}`] => [264, 278, temthis.typee>]
```

**Comment by ktsn** [comment] 2019-04-25 06:36
Duplicate of #1230.
And I already made a PR for this #1244

**Closed by ktsn** 2019-04-25 06:36 UTC
Labels: need-more-info
