### ISSUE TITLE
Vetur 0.19.1 doesn't recognize v-slot variable

### ISSUE THREAD

**Issue by koiketakayuki** [vuejs/vetur#1240] opened 2019-04-25 02:28 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.19.1
- VS Code version:1.33.1

## Problem
It doesn't recognize variables served by slot-scope/v-slot.
Following code is regarded as problem, which actually shouldn't be.
```
<SomeComponent>
  <template slot-scope="{ data }">
    {{ data }}
    <!-- ErrorMessage: Cannot find name 'data' -->
  </template>
</SomeComponent>
```

**Comment by ktsn** [comment] 2019-04-25 02:31
Duplicate of #1203

**Closed by ktsn** 2019-04-25 02:31 UTC
