### ISSUE TITLE
Syntax Highlighting error in html using strict inequality as of VSCode January 2021

### ISSUE THREAD

**Issue by AnthonyIV** [vuejs/vetur#2806] opened 2021-03-23 19:34 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows and macOS
- Vetur version: Latest (0.33.1)
- VS Code version: Latest (1.52.1 and earlier do not have this issue)

## Problem

![Screen Recording 2021-03-23 at 8 58 17 AM](https://user-images.githubusercontent.com/30813107/112207575-8a9ffb00-8bd4-11eb-839c-0743731de93e.gif)

[Error - 12:31:24 PM] No workspace path found. Vetur initialization failed.
Vetur initialized
[Error - 12:31:24 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 12:31:24 PM] Request textDocument/documentLink failed.
  Message: Unhandled method textDocument/documentLink
  Code: -32601 
[Error - 12:31:24 PM] Request textDocument/colorPresentation failed.
  Message: Unhandled method textDocument/documentColor
  Code: -32601 
[Error - 12:31:24 PM] Request textDocument/foldingRange failed.
  Message: Unhandled method textDocument/foldingRange
  Code: -32601 
[Error - 12:31:24 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 12:31:24 PM] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 
[Error - 12:31:41 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 12:31:42 PM] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 
[Error - 12:31:42 PM] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 
[Error - 12:31:42 PM] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 
[Error - 12:31:43 PM] Request textDocument/hover failed.
  Message: Unhandled method textDocument/hover
  Code: -32601 
[Error - 12:31:43 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 12:31:45 PM] Request textDocument/foldingRange failed.
  Message: Unhandled method textDocument/foldingRange
  Code: -32601 
[Error - 12:31:45 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 12:31:45 PM] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 
[Error - 12:31:46 PM] Request textDocument/foldingRange failed.
  Message: Unhandled method textDocument/foldingRange
  Code: -32601 
[Error - 12:31:46 PM] Request textDocument/documentLink failed.
  Message: Unhandled method textDocument/documentLink
  Code: -32601 
[Error - 12:31:46 PM] Request textDocument/colorPresentation failed.
  Message: Unhandled method textDocument/documentColor
  Code: -32601 
[Error - 12:31:46 PM] Request textDocument/codeAction failed.
  Message: Unhandled method textDocument/codeAction
  Code: -32601 
[Error - 12:31:46 PM] Request textDocument/documentSymbol failed.
  Message: Unhandled method textDocument/documentSymbol
  Code: -32601 

## Reproducible Case

If you have a v-if="typeof something !== 'undefined'" syntax highlighting following this will break in odd and inconsistent ways. Changing it to three =s instead will fix the syntax highlighting. This was not happening prior to VSCode update for January 2021, downloading the November 2020 VSCode version resolves issue.

Simple Vue file:
```
<template>
  <div :id="arg" v-if="typeof blah !== 'undefined'">
    <p :test="typeof junk === 'string'" :class="stuff && 'moreStuff'" 
    @click="doAThing()">
      {{ junk }}
    </p>
    <div id="">

    </div>
    <div>

    </div>
  </div>
</template>
```

**Comment by yoyo930021** [comment] 2021-03-24 02:18
If you open a project in project root with vscode?

Vetur is only support project mode.

**Comment by yoyo930021** [comment] 2021-03-24 03:21
Duplicate of https://github.com/vuejs/vetur/issues/2709

**Closed** 2021-03-24 03:21 UTC
Labels: duplicate
