### ISSUE TITLE
Request textDocument/completion failed

### ISSUE THREAD

**Issue by kobestyle** [vuejs/vetur#296] opened 2017-06-28 02:12 UTC
- [x] I searched through existing issues.
- [x] I have looked through docs at https://octref.github.io/vetur/

## Info

- Platform: macOS
- Vetur version:0.8.6
- VSCode version:1.13.1

## Problem
when coding on *.vue , vue language server frequently show errors below. it feels bad

![image](https://user-images.githubusercontent.com/14803067/27617589-f7ec6532-5be9-11e7-8735-b160c8cda306.png)
## Reproducible Case
![vetur](https://user-images.githubusercontent.com/14803067/27617595-fc2ab34c-5be9-11e7-9c90-305d7322e9a0.gif)

**Comment by HerringtonDarkholme** [comment] 2017-06-28 02:36
Sorry, I cannot reproduce it.

Can you provide a minimal .vue file or repository?

**Comment by topul** [comment] 2017-06-28 03:00
I have the same problem

Platform: Windows 10
Vetur version:0.8.6
VSCode version:1.13.1

it happens when i wrote the computed property , but even if I delete it,  this error is still there

![qq 20170628105636](https://user-images.githubusercontent.com/8213229/27618709-7fe4d5f4-5bf0-11e7-9a94-2221d40b192a.png)

**Comment by HerringtonDarkholme** [comment] 2017-06-28 03:13
Please provide an example `vue` file

**Comment by topul** [comment] 2017-06-28 03:38
@HerringtonDarkholme it's business code, i cannot reproduce it in single file, but i do some tests,
![qq 20170628113426](https://user-images.githubusercontent.com/8213229/27619546-cec2265e-5bf5-11e7-9c06-453106a78e4c.png)
I don't know if that helps

**Comment by BelinChung** [comment] 2017-06-28 06:18
I think it's easy to reproduce this issue after upgrade `vetur` to v0.8.6.
Just click like a monkey... 
Because it will automatically open the `OUTPUT` console, It makes me crazy!!

**Comment by octref** [comment] 2017-06-28 06:34
If you only provide a screenshot there isn't much we can do.
Please try to modify https://github.com/octref/veturpack or one of vue-cli's template for a repro case so we can help you.

@kobestyle Meanwhile, what's your vue version? It seems IntelliSense is not working for you at all.

**Comment by topul** [comment] 2017-06-28 06:52
`<template>
  <div class="page">
    <counter></counter>
    <p>
      To get started, edit files in <code>./client</code> and save.
    </p>
  </div>
</template>

<script>
import Counter from 'components/Counter'

export default {
  components: {
    Counter
  },
  computed: {
    taxInfo (val) {
      this.gs.loading = false
      this.ds.loading = false
      this.gs.model.pwd = ''
      this.ds.model.pwd = ''
      // 国地税都没有验证的情况下，默认展示验证表单
      this.showVerify = !+val.gsState && !+val.dsState
      this.taxInfo = val
      this._getRegion()
    }
  }
}
</script>`

@octref just modify the Home.vue like this, click this._getRegion(), the bug reproduced

**Comment by kobestyle** [comment] 2017-06-28 06:53
@octref the version is 2.3.4

**Comment by octref** [comment] 2017-06-28 07:35
@topul OK I was able to repro both the `hover` and `completion` errors. Will take a look later tonight.

**Comment by tangdw** [comment] 2017-06-29 01:37
how to prevent Vetur open the output console?

**Comment by HerringtonDarkholme** [comment] 2017-06-29 05:28
Sadly, this is TypeScript comiler's insufficiency. If you feed it wrong code like 

```ts
var a = {
    test(val) {
        this.test = val // reassigning method `test`
    }
}
```

It breaks. Consider pasting your script code to a plain JS. If the bug is reproducible in JS, you probably need to open an issue in VSCode.

**Comment by kobestyle** [comment] 2017-06-29 14:17
@HerringtonDarkholme It's ok in JS,  how can we prevent Vetur open the output console automatically? I am so trouble with it all the time.

**Comment by HerringtonDarkholme** [comment] 2017-06-29 14:28
No, it's not ok. VSCode just hides the error output.

@octref do you have any idea if we can suppress error output?

**Comment by octref** [comment] 2017-06-29 22:02
@HerringtonDarkholme https://github.com/vuejs/vetur/blob/master/client/src/htmlMain.ts#L25

F12 into `LanguageClientOptions`. We can set `revealOutputChannelOn` to never.
Think we should do that. When user finds something not working then we can ask them to open the output.

**Comment by octref** [comment] 2017-06-29 22:12
From the next version on, error will be suppressed unless you check it in output.

The root problem is as @HerringtonDarkholme suggested, TS can't handle code like.

```ts
var a = {
    test(val) {
        this.test = val // reassigning method `test`
    }
}
```

It's breaking both hover and completion.
@HerringtonDarkholme do you have a TS bug that tracks this?

And I think this is only for @topul, @kobestyle can you paste your whole vue file?

**Comment by kobestyle** [comment] 2017-06-30 01:30
`
<template>
  <div class="selffetch-address__container">
    <div>for test</div>
  </div>
</template>

<script>
export default {
  name: 'SelfFetchAddress',

  data() {
    return {
      pageTitle: '更换提货地址',
      // 是否展示提货地址弹层
      showAddress: false,
      // 当前坐标经纬度
      currentPosition: {},
      // 通过当前坐标获取到的城市信息
      locateCityInfo: {},
      // 当前城市信息
      cityInfo: {}
    };
  },

  props: {
    // v-model 双向绑定， 决定是否展示
    value: {
      type: Boolean,
      default: false
    },
    // 弹层展示位置
    position: {
      type: String,
      default: 'right'
    }
  },

  computed: {
    cityName() {
      return this.cityInfo.cityName;
    }
  },

  watch: {
    value(val) {
      this.showAddress = val;
    },
    showAddress(val) {
      this.$emit('input', val);
    }
  }
};
</script>

<style>
.selffetch-address__container {

  .van-popup {
    width: 100%;
    height: 100%;
  }
}
</style>`

**Comment by kobestyle** [comment] 2017-06-30 01:41
```
<template>
  <div class="selffetch-address__container">
    <div>for test</div>
  </div>
</template>

<script>
export default {
  name: 'SelfFetchAddress',

  data() {
    return {
      pageTitle: '更换提货地址',
      // 是否展示提货地址弹层
      showAddress: false,
      // 当前坐标经纬度
      currentPosition: {},
      // 通过当前坐标获取到的城市信息
      locateCityInfo: {},
      // 当前城市信息
      cityInfo: {}
    };
  },

  props: {
    // v-model 双向绑定， 决定是否展示
    value: {
      type: Boolean,
      default: false
    },
    // 弹层展示位置
    position: {
      type: String,
      default: 'right'
    }
  },

  computed: {
    cityName() {
      return this.cityInfo.cityName;
    }
  },

  watch: {
    value(val) {
      this.showAddress = val;
    },
    showAddress(val) {
      this.$emit('input', val);
    }
  }
};
</script>

```

@octref ,  mine is similiar with topul's,  click _this.showAddress_  repro the bug.

**Comment by HerringtonDarkholme** [comment] 2017-06-30 02:11
TS bug issue https://github.com/Microsoft/TypeScript/issues/16815

**Comment by Moerj** [comment] 2017-07-12 06:53
[Uploading QQ20170712-144336.mp4.zip…]()
I have the same error

**Comment by HerringtonDarkholme** [comment] 2017-09-29 03:28
It should be fixed in newer TS.

**Closed by HerringtonDarkholme** 2017-09-29 03:28 UTC
Labels: upstream
