### ISSUE TITLE
Vetur keeps file lock on asar files

### ISSUE THREAD

**Issue by Stanzilla** [vuejs/vetur#1474] opened 2019-10-22 21:54 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Windows
- Vetur version: 0.22.5
- VS Code version: 1.39.2

## Problem
![image](https://user-images.githubusercontent.com/75278/67337357-2b454380-f527-11e9-8172-75bc0f7d1add.png)
Sometimes Vetur keeps a file lock on the output dir of my Vue CLI project 

## Reproducible Case

Hard to reproduce as it happens randomly

**Comment by octref** [comment] 2019-10-23 18:18
Not sure what's the issue. If you can find reproducible steps, feel free to reopen.

**Comment by niceue** [comment] 2019-10-31 12:49
+1

![image](https://user-images.githubusercontent.com/1498854/67948020-cde47d00-fc1f-11e9-830e-fe3c16e3da6c.png)

**Comment by octref** [comment] 2019-12-12 18:32
https://github.com/microsoft/vscode/issues/80146

@dbaumer Do you have any guess might be happening?

**Comment by ToMGitHubN** [comment] 2019-12-18 11:29
I faced the same problem.


### problem:
I am developing an electron app. This plugin locks the asar file and prevents electron from building.

### reason:
The vs code was created with electron and has been modified to read asar files for speed.
Some plug-ins may lock asar due to changes in the vs code specification.

I found a useful URL with the extension * .asar.
https://electronjs.org/docs/api/environment-variables#electron_no_asar


### Steps to reproduce the problem:
1. create vue project.
`npx vue create asar-problem`

2. add electron-builder
`cd asar-problem`
`npx vue add electron-builder`

3. Open project folder with vs code.And open the vue file with vs code.  

4. electron build  
(There are no asar files at this time. The build was successful.)
`npm run electron:build`


5. electron build
`npm run electron:build`

problem!

---

### info:
Platform: Windows
Vetur:0.22.6
VS Code version:1.41.0


Thank you for reading!

**Comment by ToMGitHubN** [comment] 2020-01-09 10:39
@octref Need more information?

**Comment by octref** [comment] 2020-02-18 18:07
After adopting V6 node-languageclient this should be fixed. You can track #1719.

**Closed** 2020-03-03 22:50 UTC
Labels: upstream
