### ISSUE TITLE
Collapse is not working inside <template></template>

### ISSUE THREAD

**Issue by eosca** [vuejs/vetur#2255] opened 2020-09-05 06:07 UTC
Issue Type: <b>Bug</b>

Collapse/expand blocks (ex.: code between \<div\>...\</div\>) is not working inside \<template\>...\</template\> section. The "triangle" icon only appears in the editor at the left side of the \<template\> tag. The "triangle" icon is missing at the other blocks inside \<template\>\</template\> section, and therefore you can not collapse/expand those blocks.

Extension version: 0.27.1
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-45-generic

**Comment by rchl** [comment] 2020-09-05 07:51
Duplicate of #2234

**Closed by rchl** 2020-09-05 07:51 UTC
