### ISSUE TITLE
No typescript function arg snippets?

### ISSUE THREAD

**Issue by garyo** [vuejs/vetur#1483] opened 2019-10-30 16:33 UTC
- [x ] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.6
- VS Code version: 1.39.2

## Problem

When completing a function call in typescript in a .vue file, the completion appears, but you don't get arg snippets to fill in.

## Reproducible Case
```

<template>
<h1>
  hi
</h1>
</template>

<script lang="ts">
import * as d3 from 'd3'
function fooFunction(alpha: string, beta: number) {
  return 123 + alpha + beta
}
function bar() {
  fooFunct|
}
</script>

<style lang="scss">
something {
    color: blue;
}
</style>
```
Place the cursor at the `|` mark, type 'i' to get completions, then TAB or Enter to complete. 
Notice you don't get parens or arg snippets.
Ideally it should show you `fooFunction(alpha, beta)`.

I checked the logs, and vetur is not returning `insertTextFormat=2` as it should when using snippets:
```
[Trace - 12:30:07 PM] Sending request 'completionItem/resolve - (40)'.
Params: {
    "label": "fooFunction",
    "insertTextFormat": 1,
    "kind": 3,
    "sortText": "01",
    "data": {
        "languageId": "typescript",
        "uri": "file:///c%3A/tmp/vls-lsp-problem/test.vue",
        "offset": 196
    }
}
[Trace - 12:30:07 PM] Received response 'completionItem/resolve - (40)' in 94ms.
Result: {
    "label": "fooFunction",
    "insertTextFormat": 1,
    "kind": 3,
    "sortText": "01",
    "detail": "function fooFunction(alpha: string, beta: number): string",
    "documentation": {
        "kind": "markdown",
        "value": ""
    }
}
```
The same issue shows up with Emacs `lsp-mode` and `eglot` clients.

**Comment by ktsn** [comment] 2019-10-31 02:57
Duplicate of #1410

**Closed by ktsn** 2019-10-31 02:57 UTC
