### ISSUE TITLE
Module has no default export / <script setup>

### ISSUE THREAD

**Issue by web2033** [vuejs/vetur#2637] opened 2021-01-12 09:25 UTC
```vue
<template>
  <section class="bg-gray-100">
    <Toggle />
    <ul>
      <li v-for="link in data" :key="link.href">
        {{ link.text }}
      </li>
    </ul>
  </section>
</template>

<script setup>
import data from '../data.json'
import Toggle from './components/Toggle.vue'
</script>
```
> Error - Module App.vue has no default export.

Vetur doesn't yet support `<script setup>`?

**Comment by yoyo930021** [comment] 2021-01-12 09:31
Duplicate of #2296

**Closed** 2021-01-12 09:31 UTC
Labels: duplicate
