### ISSUE TITLE
Add Support for Shorthand Paths

### ISSUE THREAD

**Issue by juliancruzsanchez** [vuejs/vetur#1411] opened 2019-09-01 20:43 UTC
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: v0.22.2
- VS Code version: 1.37.1

## Problem

No path following for paths formatted like: ```import * as Sample from "@/components/Sample.vue"```

**Comment by octref** [comment] 2019-09-05 21:05
Seems duplicate of #762.

**Closed by octref** 2019-09-05 21:05 UTC
