### ISSUE TITLE
When to support variable name syntax highlighting in <script setup> please?

### ISSUE THREAD

**Issue by microkof** [vuejs/vetur#2780] opened 2021-03-12 08:54 UTC
The version of vetur in my PC is 0.33.1. VS Code theme is Monokai.

Now vetur doesn't support syntax highlighting in <script setup>. For example:

![image](https://wx4.sinaimg.cn/mw1024/3e2cf89cly1goh7zgsi8kj20bi05daaa.jpg)

**Comment by microkof** [comment] 2021-03-12 09:02
And, since the variables is not needed to return, can you add a marker to the variable to indicate that it will be implicitly returned.

**Comment by yoyo930021** [comment] 2021-03-18 06:15
Duplicate of https://github.com/vuejs/vetur/issues/2296

**Closed** 2021-03-18 06:15 UTC
Labels: duplicate
