### ISSUE TITLE
Missing Props shows when using `v-bind=`

### ISSUE THREAD

**Issue by 125Dal** [vuejs/vetur#2240] opened 2020-09-04 10:11 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.27.1
- VS Code version: 1.48.2

## Problem

When I use `v-bind="state"` to give props to component, this will shows warn "misses props

![image](https://user-images.githubusercontent.com/37011352/92227908-fabd8c80-eee1-11ea-9fd8-876ba7beca81.png)

![image](https://user-images.githubusercontent.com/37011352/92227933-06a94e80-eee2-11ea-9ea1-936f59ee0158.png)

![image](https://user-images.githubusercontent.com/37011352/92228034-30627580-eee2-11ea-9e8c-3bd4c0d0875c.png)

## Reproducible Case

Install vetur that version is more over 0.27.0
Use v-bind syntax, `v-bind=`, to give props to components.

**Comment by yoyo930021** [comment] 2020-09-04 10:12
Duplicate of #2236

**Closed** 2020-09-04 10:12 UTC
Labels: duplicate
