### ISSUE TITLE
Downgrade in v0.37.2

### ISSUE THREAD

**Issue by Skriptach** [vuejs/vetur#3652] opened 2023-02-20 13:33 UTC
## Info

- Platform: Win 7 x64
- Vetur version: v0.37.2
- VS Code version: 1.70.3

## Problem

1. Autocomplete stop working
2. Alt + click on a component use in a template stop open that component in a new tab

If install 0.37.0 from vsix than works fine

**Comment by yoyo930021** [comment] 2023-02-21 07:14
Please provide a repro case.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by hxj9102** [comment] 2023-02-22 06:12
same problem

**Comment by hxj9102** [comment] 2023-02-22 06:14
same problem in vue2

**Comment by yoyo930021** [comment] 2023-02-23 05:30
Duplicate of #3657 and fix in v0.37.3

**Closed by yoyo930021** 2023-02-23 05:30 UTC
Labels: lsp:completion, no-repro-case
