### ISSUE TITLE
Missing auto-import behavior in Vue CLI generated JavaScript app

### ISSUE THREAD

**Issue by johnpapa** [vuejs/vetur#1380] opened 2019-08-09 18:06 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.21.1
- VS Code version: 1.37.0-insider

## Problem

auto-imports are not working

## Reproducible Case

Use VS Code Insiders 1.37.0 with Vetur extension

1. See this repo <https://github.com/johnpapa/vue-autoimport> generated from the Vue CLI
2. Open `App.vue`
3. Try entering the component `HelloWorld` in the `components` section. auto-import does not work
4. Try using the `logger.js` file's `log`function. Auto-import does not work.

**Comment by theguii** [comment] 2020-05-02 19:45
Any updates on this?

**Comment by octref** [comment] 2020-06-08 02:20
Duplicate of #684.

**Closed by octref** 2020-06-08 02:20 UTC
Labels: bug, integ:typescript
