### ISSUE TITLE
when i use optional prop with typescript, i get error。

### ISSUE THREAD

**Issue by fangyang921017** [vuejs/vetur#2335] opened 2020-09-27 08:52 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win10
- Vetur version: 0.28.0
- VS Code version: 1.49.2

## Problem
![image](https://user-images.githubusercontent.com/25050610/94360674-b89ef980-00e1-11eb-90ec-258dc8f319f1.png)

![image](https://user-images.githubusercontent.com/25050610/94360635-6958c900-00e1-11eb-8e54-c60551ea1c66.png)

![image](https://user-images.githubusercontent.com/25050610/94360645-7e355c80-00e1-11eb-873f-2ac64f56ee66.png)

No errors were reported when used in this way
![image](https://user-images.githubusercontent.com/25050610/94360652-88eff180-00e1-11eb-8215-29cae60e2cba.png)

**Comment by yoyo930021** [comment] 2020-09-27 09:19
Duplicate of #2314

**Closed** 2020-09-27 09:19 UTC
Labels: duplicate
