### ISSUE TITLE
In Vue and Typescript files, the composite string type prompt is invalid

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/vetur#2410] opened 2020-10-29 14:32 UTC
When I input a string, I can't see what kind of string there is
![image](https://user-images.githubusercontent.com/49724027/97587837-d04a0480-1a36-11eb-95d1-70f84f955bd9.png)

**Comment by yoyo930021** [comment] 2020-10-29 14:45
Duplicate of #2300 
It will fix it when Vetur next release.
The PR is merged.

**Closed** 2020-10-29 14:45 UTC
Labels: duplicate
