### ISSUE TITLE
Multiple component suggestion

### ISSUE THREAD

**Issue by onrc** [vuejs/vetur#1145] opened 2019-03-11 06:14 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.16.2
- VS Code version: 1.32.0

## Problem

Template completion provides multiple suggestion for components when using initial tag casing.

![Screenshot from 2019-03-11 09-10-23](https://user-images.githubusercontent.com/14337113/54103485-a8c7a380-43dd-11e9-9982-1c615c027691.png)

## Reproducible Case

Select initial tag casing. Import component and type `<`.

**Comment by octref** [comment] 2019-03-21 23:32
Does this happen after you restart?

**Comment by yoyo930021** [comment] 2020-09-12 12:44
Duplicate of #2053

**Comment by yoyo930021** [comment] 2020-09-12 12:45
Fixed e707368

**Closed** 2020-09-12 12:45 UTC
Labels: bug, template-interpolation
