### ISSUE TITLE
Syntax highlight for script tag content in .vue files disappeared when adding a template tag with v-slot:namedSlot

### ISSUE THREAD

**Issue by luxwarp** [vuejs/vetur#1368] opened 2019-07-25 21:04 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux Ubuntu 19.04
- Vetur version: 0.21.1
- VS Code version: 1.36.1

## Problem

Syntax highlight for script tag content in .vue files disappeared when adding a template tag with v-slot:namedSlot

## Reproducible Case

Create a single file component that has named slots. Import the component inside another component, reference it in template tags and insert template tags with v-slot:slotName attribute and the content of script tag looses its syntax highlight. See images.

![Imgur](https://i.imgur.com/1dyBuM2.png)
![Imgur](https://i.imgur.com/oMW6eDt.png)

**Comment by zcqno1** [comment] 2019-07-26 02:54
@luxwarp I just met the same problem as yours. Thanks for reminding me to check the `template` tag.
I had a `template` tag in the template, but without `v-slot` direct. Like what you do, comment it, and things go well.
So I guess it may be caused by the format of the `template` tag. After trying some format adjustment, I found it.

before(bad situation):
```html
<template
  >some code</template
>
```
after(good situation):
```html
<template
  >some code</template>
```

Yeah, it's exactly the `</template>`‘s `>` in a new line cause the problem.
If someone makes one of his `</template>`'s `>` in a new line, including the `.vue` file’s outer `template` tag, congratulation, he reproduces the case.
That's the problem.

**Comment by luxwarp** [comment] 2019-07-26 14:24
Very interesting! After som pokeing around in my codes i finally got it working by just change my code to this and make sure that eslint/prettier did not try to format the code, and it does not :).
So its both a "bug" for prettier in vue projects and maybe vetur also to not be able to handle prettiers wierd formatting :D 

```
<NoListItemsFound v-else>
    <template v-slot:title>
      No to-do's found
    </template>
    <template v-slot:subtitle>
      Create one now!
    </template>
  </NoListItemsFound>
```

**Comment by zcqno1** [comment] 2019-07-26 15:31
I just heard from one of my colleagues, prettier makes such formatting to get rid of the spaces on the two side of the content when vue complies the template. He thinks it's a 'bug' of vue. Funny 😃 
So prittier may act reasonable here.

**Comment by octref** [comment] 2019-08-07 17:10
Duplicate of #1211. I'm afraid there's no easy fix in TextMate grammar and you would have to wait for the upcoming semantic syntax highlighting in VS Code.

**Closed by octref** 2019-08-07 17:10 UTC
