### ISSUE TITLE
Declaring an array property breaks intellisense scoping for typescript and javascript

### ISSUE THREAD

**Issue by Nonary** [vuejs/vetur#1295] opened 2019-05-15 19:20 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.21.0
- VS Code version: 1.33.1

## Problem
When declaring a property in Vue, if you specify that the type is an Array, Vetur will no longer recognize your data class and provide no suggestions. On Typescript it will error out stating it does not exist

## Reproducible Case
Create any vue project and declare a property that has an Array type

  props: {
    test: Array
  }

**Comment by octref** [comment] 2019-05-15 23:02
Duplicate of #1242, upstream vuejs/vue#9935.

**Closed by octref** 2019-05-15 23:02 UTC
