### ISSUE TITLE
mixins error message

### ISSUE THREAD

**Issue by kouchao** [vuejs/vetur#1238] opened 2019-04-25 01:35 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.19.1
- VS Code version: 1.33.1

## Problem
I use `mixins`, `create` exist on `mixins`.
```
Property 'create' does not exist on type 'CombinedVueInstance<{ rules: { title: { required: boolean; message: string; trigger: string; }[]; content: { required: boolean; message: string; trigger: string; }[]; }; form: { title: string; content: string; }; } & { createApi: any; toLocal(data: any): void; toServe(): any; } & Record<...> & Vue, object, object, o...'.Vetur(2339)
```

## Reproducible Case

Use mixins.

**Comment by KevisLuo** [comment] 2019-04-25 02:37
Duplicate of #1232

**Closed** 2019-04-25 03:07 UTC
