### ISSUE TITLE
v-for directive is showing error

### ISSUE THREAD

**Issue by ip127001** [vuejs/vetur#726] opened 2018-03-11 13:56 UTC
It shows "Elements in iteration expect to have 'v-bind:key' directives". v-for directive is independent and also code is working but vetur is giving the above suggestion and red under-line.

**Comment by leopiccionia** [comment] 2018-03-11 16:26
It seems to be duplicate of #261.

Please notice that, even though ignoring it won't break your code, it's **strongly** recommended to use `:key` together with `v-for` (see [here](https://vuejs.org/v2/guide/list.html#key) and [here](https://vuejs.org/v2/style-guide/#Keyed-v-for-essential)).

**Closed** 2018-03-11 16:43 UTC

**Comment by ip127001** [comment] 2018-03-11 18:11
thank you.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality&>

**Comment by octref** [comment] 2018-03-13 16:29
@leopiccionia Thanks for helping out with the question!

**Comment by uri** [comment] 2019-04-22 21:34
@octref 

It seems that using `v-for` without a key is usable when iterating over a simple object/array that is not a component.

>It is recommended to provide a key with v-for whenever possible, **unless the iterated DOM content is simple, or you are intentionally relying on the default behavior for performance gains.**

and 

>key with v-for is always required **on components**...

------

I'm essentially doing something like:

```javascript
this.errors = ['something went wrong']
```

```html
<li v-for="error in errors">{{error}}</li>
```

But vetur pushes me to do something like:

```html
<li v-for="(error,index) in errors" :key="index">{{error}}</li>
```

Which according to the docs (but maybe not in practice?) is unnecessary.

**Comment by octref** [comment] 2019-04-26 04:05
@uri You can disable that rule by either `vetur.validation.template` false, or disabling it through `eslint-plugin-vue` setting: https://github.com/vuejs/eslint-plugin-vue.

**Comment by octref** [comment] 2019-04-26 04:05
Cool username btw

**Comment by AmineAch** [comment] 2020-03-03 19:59
Thank s bro
