### ISSUE TITLE
Cannot find name XXX when using TypeScript component with complex prop type

### ISSUE THREAD

**Issue by KodrAus** [vuejs/vetur#2826] opened 2021-03-30 03:40 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10
- Vetur version: `vti 0.1.1`
- VS Code version: N/A

## Problem

The code emitted behind `vetur` will reference the types of complex properties without importing them first. I'm not sure if this is really a `vetur` issue or something upstream.

For example, if we have a `complex.ts`:

```typescript
export interface Complex {
    value: string
}
```

A `WithComplexProps.vue`:

```vue
<template>
  <div>
    {{ data.value }}
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import { PropType } from 'vue'

import { Complex } from './complex'

export default Vue.extend({
  props: {
      data: {
          type: Object as PropType<Complex>,
          required: true
      }
  }
})
</script>
```

A `Test.vue`:

```vue
<template>
  <div>
    <with-complex-props :data="complex" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

import WithComplexProps from './WithComplexProps.vue'

export default Vue.extend({
  components: {
    WithComplexProps
  },
  data () {
    return {
      complex: {
        value: 'hello'
      }
    }
  }
})
</script>
```

Then `Test.vue` will produce the following virtual file:

```
====================
Virtual content of path\Test.vue.template
Hover, semantic diagnostics, jump to definition and find references are run on this file.
====================

import __vlsComponent from "./Test.vue";
import { __vlsRenderHelper, __vlsComponentHelper, __vlsIterationHelper, __vlsComponentData } from "vue-editor-bridge";
__vlsRenderHelper(__vlsComponent, function () { __vlsComponentHelper(this, "div", { props: {}, on: {}, directives: [] }, [__vlsComponentHelper__with_complex_props(this, "with-complex-props", { props: { "data": this.complex }, on: {}, directives: [] }, [])]); });

interface __vlsComponentData__with_complex_props<T> extends __vlsComponentData<T> {
  props: { data: Complex, [other: string]: any }
  on: {  } & { [K in keyof T]?: ($event: T[K]) => any; }
}
declare const __vlsComponentHelper__with_complex_props: {
  <T>(
    vm: T,
    tag: string,
    data: __vlsComponentData__with_complex_props<Record<string, any>> & ThisType<T>,
    children: any[]
  ): any
}

====================
SourceMap
from: path\src\Test.vue
to  : path\src\Test.vue.template
[VueFileStart, VueFileEnd, VueFileText] => [TSVirtualFileStart, TSVirtualFileEnd, TSVirtualFileText]
====================

[15, 18, div] => [246, 251, props]
[26, 44, with-complex-props] => [355, 360, props]
[46, 50, data] => [364, 370, "data"]
[52, 59, complex] => [372, 384, this.complex]
```

with this problematic snippet:

```typescript
interface __vlsComponentData__with_complex_props<T> extends __vlsComponentData<T> {
  props: { data: Complex, [other: string]: any }
  on: {  } & { [K in keyof T]?: ($event: T[K]) => any; }
}
```

that produces this output from `vti`:

```
====================================
Getting Vetur diagnostics
Loading Vetur in current directory: path\veturpack
Vetur initialized
====================================

Getting diagnostics from:  [ 'src/Test.vue', 'src/WithComplexProps.vue' ]

[INFO ] Find node_modules paths in path - 148ms
[INFO ] Loaded bundled typescript@4.2.3.
[INFO ] Loaded bundled prettier.
[INFO ] Loaded bundled @starptech/prettyhtml.
[INFO ] Loaded bundled prettier-eslint.
[INFO ] Loaded bundled prettier-tslint.
[INFO ] Loaded bundled stylus-supremacy.
[INFO ] Loaded bundled @prettier/plugin-pug.
File : fpath\Test.vue:1:1
Error: Cannot find name 'Complex'.
> 1 | <template>
    | ^
  2 |   <div>
  3 |     <with-complex-props :data="complex" />
  4 |   </div>

====================================
VTI found 1 error
```

## Reproducible Case

https://github.com/KodrAus/vti-repro

**Comment by KodrAus** [comment] 2021-03-30 04:10
This actually appears to be a dupe of: #2668

**Comment by yoyo930021** [comment] 2021-04-07 11:51
Duplicate of #2668

**Closed** 2021-04-07 11:52 UTC
Labels: duplicate
