### ISSUE TITLE
interpolation got wrong error message

### ISSUE THREAD

**Issue by Killea** [vuejs/vetur#2251] opened 2020-09-04 19:55 UTC
- [. ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

Linux

## Reproducible Case

If you use sync modifier, the prop was counted a missing prop.
![image](https://user-images.githubusercontent.com/5551824/92280176-dbfdcc80-eec6-11ea-8871-b0587b756163.png)

**Comment by rchl** [comment] 2020-09-04 20:08
Duplicate of #2237

**Closed by rchl** 2020-09-04 20:08 UTC
