### ISSUE TITLE
Remove barely used dom API out of IntelliSense

### ISSUE THREAD

**Issue by csicky** [vuejs/vetur#110] opened 2017-03-27 16:40 UTC
When I comment something in a .vue file and I type `//` I get instead `/AAGUID/`. It happens only sometimes, not always.
It appeared only after I switched to Vetur. 
I also use extensions Eslint, Editorconfig for VS Code, Reactjs code snippets, React Native Tools.
Thank you.

**Comment by octref** [comment] 2017-03-28 18:57
Interesting, I haven't seen this before. Which part (template, style, js, or outside any region) are you writing it?

I can't debug it if I can't reproduce it.

**Comment by csicky** [comment] 2017-03-28 22:01
I made a video and from it I made a gif. I don't know what to send for you to be able to reproduce it. It's not big deal, but if you want I can send you any config files from VS Code just for your curiosity.
What is strange is that it appears like it is coming from somewhere, it's not random. Even if I type `aa` it appears in IntelliSense.
Like I said, I can live with it. I just thought to report it because I was here researching about the other issue where on each format the HTML in the vue file is indented.

Best regards,
Rudolf

![aaguid](https://cloud.githubusercontent.com/assets/3931907/24429237/dd5669ce-1419-11e7-9944-8efeec718bff.gif)

**Comment by octref** [comment] 2017-03-29 03:22
Yea the current IntelliSense have a lot of junks in it (outputting everything and let you filter it down).
A lot of the suggestions don't make sense in the context at all.
I'll have time to improve IntelliSense next week, and I'll remember to look into this.

**Comment by aprilandjan** [comment] 2017-04-05 09:33
When I use `switch` syntax in vue files, after typing a case colon, the suggested string `AAGUID` came out. I had to press ESC to cancel suggestions and then ENTER to switch to a new line.

**Comment by octref** [comment] 2017-04-25 04:14
AAGUID is part of TS's DOM api: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts

So while it's not commonly used, we can't blame TS for having it in IntelliSense.

What you were describing sounds like a VSCode issue with its IntelliSense. Can you try the latest version and see if it's resolved already?

**Comment by csicky** [comment] 2017-04-25 08:24
Still happening and is starting to get in the way of normal work. I am always stopped by it and must press esc to get rid of it.
Why are not more people complaining about this?
Reported to VS Code too. https://github.com/Microsoft/vscode/issues/25275

**Comment by octref** [comment] 2017-04-25 15:20
Try removing `vue-snippets`.

**Comment by csicky** [comment] 2017-04-25 22:38
I disabled Vetur. Installed back Vue snippets. `AAGUID` is not appearing anymore. Even if I type `AA` I don't get it. Seems like Vetur is bringing some IntelliSense into scope which should not be there. Too bad because I really like that Vetur indents my code on save, a feature I find very important.

**Comment by KagamiChan** [comment] 2017-05-25 07:25
I hit something similar: when typing`:` in a `case` syntax, most times I just want to add a line break, but if I press Enter, AAGUID will come out

![image](https://cloud.githubusercontent.com/assets/3816900/26440189/bce7149c-415d-11e7-8b90-53c264599bf4.png)

**Comment by octref** [comment] 2017-06-06 14:24
The repeating IntelliSense is an upstream bug and will be resolved with LS@3.3.0 released later this week.

**Comment by csicky** [comment] 2017-06-13 11:57
Any news on our friend `AAGUID`?
I just typed this because I forgot to press ESC after each equal sign:

`=AAGUID=AAGUID=` 

I wanted `===`

**Comment by octref** [comment] 2017-06-19 20:33
I can type `===` without any problem. I think you should raise a problem with VSCode again, since `=` shouldn't trigger IntelliSense.

Meanwhile on Vetur side, the repeating IntelliSense suggestion has been fixed.

**Closed** 2017-08-05 08:12 UTC
Labels: bug, IntelliSense
