### ISSUE TITLE
Cannot find name template

### ISSUE THREAD

**Issue by lzl124631x** [vuejs/vetur#1491] opened 2019-11-07 07:27 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version: 1.39.2

## Problem

![image](https://user-images.githubusercontent.com/5824517/68368376-ca079d80-00ec-11ea-9a1b-8ff58d809d2e.png)

## Reproducible Case

Not sure. This issue just came to me around a month ago. I don't remember I did anything special.

This used to be working.

I have the following settings in my user settings.json

```json
    "files.associations": {
        "*.vue": "vue",
        "*.wpy": "vue",
        "*.wxs": "javascript"
    },
```

**Comment by lzl124631x** [comment] 2019-11-07 07:29
Reverting to 0.21.1 works. Some broken change were introduced :(

**Comment by lzl124631x** [comment] 2019-11-07 07:31
0.22.4 works but 0.22.5 doesn't!

![image](https://user-images.githubusercontent.com/5824517/68368762-937e5280-00ed-11ea-9673-c83a2c664dc2.png)

![image](https://user-images.githubusercontent.com/5824517/68368715-7ba6ce80-00ed-11ea-87c6-e1691f289ed1.png)

**Comment by ktsn** [comment] 2019-11-07 13:50
Duplicate of #1451 and #1388

**Closed by ktsn** 2019-11-07 13:50 UTC

**Comment by lzl124631x** [comment] 2021-03-04 17:15
@ktsn  I don't think this is a dup of the other two issues. This file is not in `node_modules` and trying the solutions in 1388 doesn't help.

**Comment by manasux** [comment] 2021-07-28 14:03
Uninstall Vetur extension in vscode, then it will not come. It happens, because Vetur is not able to configure properly, and usually at starting the warning comes from vetur that `tsconfig.json` is not configured.
