### ISSUE TITLE
Find All References called from defining module does not find usage of a function

### ISSUE THREAD

**Issue by deisner** [vuejs/vetur#2944] opened 2021-05-18 01:00 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.33.1
- VS Code version: 1.56.2

## Problem

I have a `utils.js` file with an exported function. I use that function in a `.vue` component (e.g. `Test.vue`). When I right-click on the usage of the function and use **Find All References**, I see the references to the function in the `Test.vue` file, and in the defining `utils.js` file:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/742277/118574173-e3fa5580-b751-11eb-879f-8a12c9c24854.png">
 So far so good.

However, if I right-click on the definition of the exported function in `utils.js` and use Find All References, It only shows me the definition, not the usage in the `.vue` component:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/742277/118574281-173ce480-b752-11eb-98ed-e8b2d70aba86.png">

It seems like it should be showing me the usages, not just the definition. Am I missing something?

## Reproducible Case

Here's my demonstration of the problem, forked from `veturpack`: https://github.com/deisner/find-all-references-example/commit/f25db000575437f83d642fc45e1f01ef1f29feec

(An extension I'm using -- Window Colors -- made a few additions to `.vscode/settings.json`, which are included for completeness.)

**Comment by yoyo930021** [comment] 2021-06-02 02:45
https://github.com/vuejs/vetur/issues/707#issuecomment-762595189

**Comment by yoyo930021** [comment] 2021-06-02 02:58
Duplicate of https://github.com/vuejs/vetur/issues/2358

**Closed** 2021-06-02 02:59 UTC
Labels: duplicate
