### ISSUE TITLE
vetur0.22.5 snippet for js is not work

### ISSUE THREAD

**Issue by zhuman1993** [vuejs/vetur#1475] opened 2019-10-23 04:25 UTC
when i upload vetur to 0.22.5 version, the snippet for js is not work, and then i installed the 0.22.4 version, it work again.

please finish the issue

**Comment by peidLuo** [comment] 2019-10-23 06:16
me too, omg,... (ᵒ̤̑ ₀̑ ᵒ̤̑)

**Comment by steelcg** [comment] 2019-10-23 06:46
me too

**Comment by ah597568204** [comment] 2019-10-23 06:56
same issues already change version to 0.22.5 version to 0.22.4

**Comment by croson** [comment] 2019-10-23 09:17
me too

**Comment by Rizzato95** [comment] 2019-10-23 09:39
Me too

**Comment by JHanL** [comment] 2019-10-23 09:40
me too

**Comment by BearAndDoggy** [comment] 2019-10-23 13:33
me too

**Comment by nik9play** [comment] 2019-10-23 15:01
me too

**Comment by zangxx66** [comment] 2019-10-23 15:55
me too

**Comment by octref** [comment] 2019-10-23 19:59
Duplicate of #1476. Fixed by #1472 and released in 0.22.6.

**Closed by octref** 2019-10-23 19:59 UTC
