### ISSUE TITLE
Show ESLint errors on disabled rules

### ISSUE THREAD

**Issue by haiarha** [vuejs/vetur#2118] opened 2020-08-06 11:55 UTC
Issue Type: <b>Bug</b>

Show eslint-plugin-vue error for the rule `vue/valid-v-slot`, when it is disabled ("vue/valid-v-slot": "off"):

```html
      <template v-slot:item.rating="{ item }">
        <RatingStars :rating="item.rating" />
      </template>

<!--
On v-slot hover:

[vue/valid-v-slot]
An element cannot have multiple '<template>' elements which are distributed to the same slot.eslint-plugin-vue
[vue/valid-v-slot]
'v-slot' directive doesn't support any modifier.eslint-plugin-vue
-->
```

In case of turned on ("vue/valid-v-slot": "error") rule errors **doubling**!!!
```html
      <template v-slot:item.rating="{ item }">
        <RatingStars :rating="item.rating" />
      </template>

<!--
On v-slot hover:

[vue/valid-v-slot]
An element cannot have multiple '<template>' elements which are distributed to the same slot.eslint-plugin-vue
[vue/valid-v-slot]
'v-slot' directive doesn't support any modifier.eslint-plugin-vue
An element cannot have multiple '<template>' elements which are distributed to the same slot.eslint(vue/valid-v-slot)
'v-slot' directive doesn't support any modifier.eslint(vue/valid-v-slot)
-->
```

Extension version: 0.26.0
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yoyo930021** [comment] 2020-08-06 11:58
Duplicate of #2113.

**Comment by yoyo930021** [comment] 2020-08-06 11:59
Duplicate of #2113.

**Closed** 2020-08-06 12:00 UTC
