### ISSUE TITLE
vscode updata 1.19, Plug-in error

### ISSUE THREAD

**Issue by SunOfHomeBoy** [vuejs/vetur#580] opened 2017-12-15 01:10 UTC
- [done ] I have searched through existing issues
- [done ] I have read through [docs](https://vuejs.github.io/vetur)
- [done] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.11.4
- VS Code version: 1.19.0
版本 1.19.0
提交 816be6780ca8bd0ab80314e11478c48c70d09383
日期 2017-12-14T12:06:43.492Z
Shell 1.7.9
渲染器 58.0.3029.110
Node 7.9.0
架构 x64

## Problem
**vscode version,updating plug-in vetur error!**

"vetur initialized"

my email:15030098661@163.com/sc903317164@gmail.com

![image](https://user-images.githubusercontent.com/30047595/34021931-57bb01e0-e177-11e7-9901-9911e33baeea.png)

**Comment by ysk8** [comment] 2017-12-15 02:18
I just updated to the same versions of **Vetur** and **VS Code** and start to get highlighted some part of my code with this:

**`[vue-language-server] Require self-closing on Vue.js custom components (<v-text-field>).`**

**`<v-text-field>`** is an tag used in **Vuetify**, and before the update everything was ok

**`[vue-language-server] '<template>' should have end tag.`**

<img width="493" alt="screen shot 2017-12-14 at 21 12 48" src="https://user-images.githubusercontent.com/4340660/34023571-a1584006-e113-11e7-85d5-82bceca0ab0e.png">

**Comment by huoteng** [comment] 2017-12-15 02:21
![image](https://user-images.githubusercontent.com/9995379/34023737-79212a76-e181-11e7-9d00-c9f708a9967d.png)

The same as the above, after updating VS Code to 1.19.0, I got thus errors.

**Comment by mrmengjun** [comment] 2017-12-15 02:25
same error too.

**Comment by mrmengjun** [comment] 2017-12-15 02:29
@ysk8 you can set the config to except the template valide: vetur.validation.template: false.

**Comment by SunOfHomeBoy** [comment] 2017-12-15 02:43
@ysk8 me too

**Comment by SunOfHomeBoy** [comment] 2017-12-15 02:44
@mrmengjun How to operate it？

**Comment by ysk8** [comment] 2017-12-15 02:47
but @mrmengjun doing that, maybe the issue is related to the **`eslint-plugin-vue`** the highlighted disappears

**Comment by ysk8** [comment] 2017-12-15 02:52
@SunOfHomeBoy if you are in macOS can activate User Settings with **`cmd + ,`** maybe for WIN **`ctrl + ,`** regulary. Then search for **`vetur.validation.template`** and edit it.

**Comment by SunOfHomeBoy** [comment] 2017-12-15 05:44
@ReZhangxin please speak english :p

**Comment by CarmineZhang** [comment] 2017-12-15 05:47
same error .
why?

**Comment by vsona** [comment] 2017-12-15 05:50
same error

**Comment by ckaiCp** [comment] 2017-12-15 05:51
same error too. so disappointed about 0.11.4 changelog

**Comment by NickeyLin** [comment] 2017-12-15 06:08
@ysk8 same too.  😞

**Comment by wzc0x0** [comment] 2017-12-15 06:25
me too

**Comment by ainialan6** [comment] 2017-12-15 07:41
so how to solve

**Comment by yoyo837** [comment] 2017-12-15 08:18
same error .

**Comment by octref** [comment] 2017-12-15 08:23
> `<template>` should have end tag.


This is a bug that has been fixed.



> [vue-language-server] Require self-closing on Vue.js custom components (<v-text-field>).

This is `html-self-closing` rule from `eslint-plugin-vue`: https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-self-closing.md

In 0.11.4, I used the [`recommended`](https://github.com/vuejs/eslint-plugin-vue#priority-c-recommended-minimizing-arbitrary-choices-and-cognitive-overhead) set from `eslint-plugin-vue`. And it seems it's too strict. I've changed that to [`essential`](https://github.com/vuejs/eslint-plugin-vue#priority-a-essential-error-prevention).

After upgrading to 0.11.5, you can
- Leave `vetur.validate.template` on, which uses the `essential` rule set from `eslint-plugin-vue` to lint template
- Configure `.eslintrc` to use your own rule set, see: https://vuejs.github.io/vetur/linting-error.html

**Closed by octref** 2017-12-15 08:23 UTC

**Comment by corala** [comment] 2017-12-15 08:30
vue报错但能正常运行，怎么解决啊

**Comment by yoyo837** [comment] 2017-12-15 08:31
@corala Update extension 0.11.5, the latest

**Comment by ckaiCp** [comment] 2017-12-15 08:33
@corala use sublime  like to change boy  friend;hahahhaha

**Comment by yoyo837** [comment] 2017-12-15 09:04
@octref 
>Leave **_vetur.validate.template_** on, which uses the essential rule set from eslint-plugin-vue to lint template

typo:  vetur.validation.template

**Comment by NickeyLin** [comment] 2017-12-15 09:20
after update 0.11.5, the <template> formatting not work.
