### ISSUE TITLE
Template interpolation incorrect type on event (Typescript)

### ISSUE THREAD

**Issue by SuspiciousLookingOwl** [vuejs/vetur#2504] opened 2020-11-29 23:38 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows
- Vetur version: 0.30.3
- VS Code version: 1.51.1

## Problem

Vetur is reporting false error with `"vetur.experimental.templateInterpolationService": true` due to inccorect typing when passing a variable from an event, example:

```vue
  <!-- foo is computed property with return type number | undefined -->

  <div v-if="foo">
    <!-- foo now should be number  -->
    {{ foo }} <!-- Correct type (number) -->
    <input :example="foo" /> <!-- Also correct type (number) -->
    <input type="text" @input="bar(foo)" /> <!-- Incorrect type (number | undefined) -->
  </div>
```
![image](https://user-images.githubusercontent.com/32597776/100556566-ce918c00-32d5-11eb-9317-2fbda09b0705.png)

## Reproducible Case
```vue
<template>
  <div v-if="foo">
    <!-- foo now should only be number  -->
    {{ foo }} <!-- Correct type (number) -->
    <input :example="foo" /> <!-- Also correct type (number) -->
    <input type="text" @input="bar(foo)" /> <!-- Incorrect type (number|undefined) -->
  </div>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";

@Component
export default class Test extends Vue {
  get foo(): number | undefined {
    return 1;
  }

  bar(x: number) {
    return x * 2;
  }
}
</script>
```

**Comment by rchl** [comment] 2020-11-30 09:11
This is the correct behavior.

The handler of the `input` event will be evaluated on entering the text in the input. That can happen at arbitrary times. So the value can be undefined at that point.

**Comment by SuspiciousLookingOwl** [comment] 2020-11-30 09:31
So the `@input` can be triggered even though it's not rendered because of the `v-if="foo"`?

**Comment by yoyo930021** [comment] 2020-11-30 09:38
> So the `@input` can be triggered even though it's not rendered because of the `v-if="foo"`?

https://www.typescriptlang.org/play?#code/DYUwLgBAZg9jBcEB2BXAtgIxAJwgH2RWGAgF4IBGAKCoGMYkBnSetABzIgAoBKMgPggBvKhAgBLKN1gw+IsWJkA6AG4BDYChAB5KLxoKI9Ji2DjaAa068B0OKo1bd+sQF8q7qjM6piQA

**Comment by rchl** [comment] 2020-11-30 09:49
Good point I guess. It should theoretically not be possible to trigger the event handler if `foo` is undefined. But this relation might be too complex for a tool like Vetur (or Typescript) to understand.

**Comment by SuspiciousLookingOwl** [comment] 2020-11-30 09:49
> > So the `@input` can be triggered even though it's not rendered because of the `v-if="foo"`?
> 
> https://www.typescriptlang.org/play?#code/DYUwLgBAZg9jBcEB2BXAtgIxAJwgH2RWGAgF4IBGAKCoGMYkBnSetABzIgAoBKMgPggBvKhAgBLKN1gw+IsWJkA6AG4BDYChAB5KLxoKI9Ji2DjaAa068B0OKo1bd+sQF8q7qjM6piQA

That's true for Typescript, but does Vue work the same?

Since I put `<div v-if="foo">` so technically `foo` inside that `div` is not `undefined`, therefore the `foo` in `@input="bar(foo)"` is supposed to be not `undefined`. Unless it's possible for Vue to trigger the `@input` even though the component is not rendered because of the `<div v-if="foo">` when the `foo` is `undefined`, which seems to be what you are trying to say.

**Comment by yoyo930021** [comment] 2020-11-30 11:21
@ktsn what do you think about this?

**Comment by ktsn** [comment] 2020-11-30 12:38
#1212

I've been thinking of this problem and there seem to be two approaches:

1. Change template transformer implementation to like what Angular does (use `if` statement and user defined type guard to generate context, in this case `$event`, instead of using helper function and callback) so that we can eliminate callbacks from transformed code.

https://medium.com/angular-in-depth/type-checking-templates-in-angular-viewengine-and-ivy-77f8536359f5

2. Assign all values in if condition into local variables so that we avoid type widening.

```ts
if (vm.foo.bar.baz) {
  const __foo = vm.foo
  const __foo_bar = vm.foo.bar
  const __foo_bar_baz = vm.foo.bar.baz

  {
    on: {
      input: $event => func(__foo_bar_baz)
    }
  }
}
```

The latter approach should be easier than the former but I'm not sure if it actually works properly. There might be some edge cases that I'm not aware of.

**Comment by yoyo930021** [comment] 2020-11-30 13:15
> #1212
> 
> I've been thinking of this problem and there seem to be two approaches:
> 
> 1. Change template transformer implementation to like what Angular does (use `if` statement and user defined type guard to generate context, in this case `$event`, instead of using helper function and callback) so that we can eliminate callbacks from transformed code.
> 
> https://medium.com/angular-in-depth/type-checking-templates-in-angular-viewengine-and-ivy-77f8536359f5
> 
> 1. Assign all values in if condition into local variables so that we avoid type widening.
> 
> ```ts
> if (vm.foo.bar.baz) {
>   const __foo = vm.foo
>   const __foo_bar = vm.foo.bar
>   const __foo_bar_baz = vm.foo.bar.baz
> 
>   {
>     on: {
>       input: $event => func(__foo_bar_baz)
>     }
>   }
> }
> ```
> 
> The latter approach should be easier than the former but I'm not sure if it actually works properly. There might be some edge cases that I'm not aware of.

I think we can choose the latter one.
Just adjust as necessary.

**Comment by yoyo930021** [comment] 2020-11-30 13:15
I will close this issue.
Please follow #1212

**Comment by yoyo930021** [comment] 2020-11-30 13:16
Duplicate of #1212

**Closed** 2020-11-30 13:16 UTC
Labels: duplicate
