### ISSUE TITLE
me too,Ctrl+K,Ctrl+F doesnot work, it has been resolved??

### ISSUE THREAD

**Issue by songfs** [vuejs/vetur#2408] opened 2020-10-28 02:26 UTC
me too,Ctrl+K,Ctrl+F doesnot work, it has been resolved??

_Originally posted by @Gavin110 in https://github.com/vuejs/vetur/issues/622#issuecomment-357124113_

**Comment by yoyo930021** [comment] 2020-10-28 02:40
Duplicate of #2388 

At this point we can't confirm if it's a vscode upstream issue.

**Closed** 2020-10-28 02:40 UTC
Labels: duplicate
