### ISSUE TITLE
Intellisense (Go to Definition/Peek) of methods doesn't work if I have computed property within same .vue file

### ISSUE THREAD

**Issue by bahung1221** [vuejs/vetur#2425] opened 2020-11-02 06:35 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.19 -> 0.28.0 (I tried to downgrade through a lot of vetur versions but it still doesn't work)
- VS Code version: 1.49 -> 1.50 (latest)

## Problem
I can't call `go to definition` or `peek definition` of all methods when **I have any computed property** that was declared in the same vue instance, both call from `script` and `template` just showed "No definition found for...".
If I remove `computed`, It will work fine!

<img width="1382" alt="Screen Shot 2020-11-02 at 13 25 19" src="https://user-images.githubusercontent.com/27690861/97836550-22c54280-1d0f-11eb-9265-64bd1953b507.png">

I also tried to removed **all extensions** and then reinstall both vscode and vetur but no luck.
You can check the reproduce repository below that I successfully reproduced.

## Reproducible Case
Just install vscode and install only vetur and then try to create a method and a computed property **that use `this` instance** inside .vue file.

Reproduce commit:
https://github.com/bahung1221/reproduce-vetur-intellisense/commit/088fef34b99c72dc20672e2c833f3ce5c66d9781

Thank you so much!

**Comment by octref** [comment] 2020-11-02 10:36
Duplicate of #1707, see:
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#property-xxx-does-not-exist-on-type-combinedvueinstance
https://github.com/vuejs/vetur/issues/1707#issuecomment-686851677

**Closed by octref** 2020-11-02 10:37 UTC

**Comment by bahung1221** [comment] 2020-11-02 11:30
Thanks for your respond, it worked now 😄 

For those who don't use vue with typescript, just add typescript < v3.4 to your project devDependencies:
```
yarn add -D typescript@3.2.4
```
Then add `"vetur.useWorkspaceDependencies": true,` to your vscode setting.
