### ISSUE TITLE
Cannot find name 'scope'.

### ISSUE THREAD

**Issue by SssLiao** [vuejs/vetur#1247] opened 2019-04-25 08:48 UTC
## Info

- Platform: Win
- Vetur version:0.91.1
- VS Code version:1.33.1

## Problem

```
<template slot-scope="scope"></template>
```

Using the above code in elementui will cause errors

Cannot find name 'scope'.Vetur(2304)

**Comment by zhouxinyong** [comment] 2019-04-25 09:16
the same issue +1

**Comment by DWYW** [comment] 2019-04-25 09:35
the same issue +1
hope it can be fixed as soon as possible.

**Comment by ktsn** [comment] 2019-04-25 09:43
Duplicate of #1203

**Closed by ktsn** 2019-04-25 09:43 UTC
