### ISSUE TITLE
Gridsome's Pager autocompletion is not working

### ISSUE THREAD

**Issue by tyankatsu0105** [vuejs/vetur#1160] opened 2019-03-21 01:36 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  macOS
- Vetur version: 0.17.0
- VS Code version:1.32.3

## Problem

I added gridsome-helper-json for Vetur.
https://github.com/gridsome/gridsome-helper-json/blob/master/gridsome-tags.json

`g-link` and `g-image` autocompletion is success.
But `Pager` autocompletion is not working.
Do you know anything about it?

<img width="559" alt="スクリーンショット 2019-03-21 10 32 44" src="https://user-images.githubusercontent.com/28397593/54729062-b0006580-4bc4-11e9-9244-3d92a3f2c7aa.png">

## Reproducible Case

Add tag `<Pager>` in `.vue`

**Comment by octref** [comment] 2019-03-21 23:51
Seems to be a bug for the HTML completion part.

**Comment by octref** [comment] 2020-08-04 03:41
Duplicate of #2049, fixed by #2056.

**Closed by octref** 2020-08-04 03:41 UTC
Labels: bug, component-data, lsp:completion
