### ISSUE TITLE
Go to Symbol In Editor no longer shows methods, computed, etc

### ISSUE THREAD

**Issue by asethwright** [vuejs/vetur#2058] opened 2020-07-24 15:10 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Mac
- Vetur version: 0.25.0
- VS Code version: 1.47.2

## Problem

I'm no longer getting symbols matched for what's inside the <script> section of my template. Only HTML symbols. I cannot jump quickly to a function definition.

## Reproducible Case

Install 0.25.0
Open a vue file
Go -> Go to Symbol In Editor
Type the name of a method
Only HTML tags matched

Downgrade 0.24.0
Open a vue file
Go -> Go to Symbol In Editor
Type the name of a method
Works

**Comment by jahhernandez** [comment] 2020-07-25 12:51
Can confirm it also happens on Windows & Linux, tried upgrading prettier to version 2.0.5 but the problem continues had to downgrade for now.

**Comment by IWANABETHATGUY** [comment] 2020-07-27 09:50
i think this is an upstream bug, releated to https://github.com/vuejs/vetur/issues/1849

**Comment by IWANABETHATGUY** [comment] 2020-07-27 10:06
this would fixed in `typescript 4.0` ,we could use `typescript@next` fix this bug, https://github.com/microsoft/vscode/issues/101570

**Comment by yoyo930021** [comment] 2020-07-27 13:03
@IWANABETHATGUY thanks.
I will close this issue when we upgrade TypeScript version.

**Comment by rathboma** [comment] 2020-07-29 15:18
I have the same issue in Vetur 0.25, downgrading to 0.24 works as expected.

Not only using 'goto', but right-click go-to-definition is broken too.

**Comment by XrayBravoGolf** [comment] 2020-08-04 06:58
> this would fixed in `typescript 4.0` ,we could use `typescript@next` fix this bug, [microsoft/vscode#101570](https://github.com/microsoft/vscode/issues/101570)

The `typescript@next` extenstion would have an effect and take the (now 4.0.0) dev version applying to JavaScript and TypeScript files. 
However, the `TypeScript: Select TypeScript Version` command, as referenced in the `typescript@next` plugin instructions, would be _missing from the Command Palette_ when editing a .vue file and thus VSCode identifies it as Vue.
I am not able to confirm it's utilizing the nightly TypeScript, and I do not see items declared within export default appearing in the outline view or the breadcrumb. (not in the navtree)

Let me know if I should put in its own separate issue, or I shall provide more info, or both.

**Comment by yoyo930021** [comment] 2020-08-04 07:03
> > this would fixed in `typescript 4.0` ,we could use `typescript@next` fix this bug, [microsoft/vscode#101570](https://github.com/microsoft/vscode/issues/101570)
> 
> The `typescript@next` extenstion would have an effect and take the (now 4.0.0) dev version applying to JavaScript and TypeScript files.
> However, the `TypeScript: Select TypeScript Version` command, as referenced in the `typescript@next` plugin instructions, would be _missing from the Command Palette_ when editing a .vue file and thus VSCode identifies it as Vue.
> I am not able to confirm it's utilizing the nightly TypeScript, and I do not see items declared within export default appearing in the outline view or the breadcrumb. (not in the navtree)
> 
> Let me know if I should put in its own separate issue, or I shall provide more info, or both.

The Vetur is used typescipt version in node_modules when `vetur.useWorkspaceDependencies` is true.
The `TypeScript: Select TypeScript Version` command is not work in Vetur.
Follow up #1996.

**Comment by jahhernandez** [comment] 2020-08-25 20:01
I am still having the same issue, is marked as closed but the go to symbol remains the same, is there something I need to do?

**Comment by octref** [comment] 2020-08-26 02:15
Duplicate of #1849, which is fixed when upgrading to TS 4.0.2.

**Closed by octref** 2020-08-26 02:15 UTC
Labels: duplicate
