### ISSUE TITLE
Cannot redeclare block-scoped variable '$crumbs'

### ISSUE THREAD

**Issue by sandikodev** [vuejs/vetur#3555] opened 2022-10-28 03:11 UTC
i have little pieces of code
```
<!-- pages.vue -->

<script lang="ts" setup>
const { $crumbs } = useNuxtApp()
$crumbs.set([
  { name: 'Home', to: '/' },
  { name: 'Pages', to: '/pages' },
])
</script>
<template>
...
</template>
```

then vetur shows me an error
```Cannot redeclare block-scoped variable '$crumbs'.```

```
[{
	"resource": "/home/dev/project/kerja/dashboard/src/pages/pages.vue",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "2451",
	"severity": 8,
	"message": "Cannot redeclare block-scoped variable '$crumbs'.",
	"source": "Vetur",
	"startLineNumber": 4,
	"startColumn": 9,
	"endLineNumber": 4,
	"endColumn": 16
}]
```

**Comment by yoyo930021** [comment] 2022-11-01 10:22
We don't support `<script setup>` now.
Duplicate of https://github.com/vuejs/vetur/issues/2296

**Comment by yoyo930021** [comment] 2022-11-01 10:22
Duplicate of https://github.com/vuejs/vetur/issues/2296

**Closed as completed by yoyo930021** 2022-11-01 10:22 UTC
Labels: duplicate
