### ISSUE TITLE
Feature to Edit Snippets

### ISSUE THREAD

**Issue by unixneo** [vuejs/vetur#1138] opened 2019-03-07 02:52 UTC
Have read the docs and Googled around and cannot find out where to edit the existing vutur snippets in Visual Studio Code.

For example, I want to change the basic vutur scaffolding to add the scoped directive to the style tags.  I realize this is a small thing and don't want to bother the developers, but if you could reply with "how to edit or customize existing vutur scaffolding",  I would appreciate it.

Thanks.

**Comment by octref** [comment] 2019-03-21 23:14
Duplicate of #1151.

**Closed by octref** 2019-03-21 23:14 UTC
