### ISSUE TITLE
Vetur doesn't respect importModuleSpecifier* settings

### ISSUE THREAD

**Issue by wenfangdu** [vuejs/vetur#1905] opened 2020-05-13 08:41 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.24.0
- VS Code version: 1.45.0

## Problem

Vetur doesn't respect the following settings
![image](https://user-images.githubusercontent.com/28700378/81790228-af006500-9537-11ea-8223-0c1c0d5385fa.png)
![image](https://user-images.githubusercontent.com/28700378/81790251-ba539080-9537-11ea-9803-2ca3d197fcb1.png)
![image](https://user-images.githubusercontent.com/28700378/81790266-c2abcb80-9537-11ea-86c2-87a4fc206eb6.png)

## Reproducible Case
Expected behavior (in .js file)
![image](https://user-images.githubusercontent.com/28700378/81790799-7dd46480-9538-11ea-9f38-0b19ac37f724.png)
Current behavior (in .vue file)
![image](https://user-images.githubusercontent.com/28700378/81790634-3f3eaa00-9538-11ea-9979-783a96ec7075.png)

**Comment by yoyo930021** [comment] 2020-06-03 12:53
#1297 #1177

**Comment by hikerpig** [comment] 2020-06-03 14:24
I've created a PR https://github.com/vuejs/vetur/pull/1753, but it's not merged yet.

**Comment by yoyo930021** [comment] 2020-06-04 12:47
I plan to fork this project and maintain until this project reactivate.
Maybe fixed it or merge this PR for fork project.

**Comment by yoyo930021** [comment] 2020-06-06 12:34
I publish self-maintenance vscode extension.
This extension will be maintained until Vetur is reactivated.

https://marketplace.visualstudio.com/items?itemName=yoyo930021.vuter

**Comment by octref** [comment] 2020-08-03 11:45
Duplicate of #1177, which is fixed by #1753.

**Closed by octref** 2020-08-03 11:45 UTC
Labels: duplicate
