### ISSUE TITLE
The import .vue file in the .ts file will not be able to locate

### ISSUE THREAD

**Issue by masquevil** [vuejs/vetur#2950] opened 2021-05-21 08:19 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS
- Vetur version: 0.33.1
- VS Code version: 1.56.0

#### Bug 1
In the vscode editor, if you import a `.vue` file in a `.ts` or `.js` file, you will not be able to locate the file, only `shims-vue.d.ts`.
But there is no problem importing the `.vue` file in the `.vue` file：

Note that there is no entry.vue file in the dropbox:
![dropbox](https://user-images.githubusercontent.com/3344691/116192094-f4756c80-a75f-11eb-9393-ca88cebe2982.png)

command + click to jump, it will jump to `shims-vue.d.ts`:
![shims-vue.d.ts](https://user-images.githubusercontent.com/3344691/116192835-fc81dc00-a760-11eb-8d90-74a0534ccf95.png)

#### Bug 2
The import `.vue` file in the `.vue` file can be located, but two modules will be found, which are the same file but in different scopes:

Found 2 modules：
![Found 2 modules](https://user-images.githubusercontent.com/3344691/116193034-4b2f7600-a761-11eb-9eaa-11d1eacaf7b9.png)

Click the first one to enter, all the contents in the `<script>` tag will be selected:
![selected area 1](https://user-images.githubusercontent.com/3344691/116193089-64d0bd80-a761-11eb-9d68-8fde03688a8f.png)

Click the second one to enter, it will select from the `<script>` tag to the end of the file:
![selected area 2](https://user-images.githubusercontent.com/3344691/116193188-8b8ef400-a761-11eb-918f-0441d40ba0f4.png)

#### Bug 3
```js
import Comp from './xxx/yyy'
```
If you do not write `.vue` or `index.vue`, the corresponding file cannot be recognized.

## Reproducible Case
https://github.com/masquevil/stock

**Comment by satrong** [comment] 2021-05-25 01:41
the same to me.

**Comment by yoyo930021** [comment] 2021-06-02 03:00
Duplicate of https://github.com/vuejs/vetur/issues/2591

**Closed** 2021-06-02 03:00 UTC
Labels: duplicate

**Comment by masquevil** [comment] 2021-06-14 07:47
Bug 1 can follow: https://github.com/vuejs/vetur/issues/2016
Bug 2 & 3 still not resolved
