### ISSUE TITLE
load types that are in subfolder

### ISSUE THREAD

**Issue by Upd4ting** [vuejs/vetur#2196] opened 2020-08-26 11:28 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Window 10 version 1909 (18363.1016)
- Vetur version: Latest
- VS Code version: 1.8.41

## Problem

I'm having a folder `www` with a nuxt application inside.

My tsconfig look likes this:

```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "esnext",
    "moduleResolution": "node",
    "lib": ["esnext", "esnext.asynciterable", "dom"],
    "esModuleInterop": true,
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noEmit": true,
    "experimentalDecorators": true,
    "baseUrl": ".",
    "paths": {
      "~/*": ["./*"],
      "@/*": ["./*"]
    },
    "types": ["@types/node", "@nuxt/types"]
  },
  "exclude": ["node_modules", ".nuxt", "dist"]
}
```

I created a `types` folder with an `index.d.ts` inside:

```
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface Vue {
    $test: string;
  }
}
```

where i'm trying to augment the typing of Vue and when i'm trying to use my `$test` property i'm getting the error `Property '$test' does not exist on type 'default'.Vetur(2339)`

But if i'm opening directly the `www` folder into vscode instead of the parent directory, that's working fine.

Any solutions to this?

**Comment by rchl** [comment] 2020-08-26 12:06
Just add the path to the `types` array like:
```js
"types": ["./types", "@types/node", "@nuxt/types"]
```
or whatever the path is relative to `tsconfig.json`

**Comment by Upd4ting** [comment] 2020-08-26 21:33
I think I already tried this but i'll retry tomorrow.
My `types` folder will only be loaded if I open vscode directly into `www` folder and not the parent one

**Comment by rchl** [comment] 2020-08-27 13:36
I believe Typescript automatically checks the `types` directory if it's in the same directory as `tsconfig.json`. Otherwise you have to manually point to types.

This is more of a TS question than Vetur specific problem IMO.

**Comment by triforcely** [comment] 2020-08-27 17:57
Isn't your problem related to https://github.com/vuejs/vetur/issues/815 ?

**Comment by rchl** [comment] 2020-08-27 18:01
I've assumed a structure like (since it wasn't specified in initial comment):
 - www/
 - www/types/index.d.ts
 - tsconfig.json

but yeah, if the tsconfig.json was inside `www/` then it sounds like a duplicate of #815.

**Comment by Upd4ting** [comment] 2020-08-27 18:57
> I've assumed (since it wasn't specified in initial comment) a structure like:
> 
> * www/
> * www/types/
> * www/types/index.d.ts
> * tsconfig.json
> 
> but yeah, if the tsconfig.json was inside `www/` then it sounds like a duplicate of #815.

Yeah my tsconfig.json is into my `www` folder



> Isn't your problem related to #815 ?

Yeah should be related. I assume there is no workaround currently?

I also tried to create a `tsconfig.json` at the root and specify my types folder manually but it doesn't work either

**Comment by rchl** [comment] 2020-08-27 19:02
> I also tried to create a `tsconfig.json` at the root and specify my types folder manually but it doesn't work either

It should work in this case. Maybe you did something wrong. Provide a repo that reproduces.

**Comment by Upd4ting** [comment] 2020-08-28 13:31
Okay so I made a repo that reproduces and I actually better understood what's happening.

https://github.com/Upd4ting/vetur-bug-repro

Here is my structure:

- www/types/
- www/tsconfig.json
- www/pages/index.vue
- www2/types/
- www2/tsconfig.json
- www2/pages/index.vue

As you can see into my repo, in the `www` folder i'm augmenting vue and add a `$test: string` property. 
In the `www2` folder i'm augmenting vue and add a `$test2: string` property.

It seems that my `www/types` folder is correctly read because in my `www/pages/index.vue` I can use it fine.
But my `www2/types` isn't read because in my `www2/pages/index.vue` I can't use `$test2` property. 
Another strange fact is that I can use `$test` property into `www2/pages/index.vue` but that has been defined into my `www/types`

I hope that helps to understand the problem.

**Comment by rchl** [comment] 2020-08-28 13:40
The `$test` will work fine in the first directory (`www/`) if you'll do as I've said before:
```
"types": ["./types", "@types/node", "@nuxt/types"]
```

The `www2` won't work which looks like #815.

**Comment by rchl** [comment] 2020-08-28 13:41
BTW. Why can't you add both folders to the project separately? Then it should work for both.

**Comment by Upd4ting** [comment] 2020-08-28 13:44
In fact like I said `$test` already work fine without adding `./types` so that's okay.

But yeah it looks like #815 and there is no workaround currently?

I need them in the same vscode project for facility. Each different folder I have is a different service for `docker` and I can start them all in just one command like that. It's to facilitate my team development process.

**Comment by Upd4ting** [comment] 2020-09-03 09:21
@rchl No workaround currently?

**Comment by yoyo930021** [comment] 2020-12-09 13:25
> @rchl No workaround currently?

You can use `vetur.config.js` to solve this problem now.
https://vuejs.github.io/vetur/guide/setup.html#advanced

**Closed by yoyo930021** 2020-12-09 13:25 UTC
Labels: question
