### ISSUE TITLE
Cannot find module, Veteur 2307

### ISSUE THREAD

**Issue by AbderrazzakB** [vuejs/vetur#1677] opened 2020-01-24 23:28 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux (Archlinux)
- Vetur version: 0.23.0
- VS Code version: 1.41.1

## Problem
I keep getting "Cannot find module" in VS Code Linting when I'm trying to import a component, but there is no error in the console and everything works fine.
![veteur-issus-import](https://user-images.githubusercontent.com/23277063/73110917-7e54db00-3f08-11ea-8e51-3540212acaad.gif)
![veteur-issus-import-1](https://user-images.githubusercontent.com/23277063/73110929-86ad1600-3f08-11ea-8c0f-633e5081501b.gif)

## Reproducible Case
I decided to split my components into loosely-coupled files as mention in the documentation of VueJs, now the component in a parent folder that named after the component name then there is an index.vue, script.ts, and, style.scss inside the folder.
I assume that I can import the component only by calling the parent folder and that works fine, but Veteur keep gives an error in VSCode.

**Comment by octref** [comment] 2020-02-10 20:02
Duplicate of #762.

**Closed by octref** 2020-02-10 20:02 UTC

**Comment by yb0112** [comment] 2021-06-22 07:37
试试将这个项目的文件放在根目录下

**Comment by yb0112** [comment] 2021-06-22 07:38
因为tsconfig.json没有加载成功导致的，可以将这个项目放在根目录下试试

**Comment by bossikill** [comment] 2021-06-30 16:33
tsconfig.json

`{
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "strict": true,
        "jsx": "preserve",
        "sourceMap": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "lib": ["esnext", "dom"],
         // add this line 加这行
        "baseUrl": ".",
         // add this line 加这行
        "paths": {
            "@/*": ["src/*"]
        }
    },
    "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue", "src/third/element.js"]
}`
