### ISSUE TITLE
Cannot auto suggest in return {} of setup() method

### ISSUE THREAD

**Issue by kytosai** [vuejs/vetur#2760] opened 2021-03-05 07:28 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: macOS 11.12.1 (16in)
- Vetur version: v0.33.0
- VS Code version: v1.54.1

## Problem

Vetur cannot auto suggest variable in return of setup() method in vue 3

Demo 1: https://prnt.sc/10dhqrh 
Demo 2: https://prnt.sc/10dhrb8

**Comment by yoyo930021** [comment] 2021-03-05 10:56
Duplicate of https://github.com/vuejs/vetur/issues/2544

**Closed** 2021-03-05 10:56 UTC
Labels: duplicate
