### ISSUE TITLE
Vetur crashes after upgrade to 0.19 

### ISSUE THREAD

**Issue by leopoldkristjansson** [vuejs/vetur#1225] opened 2019-04-24 14:00 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.19.0
- VS Code version: 1.33.1 (system setup)

## Problem

Getting the following message from VS Code and Vetur stops working.
"The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."
**If I downgrade to 0.18.1 the problem goes away**

![18cae3aa4fdff114c796b32f6d00b0ad](https://user-images.githubusercontent.com/2579324/56665276-053f0380-66aa-11e9-94ae-25f9a6219563.png)

**Comment by ktsn** [comment] 2019-04-24 14:02
Duplicate of #1220

**Closed by ktsn** 2019-04-24 14:02 UTC
