### ISSUE TITLE
Resolve json modules in typescript

### ISSUE THREAD

**Issue by filiplindqvist-netlight** [vuejs/vetur#2313] opened 2020-09-23 09:00 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.28.0
- VS Code version: 1.49.1

## Problem

Vetur has problems detecting json modules in typescript. 
![image](https://user-images.githubusercontent.com/71712056/93990788-d855bb00-fd8b-11ea-95d0-aaea49390433.png)

## Reproducible Case
Repo: https://github.com/filiplindqvist-netlight/vetur-bug-jsonmodule
Change: https://github.com/filiplindqvist-netlight/vetur-bug-jsonmodule/commit/beb48880c96b56a1454580e6b0dde9ecf3a6b06f

**Comment by ci010** [comment] 2020-09-24 08:56
I think the draft PR #1495 might resolve this, but it seems that PR has paused for a while.

**Comment by yoyo930021** [comment] 2020-09-24 08:59
> I think the draft PR #1495 might resolve this, but it seems that PR has paused for a while.

No, It isn't.
because The related part is in #2095 and it is merged.

**Comment by yoyo930021** [comment] 2020-09-24 09:07
If anyone can reproducible?
I can't reproducible.
I need more information.
![截圖 2020-09-24 下午5 06 37](https://user-images.githubusercontent.com/9126398/94124993-58f9e180-fe88-11ea-8cc1-efeadae26b07.png)

**Comment by filiplindqvist-netlight** [comment] 2020-09-24 14:39
@yoyo930021 What more information is relevant to provide?

**Comment by yoyo930021** [comment] 2020-09-24 14:57
> @yoyo930021 What more information is relevant to provide?

1. open vscode.
2. disable all other extensions.
3. enable Vetur.
4. open reproducible case folder.
5. Is it achievable?

**Comment by filiplindqvist-netlight** [comment] 2020-09-27 13:45
Thanks for the coaching. I did the above steps, and now it seems to work, even with ALL extensions active again. 🧐
We can close this for now then. I'll try my private repos see if I can repo at all anymore. Thanks! :+1:

**Closed** 2020-09-28 02:15 UTC
Labels: integ:typescript, need-more-info
