### ISSUE TITLE
html.autoClosingTags feature doesn't work in <template> section

### ISSUE THREAD

**Issue by ianwalter** [vuejs/vetur#900] opened 2018-09-10 23:33 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS High Sierra
- Vetur version: 0.12.6
- VS Code version: 1.27.1

## Problem

When writing HTML in the `<template>` section of a Vue SFC, tags are not automatically closed even though `html.autoClosingTags` is set to `true` in my settings.json. The feature works correctly when editing HTML files in VS Code so I expected it to work within `<template>` as well.

## Reproducible Case

1. Set html.autoClosingTags to true (I think it's true by default though).
2. Create a .vue file.
3. Add a `<template>` tag and add a `<div>` tag within it for example.

**Comment by jtsom** [comment] 2019-01-22 13:38
Came here to report this same thing, found this, found no replies. Any movement on this issue?

**Comment by octref** [comment] 2019-03-14 22:42
Duplicate of #565.

**Closed by octref** 2019-03-14 22:42 UTC
Labels: duplicate
