### ISSUE TITLE
Syntax highlighting break for </template and > not in same line in template

### ISSUE THREAD

**Issue by nibytes** [vuejs/vetur#1211] opened 2019-04-18 23:45 UTC
- [*] I have searched through existing issues
- [*] I have read through [docs](https://vuejs.github.io/vetur)
- [*] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.18.1
- VS Code version: 1.33.1

## Problem

![изображение](https://user-images.githubusercontent.com/15169344/56397453-787ceb80-624c-11e9-9a40-780e515c7088.png)

## Reproducible Case

I don't know, this behavior in one file.
I restarted VS, rename file, and reinstalled vetur. But highlighting not work in this file,

**Comment by nibytes** [comment] 2019-04-18 23:50
Ok something in template broken highlighting
```
<template>
  <div class="l-content l-content_fill">
    <div class="ipr-add__status">
      <div class="ipr-add__status-item">
        <span class="ipr-add__status-cell">
          <i class="fa fa-heartbeat" aria-hidden="true"></i>
        </span>
        <span class="ipr-add__status-cell">
          <strong>Статус: </strong>в процессе
        </span>
      </div>
      <div class="ipr-add__status-item">
        <span class="ipr-add__status-cell">
          <i class="fa fa-spinner" aria-hidden="true"></i>
        </span>
        <span class="ipr-add__status-cell">
          <strong>Рассмотрение: </strong>
          <template v-if="task.ReviewDueDate">{{
            task.ReviewDueDate | moment("from", "now")
          }}</template>
          <template v-else
            >Не установлено
            </template>
        </span>
      </div>
      <div class="ipr-add__status-item">
        <span class="ipr-add__status-cell">
          <i class="fa fa-fire" aria-hidden="true"></i>
        </span>
        <span class="ipr-add__status-cell">
          <strong>Дедлайн: </strong>
          <template v-if="task.DueDate">{{
            task.DueDate | moment("from", "now")
          }}</template>
          <template v-else
            >Не установлено</template
          >
        </span>
      </div>
    </div>
  </div>
</template>
```

**Comment by dombavetta** [comment] 2019-04-24 16:25
I'm experiencing the same issue, script and style sections for one file no longer have syntax highlighting.

**Comment by dombavetta** [comment] 2019-04-24 17:44
I have created a reproducible repo for this case, which can be pulled down and ran from here [https://github.com/dombavetta/vetur-template-interpolation-issues](url).

The problematic file -> [https://github.com/dombavetta/vetur-template-interpolation-issues/blob/master/pages/test.vue](url)

The issue appears to be caused by this line and the way it is formatted (24) `<span
          v-show="
            formDirtyFlags.reason &&
              (userHasNonSchedualableProvider ||
                someLongVariableNameThatIsGoingToGetNewLined)
          "
          class="error"
        >`

Removing that span resolves the highlighting issues.

**Comment by octref** [comment] 2019-04-24 18:30
```
          <template v-else
            >Не установлено</template
          >
```

Man, why would you write your code like this...
Vetur looks for `</template>` to close your opening `<template>`. I'm not sure if there's an easy fix for the textmate grammar.

**Comment by dombavetta** [comment] 2019-04-24 19:10
@octref I doubt he purposely wrote it like that. eslint/prettier will format it like that to prevent unnecessary whitespace from making it into the markup. Thats what it does for me at least.. I know its ugly but I guess theres some good reasoning behind it. For me its easier to just submit to the formatters that fight them or clutter my code with disable and ignore comments.

**Comment by octref** [comment] 2019-05-08 18:22
This doesn't seem to be possible with TextMate:

- You can only use single-line regexes in TextMate, see https://github.com/Microsoft/vscode-textmate/issues/32
- The opening `<template>` couldn't find a closing `</template>` if `>` is not on the same line as `</template`

**Comment by fabsenet** [comment] 2019-09-25 14:38
this formatting is a result of [whitespace-sensitive-formatting in prettier 1.15 and later](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting)

also, it only breaks the syntax highlighting if it is a `template` tag.

breaks highlighting:
```html
<template v-else
    >abc</template
>
```
works fine (replaced template with div tag only):
```html
<div v-else
    >abc</div
>
```

**Comment by Tsuyoshi84** [comment] 2020-01-11 07:04
I just faced the same problem. The foolowing code breaks highlighting of VS Code.

```html
<template v-if="value"
  >Some message</template
>
<template v-else
  >Another message</template
>
```


But thanks to @fabsenet, I figured out some workarounds of this problem.


#### 1. Using `display: block`

[As Prettier mentions](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting),  we can use `display: block` comment to prevent `<template>` from being broken.

```html
<!-- display: block -->
<template v-if="value">
  Some message
</template>
<!-- display: block -->
<template v-else>
  Another message
</template>
```

#### 2. Using `ignore` option

Another option is to set `htmlWhitespaceSensitivity` to `ignore` in prettier config.

```
  "htmlWhitespaceSensitivity": "ignore"
```

However, this change would affect the entire code formating, so we should keep in mind that.

**Comment by ssorallen** [comment] 2020-01-21 22:09
Since Prettier enabled whitespace-sensitive-formatting by default, more and more of my Vue SFC have become blobs of all-white JavaScript because of this bug, so I took a look today. I don't yet have a solution, but here are my notes:

* **The `<template>` tag both applies a new grammar and is a valid tag *within* that grammar**. The grammars currently do not differentiate between a closing `</template>` within the grammar block and a closing `</template>` that *ends* the grammar block. `<template>` tags recursively apply the Vue HTML grammar because of https://github.com/vuejs/vetur/blob/f12543fb94cdaf5a5aad1215781165520f3e4c58/syntaxes/vue-html.tmLanguage.json#L198

    **Potential solution**:
    Match the closing `</template>` at the beginning of a line to mark the close of the "text.html.vue-html" grammar block.

    For example:

      <template>
        <div>
          
          <template v-if="true">Foo</template>
        </div>
      </template> 

    **What I tried**:
    I updated [L268](https://github.com/vuejs/vetur/blob/f12543fb94cdaf5a5aad1215781165520f3e4c58/syntaxes/vue.tmLanguage.json#L268) to be the following (added the caret):

      "end": "^(</)(template)(>)",

    this effectively matched only the outermost `</template>` to close the grammar block, but then `</template>` tags within the grammar did not match regular HTML closing tags.

This would introduce a new restriction on how SFCs must be formatted, but it would enable differentiating the two types of closing `</template>` tags.

**Closed** 2020-02-10 19:47 UTC
Labels: bug, grammar

**Comment by yacoob** [comment] 2021-07-11 15:30
As I've just bumped into this: syntax highlighting for `<script>` breaks also if the entire `<template>...</template>` block is on a single line :)
