### ISSUE TITLE
Option to only validate interpolation errors for templates

### ISSUE THREAD

**Issue by pietdevries94** [vuejs/vetur#1440] opened 2019-09-24 12:44 UTC
I don't use vetur to validate the templates, but vue-cli, so I have disabled the template validation. However, I would like to get the experimental interpolation errors. Is there a way to validate interpolation errors, but keep eslint quiet?

**Comment by ktsn** [comment] 2019-10-02 03:18
Duplicate of #1293

**Closed by ktsn** 2019-10-02 03:18 UTC
