### ISSUE TITLE
Bundling resources would improve performance a lot

### ISSUE THREAD

**Issue by robole** [vuejs/vetur#2360] opened 2020-10-08 07:15 UTC
- [x] I have searched through existing issues

## Feature Request

If you bundle and minify source files, you could improve activation time. 

You can read this article [Is Your VS Code Extension Slow? Here's How to Speed it Up! ](https://dev.to/azure/is-your-vs-code-extension-slow-heres-how-to-speed-it-up-4d66) to understand the benefits. John said that bundling improved the Azure Account extension activation time by 50%.

**Comment by yoyo930021** [comment] 2020-10-08 07:27
https://github.com/vuejs/vetur/issues/2359#issuecomment-705385596

**Comment by yoyo930021** [comment] 2020-10-08 07:27
Duplicate of #2233

**Closed** 2020-10-08 07:27 UTC
Labels: duplicate
