### ISSUE TITLE
Capability to specify auto-import style

### ISSUE THREAD

**Issue by cmeyertons** [vuejs/vetur#1297] opened 2019-05-18 12:51 UTC
- [X ] I have searched through existing issues
- [X ] I have read through [docs](https://vuejs.github.io/vetur)
- [ X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.21.0
- VS Code version: 1.33.1

## Problem

VS Code Typescript has to capability to specify auto-import module behavior to prefer non-relative imports -- would be great if Vetur either respected the Typescript setting or had the same capability

![image](https://user-images.githubusercontent.com/19917677/57970008-6b354880-7941-11e9-9f3a-f2d875bdf66d.png)

## Reproducible Case
1. Set typescript -> preferences -> import module specifier to non-relative
2. perform an auto-import
3. Vetur uses a relative import

**Comment by audoban** [comment] 2019-06-20 19:58
I have the same problem

**Comment by cainaf** [comment] 2019-09-27 17:09
this would be really nice

**Comment by TimeBandit** [comment] 2019-11-28 12:27
I need this, my life depends on in.

**Comment by WORMSS** [comment] 2019-12-12 10:42
I've had to do a lot of additional imports in quite a few classes today and it always importing a massive bunch of `../../../../..` is really starting to grate

**Comment by bobmoff** [comment] 2020-02-17 09:02
Yep. Its annoying. A workaround is to instead of using the autocomplete, click the yellow lightbulb. That way the import added is non-relative.

**Comment by Janther** [comment] 2020-04-06 21:54
I'd like this as well :)

**Comment by octref** [comment] 2020-08-03 11:46
Duplicate of #1177, which is fixed by #1753.

**Closed by octref** 2020-08-03 11:46 UTC
Labels: duplicate
