### ISSUE TITLE
Import class from SFC in Typescript file with real type (not Vue)

### ISSUE THREAD

**Issue by Glandos** [vuejs/vetur#2827] opened 2021-03-31 12:56 UTC
- [X] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.33.1
- VS Code version: VSCodium 1.54.3

## Problem
I want to import a Vue class (defined with `vue-class-component`) from `.vue` SFC into a Typescript file. The import is OK, but the typing is not: the imported class is typed as `Vue` (as declared in the `vue-shims.d.ts` and not as the real class, so there are errors everywhere. When build and run, there is no error though.

![image](https://user-images.githubusercontent.com/297578/113146906-85742900-9230-11eb-93cd-dcd1480a1fd1.png)

Of course, this works nicely when the import is done in another SFC, and I've read https://vuejs.github.io/vetur/guide/FAQ.html#vue-file-cannot-be-imported-in-ts-file but this doesn't deal with the real typing of the imported class.

Is it something that I shouldn't do? Is there something I forgot to configure?

## Reproducible Case
https://github.com/Glandos/vetur-import-from-sfc

**Comment by Choooks22** [comment] 2021-03-31 17:00
That's because any `*.vue` import would always be treated by typescript as type of `Vue`, check the `vue-shims.d.ts` file for how `*.vue` files are declared.

Your best option would be to implement the logic in `.ts` files and import it inside your components rather than the other way around (which is what you're currently doing)

**Comment by Glandos** [comment] 2021-03-31 18:49
That's not really possible. The class method are computing some attributes based on DOM nodes, so it's not meant to be done outside the component.

However, I found the solution using [mixins](https://class-component.vuejs.org/guide/extend-and-mixins.html#mixins).

My question here was then: why the "special treatment" for imports of `.vue` files inside `.vue` files can't be replicated in TS files?

**Comment by yoyo930021** [comment] 2021-04-07 11:55
Duplicate of #1322

**Closed by yoyo930021** 2021-04-07 11:55 UTC

**Comment by Glandos** [comment] 2021-04-07 15:14
OK, so let's wait for #673 and the integration of https://github.com/HerringtonDarkholme/vue-ts-plugin or similar.
