### ISSUE TITLE
v0.37.1 Code Snippets Disappear 代码提示丢失

### ISSUE THREAD

**Issue by MrFlyHouse** [vuejs/vetur#3651] opened 2023-02-20 09:20 UTC
## Info

- Platform: Win10 22H2 x64
- Vetur version: 0.37.1
- VS Code version: 1.75.1

## Problem

After I update to v0.37.1, the code snippets disappear. If I return the version to 0.36.1 or disable vetur, it comes back.
Please fix the bug asap, thx.
刚才升级到0.37.1之后，代码片段提示丢失了，回到0.36.1或者禁用vetur就没关系，还请开发者解决，谢谢了。

**Comment by Kaier33** [comment] 2023-02-20 12:26
0.37.2  遇到同样的问题

**Comment by l-moondream** [comment] 2023-02-21 02:24
自动更新到0.37.2版本重新加载后，插件一直提示加载，代码片段提示和代码展开收起全都失效

**Comment by bailuochen** [comment] 2023-02-21 03:06
我把所有的扩展都删除了，vscode重新安装后，才发现是vetur的问题

**Comment by shqming** [comment] 2023-02-21 03:46
v0.37.2，同样的问题：保存冲突、没有提示，先回滚到v0.36.1

**Comment by subn3t** [comment] 2023-02-21 21:04
I am seeing the same issue. It looks like the status bar in VS Code shows "Vetur: Loading Project..." and never completes. Downgrading to 0.36.1 resolves the issue. "Show doctor info" also does nothing in this case. Not sure how to give repro steps at this point since it may be project specific, and it's a large proprietary project. Are there any logs I can access?

**Comment by yoyo930021** [comment] 2023-02-21 23:57
> I am seeing the same issue. It looks like the status bar in VS Code shows "Vetur: Loading Project..." and never completes. Downgrading to 0.36.1 resolves the issue. "Show doctor info" also does nothing in this case. Not sure how to give repro steps at this point since it may be project specific, and it's a large proprietary project. Are there any logs I can access?

Show vetur output? Repro case?

**Comment by Aeroxian** [comment] 2023-02-23 02:07
rollBack to v0.36.1 is alright,just wait

**Comment by yoyo930021** [comment] 2023-02-23 05:30
Duplicate of #3657 and fix in v0.37.3

**Closed by yoyo930021** 2023-02-23 05:30 UTC
Labels: lsp:completion, no-repro-case
