### ISSUE TITLE
missing not required props

### ISSUE THREAD

**Issue by kibilizard** [vuejs/vetur#2235] opened 2020-09-04 08:11 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.27.1
- VS Code version: 1.48.2

## Problem
in linting missed props whitch does not set as required
![missing_props](https://user-images.githubusercontent.com/21031226/92215701-d9d34800-ee9d-11ea-97ae-4cc2211dfe4b.png)

## Reproducible Case

https://github.com/kibilizard/missing_non_required
![testmissing](https://user-images.githubusercontent.com/21031226/92216709-574b8800-ee9f-11ea-99a2-c9210876d326.png)

**Comment by yoyo930021** [comment] 2020-09-04 08:16
In #2141 ,
When no required or default, it have a warning about not have.
So it's a feature not a bug.

**Comment by kaangokdemir** [comment] 2020-09-04 08:20
Even it might be a good feature, is there a way to close this one? Also it's not working with v-model binding for value props.

Screenshots:

<img width="586" alt="Ekran Resmi 2020-09-04 11 19 28" src="https://user-images.githubusercontent.com/51219535/92217656-a6de8380-eea0-11ea-86c1-d5b2050ca9c7.png">

<img width="366" alt="Ekran Resmi 2020-09-04 11 19 22" src="https://user-images.githubusercontent.com/51219535/92217676-ae9e2800-eea0-11ea-8a78-640d47a5a427.png">

**Comment by kibilizard** [comment] 2020-09-04 08:23
> In #2141 ,
> When no required or default, it have a warning about not have props.
> So it's a feature not a bug.

you offer me to rewrite all projects because it your new feature?

**Comment by yoyo930021** [comment] 2020-09-04 08:28
> Even it might be a good feature for new projects, is there a way to close this one especially for legacy projects? Also it's not working with v-model binding for value props.
> 
> Screenshots:
> 
> <img alt="Ekran Resmi 2020-09-04 11 19 28" width="586" src="https://user-images.githubusercontent.com/51219535/92217656-a6de8380-eea0-11ea-86c1-d5b2050ca9c7.png">
> 
> <img alt="Ekran Resmi 2020-09-04 11 19 22" width="366" src="https://user-images.githubusercontent.com/51219535/92217676-ae9e2800-eea0-11ea-8a78-640d47a5a427.png">
> 
> <img alt="Ekran Resmi 2020-09-04 11 19 11" width="366" src="https://user-images.githubusercontent.com/51219535/92217700-b8c02680-eea0-11ea-9474-b114edf5af74.png">

I add a issue about this.
#2236

**Comment by yoyo930021** [comment] 2020-09-04 08:33
> > In #2141 ,
> > When no required or default, it have a warning about not have props.
> > So it's a feature not a bug.
> 
> you offer me to rewrite all projects because it your new feature?

It don't effect in runtime, so you can ignore it.
This feature is a reminder.
Maybe we can add a option to disable prop validator warning.

**Comment by victorgarciaesgi** [comment] 2020-09-04 08:34
> In #2141 ,
> When no required or default, it have a warning about not have props.
> So it's a feature not a bug.

Why does it needs do display a warning when all the props are optional?

**Comment by ilyakamens** [comment] 2020-09-04 15:32
This is a great tool, and I've really enjoyed using it for the last several months.

I also see yellow squiggly underlines for non-required properties. I personally find it very distracting. IMHO, I'm not sure a warning is necessary for omitting an optional parameter, which I think is a standard use case. For example, Python linters don't complain when omitting **kwargs to function calls. It'd be great if there was a way to opt out of these warnings!

**Comment by octref** [comment] 2020-09-04 16:15
@ilyakamens #2249

**Comment by Killea** [comment] 2020-09-04 20:03
The logic is wrong.

**Comment by dipasqualew** [comment] 2020-09-04 20:36
Can reproduce on VS Code on Ubuntu 20.04, in a Vue-Cli + TypeScript project.

The implementation fails the common use case of binding `value` with `v-model`. This breaks the linter. Please provide a way to disable the rule or account for situations where props are provided via directives.

Thanks

**Comment by adlio** [comment] 2020-09-04 21:01
Here by way of Google help future searchers. When using v-model attributes, they all report:

```
<MyComponent> misses props: value
```

So if you're googling for why you're seeing "misses props: value" messages... this issue explains why.

**Comment by tobidalhof** [comment] 2020-09-04 21:56
`0.27.0` and `0.27.1` are broken, rolled back to `0.26.1` and the error was gone

![image](https://user-images.githubusercontent.com/10046578/92287381-e9887600-ef09-11ea-8633-b00b89a11fd9.png)

**Comment by automKmilo** [comment] 2020-09-05 00:47
Hi.
I fount this feature very useful, but I think you should fix this little issues with v-model and no required props. It would be nice to have type validation in template too. Thanks.

**Comment by Panbehkar** [comment] 2020-09-05 16:00
I have this issue too -_-

**Comment by rockmandash** [comment] 2020-09-05 16:07
Same here

**Comment by rockmandash** [comment] 2020-09-05 16:13
@yoyo930021 Are optional props need to explicitly defined `required: false` in <Component /> props section?

I just want to know what is the standard way to write Vue components.

**Comment by octref** [comment] 2020-09-06 09:45
- `v-model` and `sync` issue is fixed in #2241.
- With #2249 you can turn prop validation off with `"vetur.validation.templateProps": false`

**Closed by octref** 2020-09-06 09:45 UTC
Labels: question

**Comment by dipasqualew** [comment] 2020-09-06 10:22
Thank you @octref for your quick reaction on this 🙂

**Comment by yoyo930021** [comment] 2020-09-07 03:37
> @yoyo930021 Are optional props need to explicitly defined `required: false` in props section?
> 
> I just want to know what is the standard way to write Vue components.

I'd expect at least `required` or `default` for a serious pursuit.

```
props: {
  foo: {
    type: String
  }
}
```
But I think this case might be taken as `required: false`.
I will talk to @octref.

**Comment by yoyo930021** [comment] 2020-09-07 03:49
> > In #2141 ,
> > When no required or default, it have a warning about not have props.
> > So it's a feature not a bug.
> 
> Why does it needs to display a warning when all the props are optional?

First of all, I didn't design this feature.
I found it in #2135 and handle some case in #2141 

But I think this feature is a reminder,
That's why we replace the error with a warning when it's not strictly defined.
I think VSCode's warning was too obvious and #2238 .
That's what's causing all the trouble.
But I think it's still a useful feature for strict projects.

**Comment by alykamb** [comment] 2020-10-02 18:21
I am having this issue in vue2 with typescript and vue-class-components. Notice how the error shows '?' on the optional props. Maybe this can be used to ignore them in the validation?

![Screenshot from 2020-10-02 15-15-47](https://user-images.githubusercontent.com/34348520/94956358-6d5e5f80-04c2-11eb-9782-44dbcfb15a5b.png)

This is the component code: 

![Screenshot from 2020-10-02 15-20-39](https://user-images.githubusercontent.com/34348520/94956630-e5c52080-04c2-11eb-81e9-e75341d6b939.png)

**Comment by tomitrescak** [comment] 2020-10-27 10:14
Sorry to write here, but I am not getting the error for required props. My prop is required, yet no warning or error is shown on the component that does not specify it.

**Comment by yoyo930021** [comment] 2020-10-27 10:21
> Sorry to write here, but I am not getting the error for required props. My prop is required, yet no warning or error is shown on the component that does not specify it.

Please set `{ vetur.validation.templateProps: true }`

**Comment by tomitrescak** [comment] 2020-10-27 10:33
Thanks for the super fast answer. Got it!

**Comment by meatnordrink** [comment] 2021-04-13 19:17
It's unfortunate that this is all-or-none. It would be great to have a warning when a required prop is missing; it's a hindrance to have an optional prop not passed throw a warning. 

The most logical and helpful behavior would be: 
* Error when a required prop is missing; 
* No error when an optional prop isn't (because, as the property is optional, that isn't an error).

The solution above, turning off `{ "vetur.validation.templateProps": true }`, means you have to choose between faulty validation or no validation. 

(I realize Vetur is in an awkward position, as it's a volunteer project that's become fairly critical to the Vue community. .)

**Comment by IcedNet** [comment] 2021-04-25 15:08
The logic is incorrect, if the prop is not required, not even if you are being "strict".
There is no need for any information at all.
I enjoy this tool, and several forks implement this properly - perhaps adopt one of their fixes?

**Comment by Jimmar** [comment] 2021-04-30 21:16
I'm getting this warning even though my props have default values
