### ISSUE TITLE
Multiple style tag syntax higlighting

### ISSUE THREAD

**Issue by crswll** [vuejs/vetur#623] opened 2018-01-08 00:01 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: MacOS
- Vetur version: 0.11.5
- VS Code version: 1.19.1 (1.19.1)

## Problem

Multiple style tags cause weird syntax highlighting.

<img width="540" alt="screen shot 2018-01-07 at 6 56 43 pm" src="https://user-images.githubusercontent.com/182222/34655743-d211adb4-f3dc-11e7-91e0-2d0563f08e41.png">

**Comment by crswll** [comment] 2018-01-08 00:04
Just came across a similar issue where this is a wontfix. Closing.

**Comment by crswll** [comment] 2018-01-08 00:10
I'm actually going to reopen this because it seems bigger than just this. I've attached a gif: 
![2018-01-07 19 08 16](https://user-images.githubusercontent.com/182222/34655831-6b458c20-f3de-11e7-99be-96056e463b12.gif)

**Comment by crswll** [comment] 2018-01-08 00:46
Digging a little deeper. It only happens with links to external stylesheets.

**Comment by HerringtonDarkholme** [comment] 2018-01-08 07:30
Actually it is a duplicate of https://github.com/vuejs/vetur/issues/591

**Closed** 2018-01-08 11:34 UTC
Labels: duplicate
