### ISSUE TITLE
Update to prettier 2.0 please

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/vetur#1925] opened 2020-05-20 09:31 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

**Comment by octref** [comment] 2020-06-08 02:54
Duplicate of #1794.

**Comment by Mister-Hope** [comment] 2020-06-08 03:23
I notice #1794 before opening this issue.#1794  is talking about Vetur issues when using prettier 2.0 in workspace, and some of the users already gave a workaround. While I am talking about update prettier in Vetur to 2.0

**Comment by octref** [comment] 2020-06-08 03:30
OK then

**Closed** 2020-07-05 03:02 UTC
Labels: bug, integ:prettier

**Comment by mesqueeb** [comment] 2020-07-05 12:31
@octref Thanks a lot for closing this ! When will this be live in VSCode? Much thanks!
