### ISSUE TITLE
about typescript question in the Vetur plugin

### ISSUE THREAD

**Issue by Eric124120** [vuejs/vetur#455] opened 2017-09-27 13:10 UTC
# about typescript question in the Vetur plugin

I've installed the Vetur plugin for this Vscode.
In Vscode there is a d3.d.ts file that defines Name, Age, and properties,  and now add a b attribute in the d3.d.ts file.
Your can find the b attribute in the ts file, and you can't find the b attribute in the vue file.
But reload the Vscode IDE，you can't find the b attribute in the vue file.
I want to find the b attribute immediately in the Vue file，do you have any good idea

![1041506502596_ pic_hd](https://user-images.githubusercontent.com/13373616/30913738-cbd80830-a3c3-11e7-9752-51cdb6741881.jpeg)![1051506502617_ pic_hd](https://user-images.githubusercontent.com/13373616/30914364-0a5268c4-a3c6-11e7-8aa7-f21765821c39.jpeg)![1061506502635_ pic_hd](https://user-images.githubusercontent.com/13373616/30915099-3eee470e-a3c8-11e7-9b1e-bcf7b0d4da73.jpeg)

**Comment by octref** [comment] 2017-09-27 17:41
![image](https://user-images.githubusercontent.com/4033249/30928420-76031646-a370-11e7-8dea-cca2fccd8115.png)

**Comment by HerringtonDarkholme** [comment] 2017-09-28 02:35
This should be a duplicate of https://github.com/vuejs/vetur/issues/355

> Your can find the b attribute in the ts file, and you can't find the b attribute in the vue file.
But reload the Vscode IDE，you can't find the b attribute in the vue file.
I want to find the b attribute immediately in the Vue file，do you have any good idea


This paragraph might contain one typo. The "reload VSCode" sentence should be 

> But reload the Vscode IDE，you can find the b attribute in the vue file.

OP probably wants immediate refresh as requested in #355

**Comment by octref** [comment] 2017-09-28 03:54
@HerringtonDarkholme I see, thanks for the info. So let's close it and track it in #355.

**Closed by octref** 2017-09-28 03:54 UTC
Labels: need-more-info
