### ISSUE TITLE
Update for <script setup> syntax

### ISSUE THREAD

**Issue by cimpok** [vuejs/vetur#3255] opened 2021-11-26 15:58 UTC
Vetur gives a false 
_'xxxx' is declared but its value is never read Vetur(6133)_ 
pop-up warning on import statements when the
components: { ... }  declatarion is missing, but the component is used in the template directly, which is an allowed shortcut in the new <script setup> syntax.

**Comment by jzymx50** [comment] 2021-12-02 13:29
Personally, I recommend disabling the validation provided by Vetur and turning to use `eslint` explicitly with `eslint-plugin-vue`. I haven't tried myself, but from its documentation your case is supported. https://eslint.vuejs.org/user-guide/#does-not-work-well-with-script-setup

**Comment by danb4r** [comment] 2022-01-23 21:33
For the moment, I had to switch to [Volar extension](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) on VSCode.

It is also worth to take a look at the [VueDX extension](https://marketplace.visualstudio.com/items?itemName=znck.vue-language-features).

Hope to turn back to Vetur straight away, as soon as it gets updated to support this new **script setup** syntax.

**Comment by yoyo930021** [comment] 2022-11-01 11:33
Duplicate of https://github.com/vuejs/vetur/issues/2296

**Closed by yoyo930021** 2022-11-01 11:33 UTC
