### ISSUE TITLE
I feel stupid - can't get autocomplete/intellisense to work inside template part of .vue (Typescript)

### ISSUE THREAD

**Issue by alexdpoon** [vuejs/vetur#1400] opened 2019-08-22 00:00 UTC
## Info

- Platform macOS
- Vetur version: 0.22.2
- VS Code version: 1.37.1

## Problem

Autocomplete and intellisense both work fine inside the <script lang="ts"> section of my .vue files, but not in the template section.  Is it supposed to work inside the <template> part as well?  The <script lang="ts"> part of my vue file uses vue-property-decorator.

**Comment by octref** [comment] 2019-08-22 15:26
Duplicate of #1105 and would be solved by #1323.

**Closed by octref** 2019-08-22 15:26 UTC
