### ISSUE TITLE
Typescript template intellisense not working

### ISSUE THREAD

**Issue by guyguy2001** [vuejs/vetur#1269] opened 2019-05-02 20:54 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur version: 0.19.3
- VS Code version: 1.33.1

## Problem

The template intellisense from #681 works for me in a normal javascript vue project, but it does not work on my typescript project.
Is it a problem with how my project is defined, did you miss it in the implementation, or did I miss the part where you said it isn't supported yet?
I saw in the PR that one person said that it worked with vue-class-component, but I don't know if it still works for him (as it was fairly early in the PR history),

![image](https://user-images.githubusercontent.com/6932278/57106329-be01e400-6d35-11e9-8066-f4031945e8ad.png)
![image](https://user-images.githubusercontent.com/6932278/57106347-c9550f80-6d35-11e9-8a21-c265ac8ba50c.png)

## Reproducible Case

Clone https://github.com/Microsoft/TypeScript-Vue-Starter and try to add {{name}} to the html.

**Comment by octref** [comment] 2019-05-02 20:59
Duplicate of https://github.com/vuejs/vetur/issues/1105.

**Closed by octref** 2019-05-02 20:59 UTC

**Comment by guyguy2001** [comment] 2019-05-02 21:05
Thanks for the fast response, and sorry for the duplicate; I mainly looked at the recent issues because I didn't realize it was a deeper issue than just a problem in #681, which is quite recent.

**Comment by octref** [comment] 2019-05-02 21:18
Yeah no worries, completion is a different path than #681 since #681's infrastructure mostly only supports valid virtual-compiled-from-template TS files.
