### ISSUE TITLE
The \"path\" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by bstaletic** [vuejs/vetur#1426] opened 2019-09-11 08:59 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Arch Linux for me, but a user of my client reported the issue on macOS
- Vetur version: Commit hash: f2c73f783bc8636f11d894cbe4ec684aff07dd52, but our user reported the problem after running `npm install --production` with this [`package.json`](https://github.com/ycm-core/lsp-examples/blob/master/vue/package.json)
- VS Code version: None, using YouCompleteMe in vim

## Problem

As soon as I start the server, I get, similarly to #1402, `The \"path\" argument must be of type string. Received type undefined`

## Reproducible Case

Currently not using any configuration of the server, but the same happened when I tried to use the default configuration from [here](https://github.com/vuejs/vetur/blob/master/package.json#L171).

The json exchange from my client's side looks like this:

```
2019-08-26 23:37:34,879 - DEBUG - TX: Sending message: b'Content-Length: 431\r\n\r\n{"id": "1", "jsonrpc": "2.0", "method": "initialize", "params": {"capabilities": {"textDocument": {"completion": {"completionItemKind": {"valueSet": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}}}, "initializationOptions": {}, "processId": 23433, "rootPath": "/Users/nbossard/OtherProjects/mahali/front/webapp", "rootUri": "file:///Users/nbossard/OtherProjects/mahali/front/webapp"}}'
2019-08-26 23:37:35,978 - DEBUG - RX: Received message: b'{"jsonrpc":"2.0","id":"1","error":{"code":-32603,"message":"Request initialize failed with message: The \\"path\\" argument must be of type string. Received type undefined"}}'
```

Our user issue report can be found here: https://github.com/ycm-core/lsp-examples/issues/7

**Comment by octref** [comment] 2019-09-30 02:30
Thanks for your detailed report. This should be fixed in latest release of VLS.

**Closed by octref** 2019-09-30 02:30 UTC

**Comment by douglasg14b** [comment] 2021-11-28 06:52
What is the cause of this error? I'm getting it in 2021,

**Comment by wokalek** [comment] 2022-03-24 09:57
Same

**Comment by oberemokis** [comment] 2024-01-19 00:04
Same 2024...
