### ISSUE TITLE
Template vuejs with backticks(es-6) saving wrong chars

### ISSUE THREAD

**Issue by joweste** [vuejs/vetur#2198] opened 2020-08-26 23:49 UTC
- [X ] I have searched through existing issues
- [X ] I have read through [docs](https://vuejs.github.io/vetur)
- [X ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows
- Vetur/VLS version:0.26.1
- VS Code (or other LSP client) version: 1.48.2

## Problem
There is a problem with backticks when formating documents.
When I format my vue js template  such as:
```
<template
              v-for="header in  
              headersModelosAtestados"
              v-slot: [`item.${header.value}`]="{ item }"
            >
```

It becomes:
```
<template
              v-for="header in  
              headersModelosAtestados"
              v-slot:
              [&#x60;item.${header.value}&#x60;]="{ item }"
            >

```

If I change the formatter to prettier, there is no problem.

**Comment by yoyo930021** [comment] 2020-08-28 03:50
Duplicate of #2000

**Closed** 2020-08-28 03:50 UTC
Labels: duplicate, upstream

**Comment by joweste** [comment] 2020-09-04 11:56
Yes, It´s a duplicate.
But I see no solution to this problem.
Is there some workaround?
