### ISSUE TITLE
No intellisense for imports

### ISSUE THREAD

**Issue by ajitid** [vuejs/vetur#822] opened 2018-06-15 17:12 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.12.5
- VS Code version: 1.24.1

## Problem

No Intellisense is provided in line `import {moduleName} from ''` when <kbd>ctrl</kbd> +<kbd>space</kbd>d between quotes and braces to get list of installed packages and exported modules respectively. This works fine in JS files.

**Comment by pumpkinlink** [comment] 2018-08-24 18:50
I think this is duplicate of #808

**Closed** 2019-05-10 22:31 UTC
Labels: integ:typescript, lsp:completion
