### ISSUE TITLE
VTI not compatible with Typescript 4.6.4.

### ISSUE THREAD

**Issue by kberg** [vuejs/vetur#3424] opened 2022-05-05 18:37 UTC
## Info

- Platform: Linux
- Vetur version: VTI v 0.1.3
- VS Code version: 1.66.2

## Problem

```
npx tsc -V
Version 4.6.4
```

Running `npx vti diagnostics`

```
File : .../src/client/components/Board.vue:1:1
Error: Cannot find name '__vlsComponentHelper'.
> 1 | <template>
    | ^
  2 |     <div :class="getGameBoardClassName()">
  3 |         <div class="hide-tile-button-container">
  4 |           <div class="hide-tile-button" @click="$emit('toggleHideTiles')" data-test="hide-tiles-button">
File : .../src/client/components/Board.vue:1:1
Error: 'this' implicitly has type 'any' because it does not have a type annotation.
> 1 | <template>
    | ^
  2 |     <div :class="getGameBoardClassName()">
  3 |         <div class="hide-tile-button-container">
  4 |           <div class="hide-tile-button" @click="$emit('toggleHideTiles')" data-test="hide-tiles-button">
```

This occurs with every  .vue file in the repo.

I was able to eliminate the issue by downgrading to Typescript 4.4.4.

## Reproducible Case

At the risk of having the issue closed, I probably won't generate the project given the guidance below, but I can endeavor to recreate it with my open source project if you like. (In the meantime I'm going to proceed with unbreaking my own build. ;))

**Comment by fuyunv** [comment] 2022-05-27 06:21
same problem, needs help.

**Comment by kraegpoeth** [comment] 2022-06-03 11:39
same problem on `"typescript": "<4.6.0",`

**Comment by yoyo930021** [comment] 2022-07-11 03:46
Duplicate of https://github.com/vuejs/vetur/issues/3323

**Closed by yoyo930021** 2022-07-11 03:46 UTC
