### ISSUE TITLE
Does not recognize advanced v-slot usage

### ISSUE THREAD

**Issue by hatboysam** [vuejs/vetur#2929] opened 2021-05-11 08:30 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows
- Vetur version: 0.33.1
- VS Code version: 1.55.2

## Problem

I am using the `vue-mention` library (https://github.com/Akryum/vue-mention) which uses this (admittedly funky) syntax:
```vue
        <template v-slot:item-@="{ item }">
          <div class="flex flex-row items-center pr-1">
            <Avatar :username="item.label" size="small" class="mr-2" />
            <span>{{ item.label }}</span>
          </div>
        </template>
```

The error I get is this:
![image](https://user-images.githubusercontent.com/997280/117784271-4d9ecf00-b23b-11eb-98f8-7b0702e7167f.png)

The way I got my error to go away is by adding a `v-slot:trickVetur`:
```vue
        <template v-slot:item-@="{ item }" v-slot:trickVetur="{ item }">
          <div class="flex flex-row items-center pr-1">
            <Avatar :username="item.label" size="small" class="mr-2" />
            <span>{{ item.label }}</span>
          </div>
        </template>
```

## Reproducible Case

I think the above is clear enough! Please let me know if not.

**Comment by yoyo930021** [comment] 2021-06-02 02:29
Duplicate of #1100

**Closed** 2021-06-02 02:29 UTC
Labels: duplicate
