### ISSUE TITLE
Rename (F2) doesn't work in .vue files.

### ISSUE THREAD

**Issue by bomzj** [vuejs/vetur#1511] opened 2019-11-21 07:42 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.6
- VS Code version: 1.40.1

## Problem
Renaming with F2 doesn't work in `.vue` files while it works fine in `.js`

![image](https://user-images.githubusercontent.com/2025775/69316922-da6e5b00-0c4a-11ea-89ba-231ff50d701a.png)

## Reproducible Case

1) Open any `.vue` file in VS Code.
2) Try to rename a variable with `F2`.
3) Rename doesn't show up.

**Comment by ktsn** [comment] 2019-11-22 02:34
Duplicate of #610

**Closed by ktsn** 2019-11-22 02:34 UTC
