### ISSUE TITLE
The component props types cannot be inferred

### ISSUE THREAD

**Issue by John60676** [vuejs/vetur#2229] opened 2020-09-04 02:03 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.27.0
- VS Code version: 1.48
- Vue version: 3.0.0-rc.10

## Problem

The component `props` types cannot be inferred

## Reproducible Case
create a new component and add a prop
```vue
<template>
  <div>{{ msg }}</div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({
  props: {
    msg: {
      type: String,
      required: false,
    }
  }
});
</script>
```
Then add a parent component, and then use the above component

```vue
<template>
  <div>
    <HelloWorld :msg="1" />
    {{data}}
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import HelloWorld from './components/HelloWorld.vue';

export default defineComponent({
  components: {
    HelloWorld
  }
});
</script>
```

The above example should prompt the types error, but in fact there is no

**Comment by octref** [comment] 2020-09-04 02:10
Duplicate of #1596. What's released is only existence checking, not type checking.

**Closed by octref** 2020-09-04 02:10 UTC
