### ISSUE TITLE
Upgrade Vscode 1.51.1. This extension makes CPU usage too high

### ISSUE THREAD

**Issue by Ztachi** [vuejs/vetur#2468] opened 2020-11-13 02:38 UTC
[Details about the situation](https://github.com/microsoft/vscode/issues/110448)

**Comment by Ztachi** [comment] 2020-11-13 03:16
I didn't install any more extensions
![image](https://user-images.githubusercontent.com/6995332/99024464-9d108500-25a1-11eb-82b7-3b03e000916e.png)
![image](https://user-images.githubusercontent.com/6995332/99024479-a863b080-25a1-11eb-9b03-0d85ceb38e0d.png)

**Comment by yoyo930021** [comment] 2020-11-13 03:35
1. Is this problem in VSCode old version?
2. What is message in Output panel for `Vue Language Server`?
3. Can you give me a tree diagram of your project filename?

**Comment by Ztachi** [comment] 2020-11-13 03:54
@yoyo930021 
1.The old version didn't pay attention, but the new version has this problem.
2、3.There are no problems with the project and the extension is working properly.But it kept on initializing and using a lot of CPU.
![Uploading image.png…]()

**Comment by yoyo930021** [comment] 2020-11-13 03:59
> @yoyo930021
> 1.The old version didn't pay attention, but the new version has this problem.
> 2、3.There are no problems with the project and the extension is working properly.But it kept on initializing and using a lot of CPU.
> ![image](https://user-images.githubusercontent.com/6995332/99026934-08108a80-25a7-11eb-84a6-5bef193f6c78.png)

Giving me information is a better way to determine this issue.
Is this problem in Vetur `v0.29.1`?

**Comment by Ztachi** [comment] 2020-11-13 04:02
@yoyo930021 
v0.30.1
vscode v1.51.1
![image](https://user-images.githubusercontent.com/6995332/99027371-05626500-25a8-11eb-895f-91bbc76c56d7.png)

**Comment by yoyo930021** [comment] 2020-11-13 04:06
> @yoyo930021
> v0.30.1
> vscode v1.51.1
> ![image](https://user-images.githubusercontent.com/6995332/99027371-05626500-25a8-11eb-895f-91bbc76c56d7.png)

Can you try to use old version extension?
https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#install-an-old-version-of-vetur
I need information for troubleshoot.

**Comment by yoyo930021** [comment] 2020-11-13 04:07
![截圖 2020-11-13 下午12 07 13](https://user-images.githubusercontent.com/9126398/99027705-c97bcf80-25a8-11eb-96b3-5deb640f29ca.png)
You also can use this method for old version extension.

**Comment by Ztachi** [comment] 2020-11-13 06:25
> ![截圖 2020-11-13 下午12 07 13](https://user-images.githubusercontent.com/9126398/99027705-c97bcf80-25a8-11eb-96b3-5deb640f29ca.png)
> You can also use this method for old version extension.
I installed V0.29.1 and it was able to complete the initialization normally.
I installed V0.30.0 again. I waited for five minutes and he was still initializing and using a lot of CPU.

**Comment by yoyo930021** [comment] 2020-11-13 06:28
> > ![截圖 2020-11-13 下午12 07 13](https://user-images.githubusercontent.com/9126398/99027705-c97bcf80-25a8-11eb-96b3-5deb640f29ca.png)
> > You can also use this method for old version extension.
> 
> I installed V0.29.1 and it was able to complete the initialization normally.
> I installed V0.30.0 again. I waited for five minutes and it was still initializing and using a lot of CPU.

If you use `pnpm` or symlink?

**Comment by yoyo930021** [comment] 2020-11-13 06:55
Can you give me a tree diagram of your project filename?

```bash
cd project
npx -p tree-cli treee -l 100 -f -o output.txt -d
```

**Comment by yoyo930021** [comment] 2020-11-13 07:05
You can decompress this file and install ext in vscode.
[vetur-0.30.1.vsix.zip](https://github.com/vuejs/vetur/files/5535234/vetur-0.30.1.vsix.zip)

1. Uninstall original extension.
2. ![截圖 2020-11-13 下午3 04 44](https://user-images.githubusercontent.com/9126398/99039054-972a9c00-25c1-11eb-831f-77160535d7bf.png)
3. install vsix

**Comment by Shinigami92** [comment] 2020-11-13 16:16
Don't know if it's related, but today I found this:

<img src="https://user-images.githubusercontent.com/7195563/99094087-a74b7700-25d3-11eb-8570-f4f053b02e5a.png" width="500px"/>

I closed all VSCode instances an hour ago... but then I found one of my 28 cores was constantly on 99% - 100%

**Comment by yoyo930021** [comment] 2020-11-13 16:41
> Don't know if it's related, but today I found this:
> 
> <img src="https://user-images.githubusercontent.com/7195563/99094087-a74b7700-25d3-11eb-8570-f4f053b02e5a.png" width="500px"/>
> 
> I closed all VSCode instances an hour ago... but then I found one of my 28 cores was constantly on 99% - 100%

Can you try to use it?
https://github.com/vuejs/vetur/issues/2468#issuecomment-726565206

**Comment by Shinigami92** [comment] 2020-11-13 17:08
Nope :-1: it's **not** working 😕
Still 99%-100%

I also have installed [Vuetify Pug snippet](https://marketplace.visualstudio.com/items?itemName=lucaslpsan.vuetify-pug-snippet) that depends on vetur

**Comment by yoyo930021** [comment] 2020-11-13 17:35
> Nope 👎 it's **not** working 😕
> Still 99%-100%
> 
> I also have installed [Vuetify Pug snippet](https://marketplace.visualstudio.com/items?itemName=lucaslpsan.vuetify-pug-snippet) that depends on vetur

I'm sorry about that.
[vetur-0.30.1.vsix.zip](https://github.com/vuejs/vetur/files/5538395/vetur-0.30.1.vsix.zip)
Can you try this?

If not, https://github.com/vuejs/vetur/issues/2468#issuecomment-726561376
and output panel in `Vue Language Server`.

**Comment by Shinigami92** [comment] 2020-11-13 17:52
Only occurs if I open a `.vue` file in `editor`-panel

![image](https://user-images.githubusercontent.com/7195563/99103461-e2ec3e00-25df-11eb-9a34-8c6d70767021.png)

https://pastebin.com/FRsNbYcD (_will explode after one week_ 😜)

**Comment by yoyo930021** [comment] 2020-11-13 18:21
@Shinigami92 https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

If you can follow the steps here, I'll thank you.
It's obviously not what I had in mind. =_=

**Comment by Shinigami92** [comment] 2020-11-13 18:27
Tomorrow

**Comment by Shinigami92** [comment] 2020-11-14 10:16
Hope I did anything correct
[CPU-20201114T111057.cpuprofile.zip](https://github.com/vuejs/vetur/files/5540477/CPU-20201114T111057.cpuprofile.zip)

**Comment by yoyo930021** [comment] 2020-11-16 06:14
I try to revert some change.
Can you try these two files for me?
[vsix.zip](https://github.com/vuejs/vetur/files/5544403/vsix.zip)

If it doesn't work, do it for me on one.
https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md

**Comment by Shinigami92** [comment] 2020-11-16 08:32
- full not working
- path not working

even after uninstalling the versions and closing vscode, I need to kill the process

I didn't installed `Vuetify Pug snippet` this time, so it's not a problem with that

Is it helpful to tell that my `.vue` files all look like this?:

```vue
<template lang="pug" src="./Filename.pug" />
<script lang="ts" src="./Filename.ts" />
```

When I uninstall the vetur plugin and open a vue file, the problem is not there. So it's definitely vetur

---

Do you think that a profile will help here? For me it's more a missing shutdown hook or destroy on close or something else
I'm currently just interested in the fix that it don't run anymore when I close vscode completely

**Comment by yoyo930021** [comment] 2020-11-16 08:42
>     * full not working
> 
>     * path not working
> 
> 
> even after uninstalling the versions and closing vscode, I need to kill the process
> 
> I didn't installed `Vuetify Pug snippet` this time, so it's not a problem with that
> 
> Is it helpful to tell that my `.vue` files all look like this?:
> 
> ```
> <template lang="pug" src="./Filename.pug" />
> <script lang="ts" src="./Filename.ts" />
> ```
> 
> When I uninstall the vetur plugin and open a vue file, the problem is not there. So it's definitely vetur
> 
> Do you think that a profile will help here? For me it's more a missing shutdown hook or destroy on close or something else
> I'm currently just interested in the fix that it don't run anymore when I close vscode completely

The profile can help me where's it stuck?
I need a specific function location for further action.
Or provide a repro project. https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md
Otherwise I'm really just guessing.

If you can provide a repro project, we'd appreciate it.

**Comment by yoyo930021** [comment] 2020-11-16 09:35
@Shinigami92 

I think I found your problem.
Can you try this vsix?
[vetur-0.30.1.vsix.zip](https://github.com/vuejs/vetur/files/5545353/vetur-0.30.1.vsix.zip)

**Comment by Shinigami92** [comment] 2020-11-16 09:37
I created an empty folder named `test`
There I created a `test.vue` file (file was empty)

The problem was not there

Then I copy-pasted
```vue
<template lang="pug" src="./Filename.pug" />
<script lang="ts" src="./Filename.ts" />
```

-> instant 99% core usage
-> the problem occured

IMO the problem has to do something with `lang="pug" src="./xy.pug"`

**Comment by yoyo930021** [comment] 2020-11-16 09:38
> I created an empty folder named `test`
> There I created a `test.vue` file (file was empty)
> 
> The problem was not there
> 
> Then I copy-pasted
> 
> ```
> <template lang="pug" src="./Filename.pug" />
> <script lang="ts" src="./Filename.ts" />
> ```
> 
> -> instant 99% core usage
> -> the problem occured
> 
> IMO the problem has to do something with `lang="pug" src="./xy.pug"`

Try this.
https://github.com/vuejs/vetur/issues/2468#issuecomment-727858642

**Comment by Shinigami92** [comment] 2020-11-16 09:40
https://github.com/vuejs/vetur/issues/2468#issuecomment-727858642 WORKING :tada:

**Comment by yoyo930021** [comment] 2020-11-16 09:42
> [#2468 (comment)](https://github.com/vuejs/vetur/issues/2468#issuecomment-727858642) WORKING 🎉

It's just a quick fix.
I need to study the context and provide a way to fix it.
Thanks for your work.

**Closed** 2020-11-16 10:19 UTC
Labels: bug
