### ISSUE TITLE
the vue language server server crashed 5 times in the last 3 minutes. the server will not be restart

### ISSUE THREAD

**Issue by Garfill** [vuejs/vetur#1229] opened 2019-04-24 16:39 UTC
It cannot work in win7 and the latest vscode, the version of vetur is 0.19.0

**Comment by ktsn** [comment] 2019-04-24 16:40
Probably duplicate of #1220

**Closed by ktsn** 2019-04-24 16:40 UTC

**Comment by honmaaax** [comment] 2019-05-06 06:48
I added this to Setting.json, then fix it.
```
"vetur.validation.template": false
```
