### ISSUE TITLE
Plugin not recognized on version 0.19.0

### ISSUE THREAD

**Issue by pdmshrestha** [vuejs/vetur#1231] opened 2019-04-24 18:01 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version:0.19.0
- VS Code version:1.33.1

## Problem
Suddenly after the plugin update plugins are not recognized on template.

<img width="1248" alt="Screenshot 2019-04-24 at 20 55 30" src="https://user-images.githubusercontent.com/2828010/56682304-efdecf00-66d3-11e9-89cb-ebbc61a03b48.png">

This happens to custom plugin too.

**Comment by octref** [comment] 2019-04-24 18:05
Repro case?

**Comment by pdmshrestha** [comment] 2019-04-24 18:15
@octref  As I said the error came right after the update. Earlier I didn't have any error. But the app complies without any issues. The plugin used in above earlier comment is https://kazupon.github.io/vue-i18n/started.html#javascript. Vetur doesn't recognize the plugin in template now. I have other vue plugins plugins which is not recognized in the template but compiles without any issues.

**Comment by pdmshrestha** [comment] 2019-04-24 18:20
Also the template doesn't recognize the custom attribute (hyphen separated) on components. For example `<v-container grid-list-md>` *grid-list-md* . is not recognized but `<v-container gridListMd>` is recognized.

<img width="928" alt="Screenshot 2019-04-24 at 21 20 21" src="https://user-images.githubusercontent.com/2828010/56683714-cb382680-66d6-11e9-9c11-43002c956adb.png">

And this happened after the plugin update.

**Comment by bennyty** [comment] 2019-04-24 20:07
![Screenshot_2019-04-24 16 06 25_5JIEvp](https://user-images.githubusercontent.com/592150/56690234-f9077600-66aa-11e9-8a4b-3f7b9ade6361.png)
I'm seeing Vetur errors after updating to 0.19.0 as well.

**Comment by colinbes** [comment] 2019-04-24 21:26
Also seeing similar errors as noted above with 0.19.0
I also get error message stating that due file is not a module `File '/.../recipe-manager.client/src/App.vue' is not a module.`. Adding lang="html" to template tag seems to have corrected the issue which should not be required.

**Failing**
```
<template>
<div>
  <label>{{title}}</label>
    <input-tag v-model="categoryList"></input-tag>
</div>
</template>
```

**Passing**
```
<template lang="html">
<div>
  <label>{{title}}</label>
    <input-tag v-model="categoryList"></input-tag>
</div>
</template>
```

**Comment by octref** [comment] 2019-04-24 21:44
Same root cause as https://github.com/vuejs/vetur/issues/1226, vue-i18n doesn't have a way to bind more properties to `this` instance.

Your second issue should be fixed.

**Comment by octref** [comment] 2019-04-24 21:45
@colinbes Can you create a new issue and not add to an unrelated issue? If you don't have any `<script>` region with `export default {}` that error will be reported.

**Comment by colinbes** [comment] 2019-04-24 22:34
@octref I added it to this issue as I was seeing similar error messages and adding the lang to template remove the error messages. I will create new issue.

**Comment by octref** [comment] 2019-04-26 03:24
I'll track it in #1226.

**Closed by octref** 2019-04-26 03:24 UTC
Labels: upstream
