### ISSUE TITLE
Test failure does not trigger CI failure

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/vetur#2138] opened 2020-08-08 08:17 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Any
- Vetur version: master
- VS Code version: 1.47.3

## Problem

https://github.com/vuejs/vetur/runs/961144612#step:10:610

## Reproducible Case

In master branch.

**Comment by octref** [comment] 2020-08-08 08:22
Thanks for catching it. Caused by my change in https://github.com/vuejs/vetur/commit/03e3f7d7e361cea6ce58e76838ccab302615c88e

**Comment by octref** [comment] 2020-08-08 08:30
Fixed via e0be39108a826fb137dc6e63369f13a7960a9de2. https://github.com/vuejs/vetur/runs/961205618 should fail.

**Closed** 2020-08-08 08:30 UTC
Labels: bug, infrastructure
