### ISSUE TITLE
Go to definition from template not work in 0.28.0

### ISSUE THREAD

**Issue by tuan-lm** [vuejs/vetur#2341] opened 2020-09-28 10:13 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Window 10 Pro
- Vetur version: **0.28.0**
- VS Code version: 1.49.2

## Problem

**Go to definition** from **template** not working when update to vetur **0.28.0**.
Work just fine when downgrade to 0.27.3

## Reproducible Case
In VS Code with vetur 0.28.0, hover any variable or function, Ctrl + click won't go to definition, instead show this error in the bottom right in vscode window

![Capture](https://user-images.githubusercontent.com/67671276/94419918-970b4400-01ad-11eb-9eae-24f514206497.PNG)

_Temporary solution_: Downgrade vetur back to 0.27.3

**Comment by yoyo930021** [comment] 2020-09-28 13:57
Please provide a reproducible project.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by SD-Gaming** [comment] 2020-09-29 02:39
same problem.

**Comment by benrwb** [comment] 2020-10-13 07:50
I'm having the same problem (using Vetur 0.28.0 on Windows 10).

When I click "Go to definition", Visual Studio closes the file I am working on, and displays a message "unable to open 'file.vue': Unable to resolve resource (path)"
I noticed that the path contains forward slashes (e.g. `c:/path/to/file`) instead of the usual convention on Windows of using backslashes (`c:\path\to\file`). I don't know if that's significant.

I think this might be the same problem as issue #1484, which was fixed in #2161 
I believe it was caused by path handling inconsistencies between Windows and Mac/Linux.
#2161 updated `server/src/modes/template/interpolationMode.ts`, by wrapping 2 uri's in `URI.file` 

I have just checked the latest version of `interpolationMode.ts`, and the calls to  `URI.file`  have been removed, which could explain why the problem has resurfaced.

**Comment by ghostlhq** [comment] 2020-10-30 04:43
![image](https://user-images.githubusercontent.com/28859710/97658555-81888300-1aa7-11eb-9286-e68aaff849cc.png)
Got the same problem when I was learning the VUE.
The image above is when I using the  TypeScript language, and here's the JavaScript version
![image](https://user-images.githubusercontent.com/28859710/97660506-be0aad80-1aac-11eb-9b65-b0e0efed97aa.png)
In ts I can get the suggestion in template, but I can't use go to the definition in the <script>, it can only shows the 'any' as prop;
In js I can use the go to the definition in <scrip>, but I can't get any suggestion in <template;
Amazing!

**Comment by octref** [comment] 2020-10-30 12:42
@benrwb It's due to me being sloppy with git, probably what happened was I did a merge of an old PR, resolved the 3-way diff but didn't catch the `URI.file` call. I'll make sure to always rebase first...

**Closed** 2020-10-30 12:42 UTC
Labels: bug, lsp:definition, no-repro-case, template-interpolation
