### ISSUE TITLE
not export the default value in <setup>, the import will report an error

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/vetur#2472] opened 2020-11-16 06:40 UTC
## HelloWorld.vue
~~~html
<script setup="props" lang="ts">
import { computed, ref, watchEffect } from "vue";
declare const props: {
  msg: string;
};
export const count = ref(0);
export const computedMsg = computed(() => props.msg + "!!!!");
watchEffect(() => {
  console.log(computedMsg.value);
});
</script>
~~~
## App.vue
~~~html
<script lang="ts">
import { defineComponent } from "vue";
// error: Module ....../HelloWorld.vue has no default export.
import HelloWorld from "@/components/HelloWorld.vue";

export default defineComponent({
  name: "Home",
  components: {
    HelloWorld
  }
});
</script>
~~~

**Comment by yoyo930021** [comment] 2020-11-16 06:51
Duplicate of #2296

**Closed by yoyo930021** 2020-11-16 06:51 UTC
Labels: duplicate
