### ISSUE TITLE
vs code syntax highlighting in vue files

### ISSUE THREAD

**Issue by Erwin-Feld** [vuejs/vetur#2793] opened 2021-03-19 15:04 UTC
in vs code color settings for javascript syntax highlighting using `Vetur` is only partially applied to javascript code in `.vue` files.
<br>
using `Inspect Editor Tokens and scopes`
the description also differs 

![vue](https://user-images.githubusercontent.com/80193235/111800881-af425d00-88cc-11eb-9d74-ea69502969b3.png)
![jsfile](https://user-images.githubusercontent.com/80193235/111800891-b10c2080-88cc-11eb-8034-8a37819a40fc.png)

is there a way to apply the color settings in `.js` files one to one to `.vue`files ?

**Comment by octref** [comment] 2021-04-01 15:27
Duplicate of #2687. Vetur does not support semantic highlighting yet.

**Closed by octref** 2021-04-01 15:27 UTC
Labels: grammar, question
