### ISSUE TITLE
If you do not export default it in <setup>, the import will report an error

### ISSUE THREAD

**Issue by TuiMao233** [vuejs/vetur#2473] opened 2020-11-16 07:02 UTC
## HelloWorld.vue

~~~html
<script setup="props" lang="ts">
import { computed, ref, watchEffect } from 'vue'
declare const props: {
  msg: string
}
export const count = ref(0);
export const computedMsg = computed(()=> props.msg + "!!!!")
watchEffect(()=>{
  console.log(computedMsg.value)
})

export default {}
</script>
~~~

## App.vue

~~~html
<script setup lang="ts">
// Module '"./components/HelloWorld.vue"' has no exported member 'default'.Vetur(2305)
export { default as HelloWorld } from './components/HelloWorld.vue';
</script>
~~~

**Comment by yoyo930021** [comment] 2020-11-16 07:03
Duplicate of #2296

**Closed by yoyo930021** 2020-11-16 07:03 UTC

**Comment by yoyo930021** [comment] 2020-11-16 07:04
Please don't open new issue.
No support yet.
