### ISSUE TITLE
Property 'zxzzxxz' does not exist on type 'CombinedVueInstance

### ISSUE THREAD

**Issue by Pedroprt** [vuejs/vetur#2160] opened 2020-08-14 01:24 UTC
- [ x] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:
- VS Code version: 1.48.0

## Problem

Property 'all properties, variables, etc' does not exist on type 'CombinedVueInstance

## Reproducible Case

all my project files were with red underlines, reporting error 2339

I found in .vscode folder a file settings.json

{
  "vetur.validation.template": false,
  
  "eslint.validate": ["javascript", "javascriptreact", "typescript", "vue"],
  
  "vetur.experimental.templateInterpolationService": true
}

changed to :

{
  "vetur.validation.template": false,
  
  "eslint.validate": ["javascript", "javascriptreact", "typescript", "vue"],
  
  "vetur.experimental.templateInterpolationService": false
}

and the error stopped

I never added that line.
Other projects withou thar folder and files (.vscode/settings.json) didn't report any problems

**Comment by yoyo930021** [comment] 2020-08-14 02:18
Duplicate of #2131

**Closed by yoyo930021** 2020-08-14 02:18 UTC
