### ISSUE TITLE
No default export while using setup sugar

### ISSUE THREAD

**Issue by wiketool** [vuejs/vetur#3116] opened 2021-08-17 17:51 UTC
- [x] I have searched through existing issues
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 10 Professional Edition 20H2 x64
- Vetur version:v0.34.1
- VS Code version:1.59.0
- Node.js version:14.16.0

## Problem

I used `setup sugar` in my code,then `Vetur` report error `Module xxx has no default export`

## Reproducible Case

**HelloWorld.vue**
```javascript
...
<script lang="ts" setup>
import { ref } from 'vue'

defineProps({
  msg: {
    type: String,
    required: true,
  },
})

const count = ref(0)
</script>
...
```

**Home.vue**
```javascript
...
<script lang="ts">
...

/*The following line is where error report*/
import HelloWorld from '@/components/HelloWorld.vue' 

...
</script>
...
```

**Comment by coderlfm** [comment] 2021-08-21 01:47
I had the same problem

**Comment by nevermore1000** [comment] 2021-09-01 03:06
I had the same problem

**Comment by nopeless** [comment] 2021-09-04 08:40
same problem here as well

**Comment by ZangYuSong** [comment] 2021-09-05 04:59
I had the same problem

**Comment by yoyo930021** [comment] 2021-10-04 12:45
Duplicate of #2296

**Closed by yoyo930021** 2021-10-04 12:45 UTC
Labels: duplicate
