### ISSUE TITLE
[0.6.10] Vue Language Server failed to start.

### ISSUE THREAD

**Issue by Moerj** [vuejs/vetur#212] opened 2017-05-22 01:29 UTC
![qq20170522-092550](https://cloud.githubusercontent.com/assets/13795438/26289255/10ffb122-3ed1-11e7-84b4-b5c509c1f966.jpg)

Open a vue project. It can not start vue language server.

**Comment by Moerj** [comment] 2017-05-22 03:00
Now I can't to work. Can you give me a 0.6.9 version ?

**Comment by ppasieka** [comment] 2017-05-22 05:47
https://github.com/octref/vetur/files/1004595/vetur-0.6.9.vsix.zip

**Comment by Moerj** [comment] 2017-05-22 06:47
Thanks @ppasieka

**Comment by Moerj** [comment] 2017-05-22 07:34
![qq20170522-153147](https://cloud.githubusercontent.com/assets/13795438/26297042/d724e9f8-3f03-11e7-94e8-a089f74fcc5d.jpg)

Unfortunately. 0.6.9 has the same problem 😔

**Comment by octref** [comment] 2017-05-29 16:39
Do you have a repro case that you could share with me?

It seems TS gets a lot of such reports: https://github.com/Microsoft/TypeScript/search?q=rangeerror+maximum&type=Issues&utf8=%E2%9C%93
So it's probably a TS error in resolving your project's dependency.

**Comment by Moerj** [comment] 2017-05-30 08:08
https://github.com/Moerj/GOPIGGY

When I have Chinese Files Name. This problem will be come. I'm not sure

**Comment by octref** [comment] 2017-06-03 23:35
It's not crashing for me...
Are you using cnpm for this one too?

**Comment by Moerj** [comment] 2017-06-04 18:32
![qq20170605-022920 2x](https://cloud.githubusercontent.com/assets/13795438/26764316/2eb8f112-4997-11e7-8f7b-cac6e4297d77.jpg)


@octref Yes. But I try to remove cnpm node_modules. And use npm install again. The problem is still

**Comment by Moerj** [comment] 2017-06-11 18:14
@octref Are you find the way to fix the bug? The current version it often crashes. ☹️

**Comment by octref** [comment] 2017-06-11 22:28
I can't repro the bug with https://github.com/Moerj/GOPIGGY no matter how I try, so there isn't anything I can do yet. 

Meanwhile, give it a try building the project and run it in debug mode (F5 with target `all`), and tick all exceptions
![image](https://user-images.githubusercontent.com/4033249/27015070-5950a4a2-4f0e-11e7-80d8-13c459cf6431.png) to see the stack trace of the error.

**Comment by BruceLpc** [comment] 2017-07-10 01:47
这个问题解决了吗？

**Comment by Moerj** [comment] 2017-07-10 10:58
@BruceLpc https://github.com/vuejs/vetur/issues/268

**Comment by BruceLpc** [comment] 2017-07-10 11:18
#321 哥们帮忙看下这个问题 怎么解决的，我英文不好

**Comment by Moerj** [comment] 2017-07-10 14:14
里面并没有解决, 我尝试修改的jsconfig也只是让它不报错了,但是相应的所有this.提示都没有了

**Comment by iamdevlinph** [comment] 2017-07-10 16:41
I will just add my issue here rather than opening another one.

`Error: ENOENT: no such file or directory, lstat 'f:\collective-front\node_modules\vue-slider-component\src\vue2-slider.vue.ts'
    at fs.lstatSync (fs.js:902:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:244:16)
    at Object.realpathSync (fs.js:1542:21)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:321:29)
    at Object.realpath (C:\Users\devli\.vscode\extensions\octref.vetur-0.9.0\client\node_modules\vue-language-server\node_modules\typescript\lib\typescript.js:3989:32)
    at realpath (C:\Users\devli\.vscode\extensions\octref.vetur-0.9.0\client\node_modules\vue-language-server\node_modules\typescript\lib\typescript.js:26373:42)
    at tryResolve (C:\Users\devli\.vscode\extensions\octref.vetur-0.9.0\client\node_modules\vue-language-server\node_modules\typescript\lib\typescript.js:26360:87)
    at nodeModuleNameResolverWorker (C:\Users\devli\.vscode\extensions\octref.vetur-0.9.0\client\node_modules\vue-language-server\node_modules\typescript\lib\typescript.js:26342:68)
    at nodeModuleNameResolver (C:\Users\devli\.vscode\extensions\octref.vetur-0.9.0\client\node_modules\vue-language-server\node_modules\typescript\lib\typescript.js:26321:16)
    at Object.resolveModuleName (C:\Users\devli\.vscode\extensions\octref.vetur-0.9.0\client\node_modules\vue-language-server\node_modules\typescript\lib\typescript.js:26110:30)
[Error - 12:38:26 AM] Connection to server got closed. Server will not be restarted.`

And in my `jsconfig.json`
```json
{
    "include": [
        "*.vue"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by iamdevlinph** [comment] 2017-07-11 08:23
I don't know if it's the plugin looking for this file. But we're just using vanilla JS in our project.

**Comment by iamdevlinph** [comment] 2017-07-11 08:41
Just check the [code of the plugin](https://github.com/NightCatSama/vue-slider-component/tree/master/src) there doesn't seem to be any call to a  `.ts` file

**Comment by wangliverpool** [comment] 2017-07-12 04:02
Same problem. I have checked all paths and find nothing in Chinese. This issue occurred since I updated Vetur to 0.9.0, before when it worked great. So I wonder if the problem is caused by the new version.

**Comment by iamdevlinph** [comment] 2017-07-12 06:46
I tried the `npm install`. Didn't work on my end.

**Comment by octref** [comment] 2017-07-12 06:49
@iamdevlinph Your issue is #321, is fixed, and will be published in the next version.

**Closed by octref** 2017-07-12 06:49 UTC
Labels: need-more-info
