### ISSUE TITLE
Maybe some conflict whthin vetur format and eslint(recommit,add some picture and setting)

### ISSUE THREAD

**Issue by L-Devil-GitHub** [vuejs/vetur#994] opened 2018-11-27 13:04 UTC
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: last
- VS Code version: last

## Problem

maybe some conflict between vetur format and eslint.
l can only provide some picture and my vscode setting.
if its my mistake of eslint config.please tell.
the rate of the problem happen is very low, may exist before the last update

## Reproducible Case
thats the vscode formatted and eslint error
![image](https://user-images.githubusercontent.com/26218200/49083184-dc474d80-f286-11e8-86f2-d1e50d54456d.png)

![image](https://user-images.githubusercontent.com/26218200/49083190-e5381f00-f286-11e8-9161-711a12672005.png)

and the follow picture is the format which may eslint want

![image](https://user-images.githubusercontent.com/26218200/49083318-31835f00-f287-11e8-9277-a4d0369d5d9f.png)

and follow is my setting 

~~~ json
{
    "editor.renderWhitespace": "all",
    "editor.detectIndentation": false,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "html.format.endWithNewline": true,
    "html.format.indentInnerHtml": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": true,
    "window.zoomLevel": 0,
    "team.showWelcomeMessage": false,
    "workbench.activityBar.visible": true,
    "workbench.statusBar.visible": true,
    "workbench.editor.showTabs": true,
    "window.menuBarVisibility": "default",
    "git.autofetch": true,
    "prettier.semi": true,
    "prettier.singleQuote": true,
    "prettier.trailingComma": "all",
    "prettier.tabWidth": 4,
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "vue"
    ],
    "gitlens.keymap": "alternate",
    "gitlens.gitExplorer.files.layout": "tree",
    "gitlens.advanced.messages": {
        "suppressCommitHasNoPreviousCommitWarning": false,
        "suppressCommitNotFoundWarning": false,
        "suppressFileNotUnderSourceControlWarning": false,
        "suppressGitVersionWarning": false,
        "suppressLineUncommittedWarning": false,
        "suppressNoRepositoryWarning": false,
        "suppressResultsExplorerNotice": false,
        "suppressShowKeyBindingsNotice": true
    },
    "gitlens.historyExplorer.enabled": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "vetur.format.defaultFormatter.html": "prettyhtml",
    "vetur.format.options.tabSize": 4,
    "vetur.format.defaultFormatterOptions": {
        "prettyhtml": {
            "wrapAttributes": true,
            "sortAttributes": true,
        },
        "prettier": {
            "semi": true,
            "singleQuote": true,
            "trailingComma": "all",
            "tabWidth": 4,
        }
    }
}
~~~

and my .prettierrc

~~~ .prettierrc
{
    "semi": true,
    "singleQuote": true,
    "trailingComma": "all",
    "tabWidth": 4
}
~~~

**Comment by patrickcate** [comment] 2018-11-28 03:07
If it's the same issue, I've ran into this today as well. I haven't noticed it with <script> js, but it's happening in <template> code like crazy. Every time I save it seems like eslint is trying to fix a formatting issue, but creates one at the same time.

![eslint-vue](https://user-images.githubusercontent.com/6277206/49126122-7d86d180-f290-11e8-8b3b-4536f466dc65.gif)

It's happening on both a vue cli 3 project w/ the prettier/eslint config, as well as with Nuxt (2.0 if it matters) made w/ create nuxt app.

**Comment by octref** [comment] 2018-11-28 07:06
@patrickcate @L-Devil-GitHub  Can you provide a sample project where I can repro this. You can either fork https://github.com/octref/veturpack or use vue cli.

**Comment by francoisromain** [comment] 2018-11-28 13:43
same problem after updating from `@vue/cli-plugin-eslint": "^3.1.5"` to `"^3.2.0"`

**Comment by francoisromain** [comment] 2018-11-28 15:02
repro: https://github.com/francoisromain/vetur-eslint-bug 

and my (relevant) VS Code user settings: 

```
{
  "eslint.enable": true,
  "eslint.autoFixOnSave": true,
  "eslint.validate": [
    {
      "language": "vue",
      "autoFix": true
    },
    {
      "language": "html",
      "autoFix": true
    },
    {
      "language": "javascript",
      "autoFix": true
    }
  ],
  "emmet.triggerExpansionOnTab": true,
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
  "javascript.implicitProjectConfig.checkJs": true,
  "prettier.semi": false,
  "prettier.eslintIntegration": true,
  "prettier.singleQuote": true,
  "typescript.npm": "/usr/local/bin/npm",
  "vetur.format.defaultFormatter.js": "vscode-typescript"
}
```

**Comment by octref** [comment] 2018-11-29 08:07
@francoisromain The problem is:

- Prettyhtml does not put space before `/>`: `<HelloWorld msg="Welcome to Your Vue.js App"/>`
- `eslint-plugin-vue` wants a space before `/>` and actually have a autofix for it
- They cannot agree on a format.

@patrickcate You have the same problem.

There is no way prettyhtml and eslint-plugin-vue could work together well now. You can workaround now by:

- Remove `"eslint.autoFixOnSave": true` and turn off `vetur.validation.template`
- Disable prettyhtml formatting by `"vetur.format.defaultFormatter.html": "none"`

@StarpTech What do you think is a good solution? Having something like `prettyhtml-eslint` that runs `prettyhtml` and then `eslint`?

**Comment by francoisromain** [comment] 2018-11-29 08:12
@octref Thank you. `"vetur.format.defaultFormatter.html": "none"` fixed the problem.

**Comment by L-Devil-GitHub** [comment] 2018-11-29 08:20
@octref i can paste you part of my .vue file.  maybie you can repro this by it and my config upside.


thats part of my .vue
<template>
    <div></div>
</template>
<script>
export default {
    name: '',
    data() {
        return {};
    },
    props: {},
    methods: {},
    computed: {
        aggregatorNames() {
            return this.aggregationFieldSelected
                ? this.selectedAggreationField.getOption(
                      'groupAggregations',
                      [],
                  )
                : [];
        },
    },
};
</script>

<style lang="scss">
</style>

**Comment by StarpTech** [comment] 2018-11-29 08:21
I won't change that rule in the formatter. This should be an option in the eslint package. Try to explain that urgent issue to the maintainer of the eslint package.

Therefore I can't see that this rule belongs to a official styleguide its the opposite. On the official vue styleguide all self-closing elements has no space in between.

**Comment by RiFi2k** [comment] 2018-12-11 00:37
I decided to share my fully working configs which took me months of trial and error, these are the base of a few live sites which get worked on by multiple people on multiple environments daily.
https://github.com/RiFi2k/vscode-vue-vetur-eslint-prettier-airbnb

This will get you vscode, vue, eslint, prettier, airbnb working with latest versions on everything. Tweak from here to do whatever you want.

**Comment by octref** [comment] 2018-12-12 18:32
I have provided workarounds for all cases in https://github.com/vuejs/vetur/issues/994#issuecomment-442742315.

@RiFi2k Would be great if you can open an issue in https://github.com/octref/veturpack and tell me issues you run into. I want to reduce config friction too.

**Closed by octref** 2018-12-12 18:32 UTC
Labels: need-more-info

**Comment by RiFi2k** [comment] 2018-12-12 20:40
@octref I actually didn't know you had that repo, I'll for sure share all my findings.

**Comment by L-Devil-GitHub** [comment] 2018-12-13 01:08
@RiFi2k Thanks for your share, i will try it soon after,
