### ISSUE TITLE
No Intellisense JSDoc @param in .vue files for vuejs plugin. (JSDoc come from d.ts file)

### ISSUE THREAD

**Issue by deguich** [vuejs/vetur#1870] opened 2020-04-24 14:50 UTC
## Info

- Platform: Win10
- Vetur version: 0.24.0
- VS Code version: 1.44.2

## Problem

In .vue file component, JSDoc is uncomplete. 
There is no Intellisense JSDoc @param, @returned @xxx in .vue files.

## Reproducible Case

I create a project from scratch :
```shell
yarn init -y
yarn add vue
```

For testing purpose, I add an index.d.ts file at project root :
```typescript
import Vue from 'vue' ;

declare module 'vue/types/vue' {
    interface Vue {
      /**
       * **Plugin property**
       * 
       * Principal plugin function
       * 
       * @param {number} param1 - Parameter 1
       * @returns {string} Return test
       */
      $myPlugin: (param1: number) => string;
    }
  }
```

I add a _tsconfig.json_ file at project root :
```javascript
{
  "include": [
    "./index.d.ts"
  ]
}
```

I add a .vue file _App.vue_ :
```javascript
<script>
export default {
  methods: {
    test() {
      this.$my;
    }
  }
};
</script>
```

And this is the intellisense doc :
![nok](https://user-images.githubusercontent.com/7642281/80224004-65fc7580-8649-11ea-904e-ca18c66e464c.jpg)

What I waiting for :
![ok](https://user-images.githubusercontent.com/7642281/80224038-73b1fb00-8649-11ea-8f71-993a8cf4694c.jpg)

**Comment by sapphi-red** [comment] 2020-08-30 10:57
I think this issue has been fixed by this commit. (https://github.com/vuejs/vetur/commit/e21fe22a8abf20fafea3603ec3fb593a1bf68103)
![image](https://user-images.githubusercontent.com/49056869/91657317-03d1e680-eafb-11ea-8cdb-582a79088000.png)

**Comment by octref** [comment] 2020-09-03 07:00
Thanks @sapphi-red. Duplicate of #2193 which is fixed already.

**Closed by octref** 2020-09-03 07:00 UTC
Labels: duplicate
