### ISSUE TITLE
Vetur Keeps loading in my Vue 2 project

### ISSUE THREAD

**Issue by BroJenuel** [vuejs/vetur#3658] opened 2023-02-23 02:35 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Windows 11
- Vetur version: 0.37.0
- VS Code version: 1.75.1
- TypeScript version: not using
- Vetur output:
![image](https://user-images.githubusercontent.com/31676163/220809031-bf6126ba-768a-4c27-b006-5bf897c91d79.png)
Vetur has been loading, and it does not stop.

**Comment by yoyo930021** [comment] 2023-02-23 05:29
Duplicate of #3657 and fix in v0.37.3

**Closed by yoyo930021** 2023-02-23 05:29 UTC
Labels: duplicate
