### ISSUE TITLE
Not working with multifile components

### ISSUE THREAD

**Issue by pabloleone** [vuejs/vetur#3121] opened 2021-08-20 09:26 UTC
The problem is quite simple, all Vetur features do not work in multifile Vue components using Typescript.

![Screenshot 2021-08-20 at 11 26 30](https://user-images.githubusercontent.com/2090437/130212284-e4b5da66-4ab2-4cc7-8f2a-d90d24b9e00b.png)

That file structure isn't supported.

**Comment by askeet** [comment] 2021-08-20 15:44
Related this ticket https://github.com/vuejs/vetur/issues/3118 also

**Comment by yoyo930021** [comment] 2021-10-04 11:06
Duplicate of #2471

**Closed** 2022-11-01 11:39 UTC
Labels: duplicate
