### ISSUE TITLE
Dynamic relative import not found

### ISSUE THREAD

**Issue by Jack85** [vuejs/vetur#1302] opened 2019-05-20 09:23 UTC
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version:0.21
- VS Code version:1.33.1
vue: 2.6.8

## Problem
module not found, although registered in tsconfig properly
```
 "paths": {
      "@/*": ["src/*"],
      "ext1": ["ext1"]
    },
```

## Reproducible Case
![image](https://user-images.githubusercontent.com/16955647/58010824-5992a300-7af1-11e9-94db-8efa0d18be48.png)

similar with normal import
![image](https://user-images.githubusercontent.com/16955647/58011196-0a00a700-7af2-11e9-8c59-e9cb30bdb55d.png)

**Comment by octref** [comment] 2019-05-23 06:18
Duplicate of #762.

**Closed by octref** 2019-05-23 06:18 UTC
