### ISSUE TITLE
Vetur Prettier ignores ESLint rules with prettier.eslintIntegration set to true

### ISSUE THREAD

**Issue by SeanGroff** [vuejs/vetur#695] opened 2018-02-18 07:44 UTC
- [x ] I have searched through existing issues
- [ x] I have read through [docs](https://vuejs.github.io/vetur)
- [ x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.11.7
- VS Code version: 1.20.1

## Problem

Vetur's version of prettier does not respect my ESLint rules even though I have `prettier.eslintIntegration` set to `true`.

 Cannot get `.vue` files to format according to `eslintrc.js`. .js files format without issue.
This causes a problem when using vue-cli and the Standard ESLint rules.

**Comment by kleinfreund** [comment] 2018-02-21 13:09
This did work as intended before. Was some default changed? I spent half an hour chasing this down.

**Comment by octref** [comment] 2018-03-06 22:12
Which rule? Also please include a repro case (or repository) and screenshot.

**Comment by KennyWho** [comment] 2018-03-09 07:26
rules: _space-before-fucntion-paren_
I use prettier-eslint instead of prettier.when it use in _.js_ file, it's right,but in _.vue_ file, it can't match the rules.

**Comment by iulo** [comment] 2018-03-17 03:09
same issue. Any update?

**Comment by stolfgang** [comment] 2018-03-18 13:40
prettier.eslintIntegration stops working if I install and activate eslint-config-standard (https://github.com/standard/eslint-config-standard).
To reproduce clone veturpack repro, run
`npm install --save-dev eslint-config-standard eslint-plugin-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node`
and add "standard" to .eslintrc

Afterwards it ignores eslint settings, but works well on javascript files.

**Comment by shangxinbo** [comment] 2018-03-21 04:48
I got the same problem. And the vscode show me Unknown configuration setting for "prettier.eslintIntegration". What's up?Because of that, I should config prettier in config.json and both in eslintrc.js

**Comment by orblazer** [comment] 2018-03-23 15:01
Hello, i have the same problem but me the HTML not want format the HTML and i can't change pretty rules.

My config : https://gist.github.com/orblazer/df1983339bfee462b8f15bfae9656ac3

Thanks.

**Comment by syropian** [comment] 2018-03-30 14:57
I'm running into this exact issue as well. I'm using:
```
...
extends: ['standard', 'plugin:vue/essential'],
...
```

in my `.eslintrc.js` config, and have `"prettier.eslintIntegration": true` in my editor, but reformatting my `.vue` files still strips the space between my function name and the the parentheses (which causes ESLint to complain).

**Comment by maarteNNNN** [comment] 2018-03-30 23:38
This is on purpose prettier doesn't like spaces in front of the parenteses.
There's an issue (GitHub) on this in prettier where they made this clear
they'll will never implement the option because it goes against their way
of JavaScript standard.

**Comment by syropian** [comment] 2018-03-31 00:59
Yes but with eslint integration set to true it’s supposed to respect my eslint config, instead of using prettier.

**Comment by YogliB** [comment] 2018-05-11 12:49
I'm using VS Code with the Vetur (0.11.7 | 2018-01-28), ESLint (1.4.8) and Prettier (1.3.1) extensions,
and I've managed to fix this with these User Settings:
```
{
    // eslint settings
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        {
            "language": "vue",
            "autoFix": true
        }
    ],
    "eslint.autoFixOnSave": true,
    // Vetur settings
    "vetur.format.defaultFormatter.js": "none"
}
```

**Comment by ZyqGitHub1** [comment] 2018-05-18 04:47
I install vetur0.12.3 and Prettier - Code formatter1.3.1,I have prettier.eslintIntegration set to true.when I format document with vscode command Format Document in .vue file,eslint rule 'brace-style': ['error', 'stroustrup'] can't match. but in .js file, it works well.

**Comment by AustinFelipe** [comment] 2018-05-30 17:19
Same problem here.

**Comment by AlvinYuXT** [comment] 2018-06-05 02:33
I have the same problem when using prettier-vscode plugin. My solution is to add `eslintIntegration: true` to a `.prettierrc` file and remove `"prettier.eslintIntegration": true` in `user settings` file

**Comment by iamswain25** [comment] 2018-10-08 23:56
This still hasn't been fixed under 0.13.0
when "prettier.eslintIntegration": true in my setting.json
it only formats js file, not the javascripts in vue file
but it formats html and css in vue file though

**Comment by gilesbutler** [comment] 2018-10-10 02:47
I'm getting the same problem as @iamswain25 too

**Comment by Bartozzz** [comment] 2018-10-10 17:13
cc @iamswain25 @gilesbutler 

I had the same issue. I was using ESLint & Prettier to format my code but it was only formatting code between `<template>` and `<style>` tags – not `<script>`'s. The following configuration should solve this issue:

- **VSCode config:**

```json
{
  "editor.formatOnSave": true,

  "vetur.validation.template": false,
  "vetur.format.defaultFormatter.scss": "prettier",
  "vetur.format.defaultFormatter.css": "prettier",
  "vetur.format.defaultFormatter.js": "prettier",

  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": [],

  "eslint.autoFixOnSave": true,
  "eslint.alwaysShowStatus": true,
  "eslint.options": { "extensions": [".html", ".js", ".vue", ".jsx"] },
  "eslint.validate": [
     "javascript",
     "javascriptreact",
     {
       "language": "vue",
       "autoFix": true
     }
  ],

  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,

  "javascript.validate.enable": false,
  "javascript.format.enable": false
}
```

- **`.eslintrc.json`:**

```javascript
module.exports = {
  root: true,

  extends: ["plugin:vue/essential", "@vue/prettier"],
  plugins: ["vue"],

  env: {
    browser: true,
    node: true
  },

  parserOptions: {
    parser: "babel-eslint",
    ecmaVersion: 2017,
    sourceType: "module"
  }
};
```

Required plugins:
- Prettier
- ESLint
- Vetur

**Comment by ozum** [comment] 2018-10-11 10:03
@Bartozzz thanks, 

Below part solves my problem with vscode, vue, eslint, eslint-prettier integration:

```
{
  "editor.formatOnSave": true,

  "prettier.eslintIntegration": true,
  "prettier.disableLanguages": [],

  "eslint.autoFixOnSave": true,
  "eslint.options": { "extensions": [".html", ".js", ".vue", ".jsx"] },
  "eslint.validate": [
     "javascript",
     "javascriptreact",
     {
       "language": "vue",
       "autoFix": true
     }
  ]
}
```

**Comment by octref** [comment] 2018-10-11 16:57
The setting is wrong. If you don't disable `vue` from `prettier.disableLanguages`, you might be either using the prettier formatter or the Vetur formatter, depending on the extension activation order.

**Comment by Bartozzz** [comment] 2018-10-11 17:07
```
"vetur.format.defaultFormatter.js": "prettier"
```


But this line should prevent this behaviour, nah? Anyway, I'll try to add Vue to disabled languages and see if it works.

**Comment by ozum** [comment] 2018-10-11 17:17
@octref, deleting `"prettier.disableLanguages": []` line disables `vue` in prettier. vscode prettier ignores `vue` by default.

I deleted it as below and it works:

```js
{
  "editor.formatOnSave": true,

  "prettier.eslintIntegration": true,

  "eslint.autoFixOnSave": true,
  "eslint.options": { "extensions": [".html", ".js", ".vue", ".jsx"] },
  "eslint.validate": [
     "javascript",
     "javascriptreact",
     {
       "language": "vue",
       "autoFix": true
     }
  ]
}
```

**Comment by octref** [comment] 2018-10-11 17:56
@ozum Exactly, vscode-prettier has half-baked support for Vue files, that's why it's disabled. Vetur has functionalities not in prettier (and probably will never end up in it):

- Other formatters: js-beautify, prettyhtml, stylus-supremacy, typescript formatter
- Select formatter for ranges: You can choose which formatter to use for which range
- Initial indent in `<style>` and `<script>`. Vetur offers options but prettier doesn't.

**Comment by ozum** [comment] 2018-10-12 03:39
@octref If possible, could you please provide a VSCode config example which works for vue, eslint, eslint-prettier, typescript and tslint as intended.

I created a documentation PR (https://github.com/ozum/vetur/commit/e041273e9206c13af2468191b6f174fba3ab2024) for config above, but I will correct it according your suggestions.

Thanks,

**Comment by MeisterTea** [comment] 2018-10-16 09:09
> @octref, deleting `"prettier.disableLanguages": []` line disables `vue` in prettier. vscode prettier ignores `vue` by default.
> 
> I deleted it as below and it works:
> 
> ```js
> {
>   "editor.formatOnSave": true,
> 
>   "prettier.eslintIntegration": true,
> 
>   "eslint.autoFixOnSave": true,
>   "eslint.options": { "extensions": [".html", ".js", ".vue", ".jsx"] },
>   "eslint.validate": [
>      "javascript",
>      "javascriptreact",
>      {
>        "language": "vue",
>        "autoFix": true
>      }
>   ]
> }
> ```

I don't understand anything about this thread.
Can you use prettier-eslint with vetur or not?
Does it have any issue ?
How can I do it ?
Also, one other thing, does prettier-stylelint works too ?

One last thing, while I am at it, does anyone has a prettier-eslint configuration working without trouble ?
Can we provide a new formatter for vetur ? Where is the doc regarding this ? Is it harcoded ?
Does it apply the multiple fixes from eslint in one pass ?

(Sorry if my comment differs too much from the original issue)

**Comment by octref** [comment] 2018-10-18 15:52
Can someone do me a favor:
- Fork https://github.com/octref/veturpack
- Make whatever edits you need for reproducing the issue, and publish it

**Comment by Coder-256** [comment] 2018-10-26 13:31
I believe that I fixed this in #933 (merged). Can somebody verify?

**Comment by MeisterTea** [comment] 2018-10-26 13:38
> I believe that I fixed this in #933 (merged). Can somebody verify?

It works ! Thank you :+1:

**Comment by octref** [comment] 2018-11-26 08:20
In 0.14.0, the way to use `prettier-eslint` is:

- `"vetur.format.defaultFormatter.js": "prettier-eslint"`

Settings should be read from local pretierrc and eslintrc configs. See [changelog](https://vuejs.github.io/vetur/CHANGELOG.html#_0-14-0-2018-11-26-vsix) and [Format doc](https://vuejs.github.io/vetur/formatting.html#formatters).

**Closed by octref** 2018-11-26 08:20 UTC
Labels: integ:eslint, integ:prettier, lsp:formatting, need-more-info

**Comment by alexeigs** [comment] 2018-11-27 12:33
Open your `settings.json` and overwrite the default settings:

    "vetur.format.defaultFormatterOptions": {
        "prettier": {
            // add your prettier settings here
            "singleQuote": true,
            "semi": false,
        }
    }

**Comment by DutchmanSA** [comment] 2018-12-01 11:34
> In 0.14.0, the way to use `prettier-eslint` is:
> 
> * `"vetur.format.defaultFormatter.js": "prettier-eslint"`
> 
> Settings should be read from local pretierrc and eslintrc configs. See [changelog](https://vuejs.github.io/vetur/CHANGELOG.html#_0-14-0-2018-11-26-vsix) and [Format doc](https://vuejs.github.io/vetur/formatting.html#formatters).

This solved it for me. Thanks!

**Comment by deveplon** [comment] 2019-01-20 17:43
Well right now the only approach I found to solve this problem is like say @alexeigs add my own vetur configuration base on my prettier & eslint config, I use airbnb and add this to my settings in vsCode

`"vetur.format.defaultFormatter.js": "prettier-eslint",
"vetur.format.defaultFormatterOptions": {
	"prettier": {
		"singleQuote": true,
		"semi": true,
		"stylelintIntegration": true,
		"eslintIntegration": true,
		"trailingComma": "es5"
	}
}`

**Comment by Frondor** [comment] 2019-07-19 02:12
Is it hard for vetur to load the current prettier settings?

**Comment by jersonlatorre** [comment] 2022-02-21 21:04
> Open your `settings.json` and overwrite the default settings:
> 
> ```
> "vetur.format.defaultFormatterOptions": {
>     "prettier": {
>         // add your prettier settings here
>         "singleQuote": true,
>         "semi": false,
>     }
> }
> ```

Thanks!!! This is what was looking for.
