### ISSUE TITLE
wrong typing of "this" when returning concatenated string in computed

### ISSUE THREAD

**Issue by jbmaisner** [vuejs/vetur#1554] opened 2019-11-26 15:08 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version: 1.40.2

## Problem

When I return a concat string + props in a computed, the keyword "this" is wrong typed in methods and lifecycle hooks. It's no more typed as "CombinedVueInstance" which causes some problems with Intellisense suggestions and type safe javascript through JSDoc.
Please see screenshots for better comprehension.

Wrong typing of keyword "this"
<img width="432" alt="Capture d'écran 2019-11-26 16 03 34" src="https://user-images.githubusercontent.com/5312996/69645539-9de59980-1066-11ea-87e5-0e7d5104cb8d.png">

Correct typing of keyword "this"
<img width="439" alt="Capture d'écran 2019-11-26 16 03 19" src="https://user-images.githubusercontent.com/5312996/69645560-a50ca780-1066-11ea-8f1c-273f0d595416.png">

## Reproducible Case
You can simply insert the following code example,
Or create a SFC with any template, then in the script section, add a mounted hook and a lambda method. Finally add a computed returning a string + props.

Hover the keyword "this" in the mounted hook or in the method.

Code example 
```
<template>
	<div/>
</template>

<script>
export default {
	props: {
		tata: {
			type: String,
			default: null
		}
	},

	computed: {
		titi () {
			return 'toto' + this.tata;
		}
	},

	mounted () {
		this.$el;
	},

	methods: {
		toto () {
			console.log(this.tata);
		}
	}
};
</script>
```

**Comment by kernZero** [comment] 2019-11-26 15:24
+1 same problem on same platform

**Comment by octref** [comment] 2020-02-11 23:28
This seems to work fine for me (annotating the return type)

```vue
<template>
	<div></div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
	props: {
		tata: {
			type: String,
			default: null
		}
	},

	computed: {
		titi (): string {
			return 'toto' + this.tata;
		}
	},

	mounted () {
		this.$el;
	},

	methods: {
		toto () {
			console.log(this.tata);
		}
	}
})
</script>
```

I guess it's somewhat related to #30854. Need to file a new issue in TS...

**Comment by F0rsaken** [comment] 2020-03-19 09:45
@jbmaisner @kernZero you can use JSDoc to annotate return types of computed and fix your issue

**Comment by octref** [comment] 2020-06-07 04:23
I can confirm, adding JSDoc annotation works. But upstream issue is closed as `Working as Intended` so there's nothing I can do.

@DanielRosenwasser This used to work as expected and fixing this would help a lot of beginner Vue users who don't know TS.

![image](https://user-images.githubusercontent.com/4033249/83960152-033d0180-a8b8-11ea-81c1-b9454080285d.png)

**Comment by DanielRosenwasser** [comment] 2020-06-08 07:09
Can you give it a shot on TS 3.9.5? There were a few small fixes that might have helped there.

**Comment by octref** [comment] 2020-06-16 01:03
I'm using `typescript@4.0.0-dev.20200615`, still doesn't work

```vue
<template>
	<div/>
</template>

<script>
import Vue from 'vue'

export default {
	props: {
		tata: {
			type: String,
			default: null
		}
	},

	computed: {
    /**
     * @returns {string}
     */
		titi () {
			return 'toto' + this.tata;
		}
	},

	mounted () {
		this.$el;
	},

	methods: {
		toto () {
			console.log(this.tata);
		}
	}
};
</script>
```

Once you remove the JSDoc, `this` fails to resolve its type.

**Comment by yoyo930021** [comment] 2020-08-01 06:19
I think duplicate of #1707 ?

**Comment by octref** [comment] 2020-09-04 01:31
Duplicate of #1707.

**Closed by octref** 2020-09-04 01:31 UTC
Labels: integ:typescript, integ:vue, upstream
