### ISSUE TITLE
VLS Not Working When Loading Templates Using src Attribute

### ISSUE THREAD

**Issue by XiNiHa** [vuejs/vetur#2277] opened 2020-09-15 00:52 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.27.3, tried various older versions
- VS Code version: 1.49.0

## Problem

VLS doesn't do anything when I import the template using `<template src="<filepath>"/>`. It works again when I put the template directly into the SFC. I have tried self-closing and paired form and both didn't work.

VLS Output:
```
[Trace - 9:44:57 AM] Sending request 'initialize - (0)'.
[Trace - 9:44:59 AM] Received notification 'window/logMessage'.
Loaded bundled typescript@4.0.2.
[Trace - 9:44:59 AM] Received notification 'window/logMessage'.
Vetur initialized
[Trace - 9:44:59 AM] Received response 'initialize - (0)' in 2002ms.
[Trace - 9:44:59 AM] Sending notification 'initialized'.
[Trace - 9:44:59 AM] Sending notification 'workspace/didChangeConfiguration'.
[Trace - 9:44:59 AM] Sending notification 'textDocument/didOpen'.
[Trace - 9:44:59 AM] Received request 'client/registerCapability - (0)'.
[Trace - 9:44:59 AM] Sending response 'client/registerCapability - (0)'. Processing request took 0ms
[Trace - 9:44:59 AM] Sending request 'textDocument/documentSymbol - (1)'.
[Trace - 9:44:59 AM] Sending request 'textDocument/codeAction - (2)'.
[Trace - 9:44:59 AM] Sending request 'textDocument/documentLink - (3)'.
[Trace - 9:44:59 AM] Sending request 'textDocument/documentColor - (4)'.
[Trace - 9:45:00 AM] Sending request 'textDocument/foldingRange - (5)'.
[Trace - 9:45:01 AM] Sending notification '$/cancelRequest'.
[Trace - 9:45:01 AM] Sending request 'textDocument/documentSymbol - (6)'.
[Trace - 9:45:01 AM] Sending notification '$/cancelRequest'.
[Trace - 9:45:01 AM] Sending request 'textDocument/codeAction - (7)'.
[Trace - 9:45:07 AM] Sending request 'textDocument/hover - (8)'.
[Trace - 9:45:18 AM] Sending notification '$/cancelRequest'.
```

## Reproducible Case

1. Create a SFC with script section
2. Create a HTML file to put the template code
3. Add the HTML file as the template using `<template src="<filepath>"/>`
4. VLS stops working

**Comment by octref** [comment] 2020-09-21 03:43
Duplicate of #1499.

**Closed by octref** 2020-09-21 03:43 UTC

**Comment by XiNiHa** [comment] 2020-09-22 02:01
@octref I think this issue is a more fundamental one since it is not only about the template but for the entire `<script>` section. At least it doesn't seem like a duplicate.

**Comment by octref** [comment] 2020-09-22 03:06
Even if you use `<template src` the script section still works for me.
I don't think we'll support external HTML templates in any time soon.

![image](https://user-images.githubusercontent.com/4033249/93840629-9feaaa00-fcc3-11ea-8313-c470bd081994.png)
