### ISSUE TITLE
Syntax highlighting breaks on script when template includes self-closing and a src with a slash

### ISSUE THREAD

**Issue by marco-gattelli** [vuejs/vetur#836] opened 2018-07-05 10:42 UTC
- [X] I have searched through existing issues

## Info

- Platform: macOS
- Vetur version: 0.12.5
- VS Code version: 1.24.1

## Problem
When using a self closing template tag Vetur does not highligth script tag correctly.

![captura de pantalla 2018-07-05 a las 12 18 16](https://user-images.githubusercontent.com/39620741/42318829-808b3eb4-8050-11e8-9575-0d0c18690474.png)

But if I remove the `/` in the `src` tag, magically:

![captura de pantalla 2018-07-05 a las 12 40 33](https://user-images.githubusercontent.com/39620741/42318882-a65b42f6-8050-11e8-82a1-d09496197ba0.png)

@octref probably the problem is in the regex..??

**Comment by Webifi** [comment] 2019-10-31 04:51
I'm seeing this as well on Vetur 0.22.6, Windows 10, Vscode 1.39.2.

**Comment by octref** [comment] 2019-12-12 18:28
Best advice I can give now is to **not** use self-closing `<template>` for imports.

**Comment by gfernandez-me** [comment] 2020-01-10 22:16
same here

same issue here maybe: https://github.com/vuejs/vetur/issues/1577

**Comment by octref** [comment] 2020-02-10 20:57
Duplicate of #1211, which was fixed.

**Closed by octref** 2020-02-10 20:58 UTC
Labels: grammar, help wanted

**Comment by octref** [comment] 2020-02-10 20:59
Syntax highlighting is fixed, language regions not, so #1577 is still open.
