### ISSUE TITLE
Add TypeScript support for VSCode 'Vue.js interpolations IntelliSense'

### ISSUE THREAD

**Issue by FlorianWendelborn** [vuejs/vetur#1146] opened 2019-03-11 16:50 UTC
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS Mojave
- Vetur version: 0.16.2
- VS Code version: 1.32.1

## Problem

The normal JavaScript works great, but unfortunately TypeScript class-based components don't work at all. Hopefully, it's possible to also get them to work.

## Reproducible Case

Try autocompletion in literally any class-based TypeScript component.

**Comment by octref** [comment] 2019-04-04 19:45
Duplicate of https://github.com/vuejs/vetur/issues/1105.

**Closed by octref** 2019-04-04 19:45 UTC
