### ISSUE TITLE
Throw error while using  Optional chaining Syntax

### ISSUE THREAD

**Issue by ringcrl** [vuejs/vetur#1548] opened 2019-11-25 08:26 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.22.6
- VS Code version:1.40.1

## Problem

Our project is 【Not a Typescript project】，but it's already used Optional chaining Syntax，I can't find a way to remove the syntax error tips

## Reproducible Case

![image](https://user-images.githubusercontent.com/16740021/69524050-3238f900-0fa0-11ea-9d88-05e458538bc4.png)

**Comment by ktsn** [comment] 2019-11-25 10:32
Duplicate of #1510, #1503, #1498, #1438
Please search issue list before opening issue. Thank you.

**Closed by ktsn** 2019-11-25 10:32 UTC
