### ISSUE TITLE
The .vue files syntax get all error in node_modules

### ISSUE THREAD

**Issue by lcysgsg** [vuejs/vetur#2177] opened 2020-08-17 08:21 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.26.1
- VS Code version: 1.48.0

> vscode about
Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

## Problem

I try to disable all installed extensions except `vetur` and clean settings.json, but not work. 
it's only happen in node_modules.
![image](https://user-images.githubusercontent.com/19550000/90373452-82169d80-e0a4-11ea-880e-e9ba8f3998ef.png)
![image](https://user-images.githubusercontent.com/19550000/90373681-df125380-e0a4-11ea-92e9-9b377604bcb6.png)

**Comment by yoyo930021** [comment] 2020-08-18 07:15
Duplicate of #1451

**Closed by yoyo930021** 2020-08-18 07:15 UTC
Labels: duplicate
