### ISSUE TITLE
feature request: highlight for template grammar in es6 string

### ISSUE THREAD

**Issue by yozman** [vuejs/vetur#665] opened 2018-01-24 10:27 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: 
- Vetur version: 0.11.6
- VS Code version: 1.19.2

## Problem

I have a component like this
```javascript
import world from './world';

const template = `
  <h1>hello</h1>
`;

const component = {
  template,
};

export default {
  children: [
    world,
  ],
  component,
  name: 'hello',
  path: 'hello',
};
```
`code highlight` not work, could you please make it work?

**Comment by HerringtonDarkholme** [comment] 2018-01-24 15:41
Actually this is a duplicate of https://github.com/vuejs/vetur/issues/49

**Comment by octref** [comment] 2018-01-24 16:08
Yeah agreed. Let's track it in #49.

**Closed by octref** 2018-01-24 16:08 UTC
Labels: duplicate

**Comment by yozman** [comment] 2018-02-23 13:55
@HerringtonDarkholme @octref 

why don't u guys do like this plugin [es6-string-html](https://github.com/mydesireiscoma/es6-string-html) so we can use like
```javascript
// default use html
const template = `
  <h1>hello world</h1>
`;
// use costom
const template = /* pug */`
  h1
    | hello world
`;
```

so hardcode maybe a right way
