### ISSUE TITLE
Vue 2 project slots type checking

### ISSUE THREAD

**Issue by IndexXuan** [vuejs/vetur#3016] opened 2021-06-21 03:04 UTC
- [x] I have searched through existing issues

## Feature Request

like volar, can vetur auto infer slot typings and give type checker, not v-slot="xxx" means any and since we cannot disabled line like ts-ignore, more and more type errors show up and we cannot use VTI anymore.

Volar said it support Vue 2 but it is not. We hope vetur support this feature ~ thanks a lot.
https://github.com/johnsoncodehk/volar/issues/273#issuecomment-864577291

**Comment by yoyo930021** [comment] 2021-06-21 08:36
Duplicate of #2929

**Closed by yoyo930021** 2021-06-21 08:36 UTC
Labels: duplicate
