### ISSUE TITLE
Fails to respect tsconfig when in a Workspace

### ISSUE THREAD

**Issue by stgogm** [vuejs/vetur#1920] opened 2020-05-18 19:14 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem

It doesn't respect the tsconfig when project is inside a workspace:

![image](https://user-images.githubusercontent.com/2774311/82250511-97e7bb80-9919-11ea-9280-a0a146d00298.png)

But it works when opened as a folder:

![image](https://user-images.githubusercontent.com/2774311/82250607-c6fe2d00-9919-11ea-8984-3636a047ebec.png)

## Reproducible Case

1. Create a new project.
1. Create another project and add to Workspace.
1. Restart VSCode and open workspace.
1. Errors appear because `tsconfig.json` is not respected for the project.

**Comment by stgogm** [comment] 2020-05-28 18:53
Upon further investigation I was able to determine that Vetur uses the `tsconfig.json` file from the first project in the workspace.

**Comment by yoyo930021** [comment] 2020-06-03 12:46
#424 
The Vetur is not supported for this on now.

**Comment by octref** [comment] 2020-06-08 03:07
Duplicate of #424.

**Closed by octref** 2020-06-08 03:07 UTC
