### ISSUE TITLE
There is an error when I input ' this. '

### ISSUE THREAD

**Issue by dgburn** [vuejs/vetur#246] opened 2017-06-21 09:38 UTC
vetur initialized
[Error - 下午5:25:20] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'parameters' of undefined
  Code: -32603

**Comment by dgburn** [comment] 2017-06-21 11:09
When there is  the components Object will appear this error

**Comment by octref** [comment] 2017-06-21 11:16
Code? Screenshot? Platform? Version?

**Comment by HerringtonDarkholme** [comment] 2017-07-03 06:40
Probably a duplicate of #296 .

**Comment by octref** [comment] 2017-07-03 07:16
Closed due to inactivity. Feel free to reopen if you can provide more info.

**Closed by octref** 2017-07-03 07:16 UTC
Labels: need-more-info
