### ISSUE TITLE
Path completion in JS `import` does not work

### ISSUE THREAD

**Issue by Hulkmaster** [vuejs/vetur#1055] opened 2019-01-10 14:54 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.14.5
- VS Code version: 1.30.2

## Problem

Autocomplete for imports does not work in single-file-components
Also autoimport does not work

I have VSCode with only vetur installed (tried reinstall)

![vetur](https://user-images.githubusercontent.com/2781622/50976302-e9936100-14ef-11e9-902b-2f88ef5a79c8.gif)
[vetur.log](https://github.com/vuejs/vetur/files/2745821/vetur.log)

## Reproducible Case

(vue-cli)
`vue create testapp`

in App.vue try `import "./"` - there will be no useful suggestions
same with autoimporting

**Comment by jon301** [comment] 2019-01-11 13:19
I guess it's related to https://github.com/vuejs/vetur/issues/684

**Comment by KytoSai** [comment] 2019-01-18 06:17
The 'auto complete path' feature in 'vetur' has been inactive for a long time
I have same issue. It work great with .js .jsx nhưng .vue don't work !

**Comment by JohnDeved** [comment] 2019-03-06 09:31
having the same issues here.
path autocomplete doesnt work at all. 
and autoimport sometimes file to work.
inside a object for example

**Comment by thedamon** [comment] 2019-04-24 19:58
[this page in the docs makes me think it will work](https://vuejs.github.io/vetur/setup.html#project-setup)

but I also cannot make it work

**Comment by bschulte** [comment] 2019-05-09 18:24
I've had the same issue and for now I've found that the [Path Intellisense](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense) plugin has been working for me to fill the void for path autocompletion.

Just wanted to post here in case anyone else was wondering about an alternative for this functionality.

**Comment by octref** [comment] 2019-05-15 17:57
Duplicate of #822 which is fixed in #1290.

**Closed by octref** 2019-05-15 17:57 UTC
Labels: bug, integ:typescript
