### ISSUE TITLE
File '/Users/xxx/components/Logo.vue' is not a module 

### ISSUE THREAD

**Issue by ppzzppz** [vuejs/vetur#1709] opened 2020-02-14 13:17 UTC
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: https://vuejs.github.io/vetur
- VS Code version: 
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

## Problem
error: `File '/Users/xxx/components/Logo.vue' is not a module ` in vue file

![image](https://user-images.githubusercontent.com/34941345/74534292-5dfbc780-4f6e-11ea-8a02-93cca736e162.png)

import `vue component` is ok in ts file
![image](https://user-images.githubusercontent.com/34941345/74534578-fc882880-4f6e-11ea-98e4-d28efd314a2d.png)

nuxt build also is ok 

## Reproducible Case

- create Nuxt.js + Typescript project

**Comment by davelsan** [comment] 2020-03-04 11:48
Can reproduce. Also, possible duplicate of #1716. As described in that issue, creating an empty export removes the error.

```ts
import Vue from 'vue'
export default Vue.extend({
  //
})
```

**Comment by ppzzppz** [comment] 2020-03-04 12:24
Thanks, to add `script`  resolve

<img width="574" alt="image" src="https://user-images.githubusercontent.com/34941345/75879275-12925600-5e56-11ea-8399-3b348e024b42.png">

**Closed** 2020-03-05 16:49 UTC

**Comment by crhistianramirez** [comment] 2020-05-16 13:28
Looks like you can add this setting in vetur without having to create an empty export :
```json
 "vetur.experimental.templateInterpolationService": true,
```

As mentioned [in this comment](https://github.com/vuejs/vetur/issues/1187#issuecomment-489638186)

**Comment by AllanOricil** [comment] 2020-06-12 23:10
How can I fi it? It seems Im still with it.
![image](https://user-images.githubusercontent.com/55927613/84552908-be1a3480-ace8-11ea-9a39-f2ab99a821ae.png)

**Comment by AllanOricil** [comment] 2020-06-12 23:16
Hi guys. I noticed my mistake. My component was declared with .vue but because it had no implementation at all, it was not being understand by Vetur. Is it expected?
