### ISSUE TITLE
Support intelliSence for class style vue and vue-property-decorator

### ISSUE THREAD

**Issue by John0King** [vuejs/vetur#1872] opened 2020-04-25 03:38 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Win
- Vetur version: 0.24.0
- VS Code version: 1.44.2

## Problem

doesn't support class style vue with `vue-property-decorator`  for tag/property IntelliSence

## Reproducible Case

```vue
<template>
  <div class="hello">
    <h1 @click="onGo()">{{ msg }}</h1>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue, Emit } from 'vue-property-decorator';

@Component
export default class HelloWorld extends Vue {
  @Prop() 
  msg!: string;

  @Emit("go")
  onGo(){
    return "go";
  }
}
</script>
```

**Comment by yoyo930021** [comment] 2020-04-27 07:49
Wait for #1323.

**Comment by octref** [comment] 2020-06-08 02:04
Duplicate of #1105.

**Closed by octref** 2020-06-08 02:04 UTC
