### ISSUE TITLE
Veture 0.19.1   Are You Kidding Me

### ISSUE THREAD

**Issue by louieaa** [vuejs/vetur#1248] opened 2019-04-25 09:17 UTC
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info
 
Property 'titleName' does not exist on type 'CombinedVueInstance<{ pageTitle: string; } & { handlePanelControl(data: any): void; handleActConfigInit(): void; } & Record<never, any> & Vue, object, object, object, Record<never, any>>'.

- Platform: 
- Vetur version: 0.19.1
- VS Code version:  1.33.1 (1.33.1)

## Problem
![image](https://user-images.githubusercontent.com/42113246/56724506-ba8ebb80-677d-11e9-821d-05ca238dcc23.png)
![image](https://user-images.githubusercontent.com/42113246/56724521-c2e6f680-677d-11e9-82ae-404fb6290432.png)
![image](https://user-images.githubusercontent.com/42113246/56724548-d09c7c00-677d-11e9-95a4-32a52a0c177e.png)

**Comment by jhgrrewq** [comment] 2019-04-25 09:36
same problem

**Comment by louieaa** [comment] 2019-04-25 09:52
Solution：  back version 0.18.1

**Comment by kinesias** [comment] 2019-04-25 10:09
Temporary solution: "vetur.experimental.templateInterpolationService": false

**Comment by stefnotch** [comment] 2019-04-25 10:56
@louieaa Would you mind posting your .vue file or a simple way to reproduce those errors?

**Comment by vinayakkulkarni** [comment] 2019-04-25 10:59
Had to revert to 0.18.1

**Comment by lopugit** [comment] 2019-04-25 15:09
yeah I reverted to 0.18.1 too cause it fucked up string literal colours lmfao omg

Link to the vsix from others: https://octref.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.18.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by octref** [comment] 2019-04-25 15:25
No repro case -> closing.

**Closed by octref** 2019-04-25 15:25 UTC

**Comment by lopugit** [comment] 2019-04-25 15:28
> No repro case -> closing.

wut

open vscode, install vetur 0.19.1

make new file test.vue

type 
```
<template lang="pug">
.test(
  @click=`
    if(this){}
  `
)
</template>
```
and 
```
@click=`
    if(this){}
  `
```

and it'll look fked up

**Comment by octref** [comment] 2019-04-25 15:38
Your issue is not even the same issue.

**Comment by v-angolenko** [comment] 2019-04-25 18:19
Vetur version: 0.19.1

We have recently got  similar error on each $style in our template. We use CSS Modules that is provided by vue-loader. 

<img width="788" alt="Снимок экрана 2019-04-25 в 21 08 56" src="https://user-images.githubusercontent.com/49995115/56758515-80ceac80-679f-11e9-82f7-13708c0248e9.png">

**Comment by yogsky** [comment] 2019-04-25 19:21
I have the same case, my template uses properties received through vuex's mapGetters.
all of them have the '...does not exist on type 'CombinedVueInstance' error on them 😭

**Comment by louieaa** [comment] 2019-04-26 03:26
@stefnotch  Of course, Please update Vetur version: 0.19.1 or 0.19.0

**Comment by Farkal** [comment] 2019-04-26 12:23
Just to say it's resolved in 0.19.2 just check VS Code have updated the extension (for my case I need to click on reload)

**Comment by stefnotch** [comment] 2019-04-26 16:05
It's "fixed" in [0.19.2](https://github.com/vuejs/vetur/releases/tag/v0.19.2) because the experimental feature causing all of this was turned off. See https://github.com/vuejs/vetur/issues/1246

The experimental feature is still in the extension and it would be great if people would test it to make sure that everything works how it's supposed to once it gets turned on again.
