### ISSUE TITLE
Just syntax highlighting problems [Need Release]

### ISSUE THREAD

**Issue by cycold** [vuejs/vetur#599] opened 2017-12-19 06:34 UTC
- [√] I have searched through existing issues
- [x ] I have read through [docs](https://vuejs.github.io/vetur)
- [x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:macOS
- Vetur version: v0.11.5
- VS Code version: Version 1.19.0 (1.19.0)
- theme color: Atom One Dark

## Problem

Css className start with underline should have the same color

![qq20171219-142106](https://user-images.githubusercontent.com/2446601/34143679-dd1c2a04-e4c8-11e7-997c-a8125e3368b5.png)

**Comment by cycold** [comment] 2017-12-21 02:53
There is a another problem, see pictures:

when style tag with src attr and keep one line(nowrap) then the javascript syntax highlighting is not working

![qq20171221-104743](https://user-images.githubusercontent.com/2446601/34238428-7eeed25e-e63c-11e7-964b-61d2d37c38b7.png)

If style tag keep wrap then the javascript syntax highlighting is working.

![qq20171221-104756](https://user-images.githubusercontent.com/2446601/34238493-e42dcb84-e63c-11e7-9f37-a779e475c08f.png)

PS: I know I can `import style.scss`, but I don't like it. Sorry poor English...

**Comment by MaxMilton** [comment] 2018-01-02 03:10
I have similar <style> highlighting issue but with plain CSS. For me the issue is IDs:
![screenshot from 2018-01-02 13-52-18](https://user-images.githubusercontent.com/14946546/34473438-a50059ac-efc6-11e7-9e58-ce93ffd26dc0.png)

**Comment by cedeber** [comment] 2018-01-09 21:27
I confirm the `<style>` and `<script>` single line highlighting issue.
Latest VS Code, latest Vetur, default color scheme.

**Comment by HerringtonDarkholme** [comment] 2018-01-15 06:43
I have tested master branch, all the above issues are fixed.

However, a new release is needed.

@octref

**Comment by octref** [comment] 2018-01-16 07:16
Yeah this is already fixed in master. We'll do a release soon.

**Closed by octref** 2018-01-16 07:16 UTC
Labels: grammar
