### ISSUE TITLE
Typescript - 'Cannot find name ____' when annotating props with interface 

### ISSUE THREAD

**Issue by sergmister** [vuejs/vetur#2857] opened 2021-04-10 00:40 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: Linux
- Vetur version: 0.33.1
- VS Code version: 1.55.1

## Problem

When I use an interface to annotate props Vetur gives give the error 'Cannot find name 'Foo'. Vetur(2304)'.

## Reproducible Case
This setup works perfectly fine:
Test.vue
```vue
<script lang="ts">
import { defineComponent, PropType } from "vue";

export interface Foo {
  name: string;
}

export default defineComponent({
  props: {
    foo: { type: Object as PropType<{ name: string }> },
  },
});
</script>
```
App.vue
```vue
<template>
  <p>hi</p>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import Test from "@/test.vue";

export default defineComponent({
  components: { Test },
});
</script>
```
However, when I change props in Test.vue to
```vue
  props: {
    foo: { type: Object as PropType<Foo> },
  },
```
Vetur give the error 'Cannot find name 'Foo'. Vetur(2304)' at the top of App.vue. The code runs just fine in Vue.

**Comment by HayasyLL** [comment] 2021-04-10 04:33
same issue when pass props as PropType

in child component
![image](https://user-images.githubusercontent.com/22284698/114258362-9e32ca80-99f8-11eb-84bc-5312e528e309.png)

in parent component, pass object to child component
![image](https://user-images.githubusercontent.com/22284698/114258386-b60a4e80-99f8-11eb-8242-50b1d2269787.png)

first line of parent component
![image](https://user-images.githubusercontent.com/22284698/114258412-e651ed00-99f8-11eb-9e0f-6af328cf282a.png)

**Comment by yoyo930021** [comment] 2021-04-10 16:19
Duplicate of #2668

**Closed** 2021-04-10 16:19 UTC
Labels: duplicate
