### ISSUE TITLE
Sub-Component type check: optional fields are mis interpolated when kebab-cased

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vetur#2345] opened 2020-09-29 14:09 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.28.0
- VS Code version: 1.49.1

## Problem
For a given component defined like such :
```ts
defineComponent({
  props: {
    iconPosition: {
      type: String as () => 'left'|'right',
      default: 'left',
      required: false,
    },
  },
})
```
![](https://imgur.com/hw68wEN.png)

### What's happening ?
for `icon-position` typings are interpreted as `'icon-position?' : any`

### What's expected ?
for `icon-position` typings should put the question mark outside the string key like that: `'icon-position'? : any`

## Reproducible Case

Coming soon I promise

**Comment by yoyo930021** [comment] 2020-09-30 01:34
Duplicate of #2314

**Closed** 2020-09-30 01:34 UTC
Labels: duplicate
