### ISSUE TITLE
No more typescript errors showing in 0.22.5

### ISSUE THREAD

**Issue by thibautguedou3** [vuejs/vetur#1473] opened 2019-10-22 16:11 UTC
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.22.5
- VS Code version: 1.39.2

## Problem

I have updated this afternoon to version 0.22.5 and I could no longer see typescript errors in every .vue files. Autocompletion has also disappeared. I have seen that you have fixed a typescript issue in the latest release, do I need to update something in my Vetur configuration?

*Observed behavior*:  Nothing is displayed when I edit a vue file
![VSCOde broken](https://user-images.githubusercontent.com/31597701/67306350-1e106080-f4f7-11e9-83f4-9485e4703313.png)

*Expected behavior*: 
![VSCode](https://user-images.githubusercontent.com/31597701/67306127-c3770480-f4f6-11e9-9541-6755604c0964.png)

*Temporary Solution*: Rollback to 0.22.4

**Comment by douglasg14b** [comment] 2019-10-22 18:04
Same, this is alongside the loss of intellisense.

**Comment by octref** [comment] 2019-10-22 18:28
See https://github.com/vuejs/vetur/issues/1449#issuecomment-544908139, I'll merge https://github.com/vuejs/vetur/pull/1472 soon to fix it.

**Comment by octref** [comment] 2019-10-23 19:59
Duplicate of #1476. Fixed by #1472 and released in 0.22.6.

**Closed by octref** 2019-10-23 19:59 UTC
Labels: duplicate
