### ISSUE TITLE
Extension size is huge (70MB) and can be shrunk dramatically

### ISSUE THREAD

**Issue by robole** [vuejs/vetur#2359] opened 2020-10-08 07:07 UTC
- [x] I have searched through existing issues

## Feature Request

I noticed that Vetur is 70MB. I built some extensions recently and discovered that you only need to include the following files in the VSIX package: source code, readme, changelog, package.json, and any images referenced in package.json. All the other files can be excluded in the *.vscodeignore*. 

If you would like to see a comparable example you can look at the [python extension](https://github.com/Microsoft/vscode-python). It excludes all node modules in it's [*.vscodeignore*](https://github.com/microsoft/vscode-python/blob/main/.vscodeignore). And it has a lot of node dependencies! It is > 50% smaller than your extension!

Another advantage of doing this is that it improves the activation time of your extension. Especially the first time it is run because the VSIX is uncompressed. Vetur takes about 10 seconds to activate on the first run!

If you would like me to submit a PR to do this, I would be happy to. Let me know :-)

**Comment by yoyo930021** [comment] 2020-10-08 07:26
They also have `node_modules` folder in python extension.
You can extract [file](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-python/vsextensions/python/2020.9.114305/vspackage).
We need to bundle tool like webpack, rollup.
It's the only way to solve this problem.
but it is difficult.

Please follow #2301 #2233

**Comment by yoyo930021** [comment] 2020-10-08 07:26
Duplicate of #2233

**Closed** 2020-10-08 07:26 UTC
Labels: duplicate

**Comment by robole** [comment] 2020-10-08 07:35
Hi @yoyo930021 ,

You can exclude the dev dependencies and asset folder without bundling.

**Comment by yoyo930021** [comment] 2020-10-08 07:37
> Hi @yoyo930021 ,
> 
> You can exclude the dev dependencies, asset folder, and spurious files without bundling. This would be a good start.

Doing now.
https://github.com/vuejs/vetur/blob/master/build/release-cleanup.sh
