### ISSUE TITLE
Report error position did not follow the change/edit when line is collapsed

### ISSUE THREAD

**Issue by yoyo837** [vuejs/vetur#405] opened 2017-08-25 04:22 UTC
- [×] I searched through existing issues.
- [√] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: Windows 10 x64 15063
- Vetur version: 0.9.5
- VSCode version: 1.15.1 x64

## Problem

No VPN, cannot upload screenshot.

## Reproducible Case

Step:
1.  make html like this:
``` html
    <div v-if="serverData.dealTicketList" class="ctx-bg">
      <div v-for=""></div> <!-- I made a mistake,this line report error, show red underline. Of course it should be report error. -->
    </div>
```
2. Collapse first div line, it look like this:
``` html
    <div v-if="serverData.dealTicketList" class="ctx-bg">... 
    <!-- Now, The red underline position is before the three points('...'). -->
```
3. Edit this line of HTML code before the three points position like this:
``` html
    <div v-if="serverData.dealTicketList && serverData.dealTicketList.length" class="ctx-bg">...
    <!-- Now, The red underline position did not follow the change/edit -->
```

**Comment by HerringtonDarkholme** [comment] 2017-08-31 09:03
Hi, I cannot reproduce this. Would you mind provide more info? Or try it in https://github.com/octref/veturpack ?

![screen shot 2017-08-31 at 5 01 35 pm](https://user-images.githubusercontent.com/2883231/29915327-2037c502-8e6e-11e7-9898-059c1cca634e.png)
![screen shot 2017-08-31 at 5 01 41 pm](https://user-images.githubusercontent.com/2883231/29915328-20386610-8e6e-11e7-9fc9-262e9a7d4347.png)
![screen shot 2017-08-31 at 5 01 54 pm](https://user-images.githubusercontent.com/2883231/29915329-21548e5c-8e6e-11e7-9fe4-d774349a08a8.png)

**Comment by yoyo837** [comment] 2017-08-31 10:52
![40795358-3db6-4afd-943c-2fc53c5f9bd1](https://user-images.githubusercontent.com/6134547/29919825-71a8812e-8e7d-11e7-95f3-4dc420920b8f.png)
![9cd327d5-36fb-469e-b667-5b576bd349bd](https://user-images.githubusercontent.com/6134547/29919827-72c52224-8e7d-11e7-9468-24472cc5d115.png)

**Comment by HerringtonDarkholme** [comment] 2017-08-31 10:57
Screen shot just says the problem exists, but it doesn't provide other information.

Can you reproduce it in veturpack?

**Comment by yoyo837** [comment] 2017-08-31 11:07
It's very very very too hard to find a VPN for upload screenshot.  :(  F*** GFW.

I'll try to reproduce it in veturpack later.

**Comment by yoyo837** [comment] 2017-08-31 11:36
No error reported in client/**/*.vue:
```html
    <div v-if="">
      <div v-for=""></div>
    </div>
```
Maybe I did not get the point.

**Comment by HerringtonDarkholme** [comment] 2017-08-31 14:54
Can you paste the output?
Ctrl-Shift-P -> toggle output -> select VueLanguageServer in the dropdown.

I guess some error occurred.

**Comment by yoyo837** [comment] 2017-08-31 15:08
No. Just only 'vetur initialized'.

**Comment by HerringtonDarkholme** [comment] 2017-08-31 15:33
Strange. I will try to reproduce it on Windows machine.

**Comment by HerringtonDarkholme** [comment] 2017-09-04 10:15
Confirmed. It seems to be a bug of VSCode.

**Comment by HerringtonDarkholme** [comment] 2017-09-04 10:26
https://github.com/Microsoft/vscode/issues/33786

Let's first close this issue since we cannot do anything here.

**Closed by HerringtonDarkholme** 2017-09-04 10:26 UTC
Labels: upstream, wontfix
