### ISSUE TITLE
Using TypeScript 4.5 as workspace dependency

### ISSUE THREAD

**Issue by kdlslyv** [vuejs/vetur#3244] opened 2021-11-18 22:35 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: 
- Vetur version: v0.35.0
- VS Code version: 1.62.3

## Problem

Just a tiny heads-up, using TypeScript 4.5.2 with `vetur.useWorkspaceDependencies: true` is broken.

This is only a bit annoying if depending on other versions of Prettier, @starptech/prettyhtml, prettier-eslint, prettier-tslint, stylus-supremacy, @prettier/plugin-pug, which are affected by this setting.

In my case I could get rid of this setting.

![image](https://user-images.githubusercontent.com/13890151/142506683-53c45542-9fdd-4df3-be32-55f70b66d20e.png)

**Comment by LasyIsLazy** [comment] 2021-12-07 07:39
I have met the same issue with `typescript@4.5.2`. So I have to set the setting `"vetur.useWorkspaceDependencies": false`

**Comment by yoyo930021** [comment] 2022-11-01 11:29
Duplicate of https://github.com/vuejs/vetur/issues/3323.
It will also solve it in v0.36.0.

**Comment by yoyo930021** [comment] 2022-11-01 11:29
Duplicate of https://github.com/vuejs/vetur/issues/3323.

**Closed by yoyo930021** 2022-11-01 11:29 UTC
