### ISSUE TITLE
"No formatter for 'vue'-files installed"

### ISSUE THREAD

**Issue by ghoultf** [vuejs/vetur#1223] opened 2019-04-24 08:57 UTC
## Info

- Platform: Win10
- Vetur version: 0.19.0
- VS Code version: 1.33.1
- ESLint version: 1.8.2

## Problem
Can't format .vue files with the new version of Vetur(0.19.0).
![无标题](https://user-images.githubusercontent.com/28552327/56645775-ea23c200-66b0-11e9-8162-2c5141926ee1.png)

This can be resolved by changing the setting vetur.validation.template to false or changing the version of Vetur to 0.18.1.

**Comment by ghoultf** [comment] 2019-04-24 09:13
Probably duplicate with #1220

**Comment by ktsn** [comment] 2019-04-24 15:30
Yeah, this is likely duplicate of #1220. Let's move to it.

**Closed by ktsn** 2019-04-24 15:30 UTC
