### ISSUE TITLE
script/style code is white

### ISSUE THREAD

**Issue by frizar** [vuejs/vetur#1690] opened 2020-01-29 13:10 UTC
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.23.0
- VS Code version: 1.41.1

## Problem
script/style code is white

## Reproducible Case
examples:
1) no bug
![image](https://user-images.githubusercontent.com/8735701/73358756-05f36e80-42a8-11ea-8778-94a9f9998b8e.png)
2) bug
![image](https://user-images.githubusercontent.com/8735701/73358821-228fa680-42a8-11ea-8df7-dbb1398e055b.png)

**Comment by octref** [comment] 2020-02-10 19:15
Duplicate of #1211.

**Closed by octref** 2020-02-10 19:15 UTC
